### ISSUE TITLE
Custom time and date format

### ISSUE THREAD

**Issue by Cu8eR** [flarum/core#1019]
https://discuss.flarum.org/d/2382-custom-time-and-date-format

**Comment by jordanjay29** [comment]
Let's try to discuss on the forums first before starting an issue.

**Comment by Cu8eR** [comment]
I think it shoul be added here, one of the most basic feature

**Comment by jordanjay29** [comment]
That's fine, but we usually let feature requests be discussed on the forums before making them an issue. Mostly because not all feature requests are candidates for inclusion into Core or as a bundled extension. Many members of the community are willing to create extensions, and discussing on forums allows this to happen more often.

**Comment by Cu8eR** [comment]
As you can see in the first post - it was posted by me to Flarum forum 5 months ago :( and no feedback

**Comment by franzliedke** [comment]
@Cu8eR In that case, we will have to assume that there is no major interest for this feature in the community. Which means it is not something we will prioritize in implementing.

You can try to gather more interest in the community. But please understand that GitHub is not the place to do so.

**Comment by Cu8eR** [comment]
Quite sad - 12 HR system is not used in Europe... moreover dont forget about month/date/year format.

**Comment by Kakifrucht** [comment]
You can customize it via language packs.

**Comment by Eldenroot** [comment]
Any changes to this one?
