### ISSUE TITLE
can't search with these word

### ISSUE THREAD

**Issue by pinglanyue** [flarum/core#1038]
- 3 lettert's word.Like SEO、SQL
- you can search “extension” or "extension li" but can't search "extensio"or"extensi"

**Comment by franzliedke** [comment]
Hi, 

yes, that's a known limitation of MySQL's full-text search engine, which we rely on. So there is nothing we can do about this (apart from implementing our own search driver), I'm afraid. 

I believe it is possible to configure MySQL to index shorter words, too, so that is something you could do if you have access to the configuration.
