### ISSUE TITLE
Removing ref="nofollow noreferrer" from internal link

### ISSUE THREAD

**Issue by quangpkv** [flarum/core#1151]
Dear developer team,
I used Flarum for a week and it's so awesome. But I realized Flarum automatically assigns the "nofollow noreferrer" attribute to all links (including internal links).
This will have a serious effect on SEO. So I expect you guys to have a solution to the issue on the next version.
Thank you so much for what you are doing. You guys rock!

**Comment by franzliedke** [comment]
Hello,

first of all, please be aware that this is an open-source project. We do all of this in our free-time. This means you shouldn't *expect* us to do certain things on your timeframe. As a good open-source citizen, you may be able to influence our forward progress by sending pull requests for certain features that are important to you.

That said, please explain what exactly the problem is (in your opinion) with using "nofollow noreferrer" for *user-contributed links*. The way we see it, this is a feature, not a bug. We do this to discourage spam content, and prevent other sites from trying to benefit from a Flarum instance's page rank.

**Comment by tobyzerner** [comment]
Kind of related to flarum/issue-archive#382 (which should be given a more descriptive name) and flarum/framework#859; I think @quangpkv is pointing out that even **internal** links (ie, URLs to other topics/user profiles within the forum) are given these attributes?

**Comment by quangpkv** [comment]
@franzliedke Sorry for asking a lot but I think it is not a private matter. I'm an Android developer and PHP is not my forte, but I love open source. If I have enough standard to do that, I'd love to help.

**Comment by franzliedke** [comment]
Okay, let's close this then.

@quangpkv Please describe your detailed reasoning for why these flags should be removed in flarum/framework#859 (and possibly flarum/issue-archive#382).
