### ISSUE TITLE
Auto discovery

### ISSUE THREAD

**Issue by luceos** [flarum/core#1208]
Taylor recently announced [auto discovery](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) for Laravel 5.5. Most likely this has already crossed your path.

It would be great if we could add this functionality to Flarum perhaps. Some things that could be easily auto discovered:

- js forum and admin, less and locales - this would remove the need for an de facto `AddClientAssets` listener.

Instead of doing auto discovery in the json we can also do it like the migrations set up, checking whether the directory exists and auto loading in that scenario.

Just putting this out here.

**Comment by franzliedke** [comment]
Are we talking about auto discovery for Flarum as a Laravel package, or auto discovery of extensions' features when installing them?

I assume the latter.

If so, I think I would currently lean towards explicitly defining *that* e.g. locale files should be loaded, but providing sane defaults such as paths, so that we can assume a certain directory structure unless custom paths are given.

**Comment by tobscure** [comment]
> If so, I think I would currently lean towards explicitly defining that e.g. locale files should be loaded, but providing sane defaults such as paths, so that we can assume a certain directory structure unless custom paths are given.

Agreed, and that is exactly what is planned with the upcoming Extender API.

**Comment by franzliedke** [comment]
@luceos If that answers your question, please close this issue. Otherwise, please clarify. :wink:
