### ISSUE TITLE
During log out, "Server 500" error if user inactive > 1 Hour

### ISSUE THREAD

**Issue by noriods** [flarum/core#1282]
## Explanation

Members who try to log out after a period of inactivity (possibly 1 hour) get a Server 500 Error.

In my logs, I see PermissionDeniedException errors.

## Technical details

- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: https://community.guitartalk.co.za/ but there are reports of it happening on the Flarum install as well: https://discuss.flarum.org/d/4496-500-error-after-no-activity/3
- nginx
- PHP version: 7.1
- Hosted environment: VPS
- Hosting provider: http://digitalocean.com

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mcrypt, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
EXT flagrow-analytics 0.5.0
EXT flarum-approval v0.1.0-beta.7
EXT s9e-autoimage 1.0.2
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-ads 0.1.0-beta.4
EXT flagrow-masquerade 0.1.4
EXT flagrow-upload 0.6.0-beta
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT noriods-smf-passwords dev-master (59252d52e416cb5eef0e243db33cf50afbfdef04)
EXT terabin-sitemap v1.0.2-beta.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://community.guitartalk.co.za
```

## Log files

None right now - I cleared my logs earlier today :/

**Comment by tobscure** [comment]
This is expected behaviour, because by the time an hour has passed the CSRF token passed in the URL has expired.

Perhaps instead of an error though, it would be good to show a confirmation like WordPress does ("Are you sure you want to log out of [forum title]?")

**Comment by maxiwarecc** [comment]
Yep, aware of the CSRF token issues.

What I've done with Laravel (where the same issue exists) is I check for the exception and then redirect to the login screen with a flashed message along the lines of, "Your session has expired. Please login again." 

It's a simple solution because it can be done in the Middleware - no UX work needed.

**Comment by tobscure** [comment]
Just because the CSRF token has expired, doesn't mean the session has, in that they could have a "remember me" cookie which will automatically log them back in again on the next request. In that case with your proposal they'd click "Log out" and then be taken back to the same page still logged in?

Additionally, it might be nice to offer a way for external sites to prompt the user to log out of the forum (eg. in some SSO solution) by pointing them to /logout without a CSRF token, so the confirmation UX could be good for that.

**Comment by maxiwarecc** [comment]
Ah I see what you mean about the session not necessarily having ended. Totally missed that case.

Not having a CSRF token on the logout route makes sense to me.
