### ISSUE TITLE
Make post divisions/contextual controls more obvious

### ISSUE THREAD

**Issue by tobscure** [flarum/core#133]
![screen shot 2015-06-20 at 2 28 35 pm](https://cloud.githubusercontent.com/assets/128862/8266076/e2810496-1758-11e5-9c8a-b0758708c360.png)

Flarum makes heavy use of whitespace to keep things clean. However, since there are no lines or obvious divisions to guide the eyes:
1. Posts can sometimes kind of blend in to each other, especially with "event posts" (when a discussion is stickied or re-tagged)
2. Contextual controls can be very difficult to find (and it's not easy to tell which post they're for)

Possible solutions:
- Increase whitespace below event posts. Naturally they have less because they don't have a "Reply" control, but really they should match the rest of the posts.
- Remove or relocate the timestamp on event posts.
- Add light horizontal rules between each post (not keen, I feel like it makes the discussion feel more segmented, inhibits its flow)
- Use a colored background and put each post in a white box (not keen, a theme could do this but I want to try and keep the default theme white).
- Move the contextual controls button to the left hand side, just next to the timestamp
- Make the contextual controls button always visible but faded out

**Comment by franzliedke** [comment]
What about a special background for "event posts"?

**Comment by franzliedke** [comment]
> Use a colored background and put each post in a white box (not keen, a theme could do this but I want to try and keep the default theme white).

Actually, I really like this idea. Could look like one of these card-based interfaces that are so cool these days. ;) No really, give this a chance. It would serve as a nice distinction, but you wouldn't have obvious clutter like extra lines between the posts.

**Comment by tobscure** [comment]
I will definitely try it out :)

**Comment by tobscure** [comment]
I had a play with this.
![screen shot 2015-06-22 at 6 47 15 pm](https://cloud.githubusercontent.com/assets/128862/8279469/165e7142-1914-11e5-9951-d0bb777ebffe.png)
(Don't mind the post scrubber, hehe)
I don't really like it. It loses the open-ness that I love about Flarum's interface. It's very segmented, every post feels like an individual piece of writing (i.e. in a news feed) rather than a part of the same conversation. It's also a bit odd when the background color changes between the index and the discussion. Still could definitely be cool in another theme.

I think the best compromise is a faint line between each post. Something to guide the eyes along to the right edge of the post, and demarcate where content starts and ends, but not disconnecting or distracting.
![screen shot 2015-06-22 at 7 28 07 pm](https://cloud.githubusercontent.com/assets/128862/8279609/20c1e208-1915-11e5-82a3-9731d406ed4f.png)

**Comment by tobscure** [comment]
I've implemented this and pushed it up to the dev forum.

For time gaps, I went with a colored background:
![screen shot 2015-06-23 at 10 46 26 am](https://cloud.githubusercontent.com/assets/128862/8296901/97bf525c-1995-11e5-968d-18afbfe03937.png)

I removed the time info from event posts, but I've left their background as-is for now. I'm still interested in this though, here's what it would look like. It certainly does distinguish them from the actual content, which could be a plus. What do you think?
![screen shot 2015-06-23 at 10 48 29 am](https://cloud.githubusercontent.com/assets/128862/8296909/a682e3da-1995-11e5-8b38-647c30286777.png)

**Comment by jmichaelward** [comment]
I like all of these changes. I agree that the lighter horizontal rule between posts is far superior to the separated content, particularly when you consider how the darker background takes over everything (such as the timeline in the sidebar). 

Also, I saw something in my e-mail about event posts and how you've removed the date information but retained their appearance, but I'm not seeing it here on Github. Still, I think your gut feeling is correct that the post info isn't really necessary. Users probably don't necessarily care to know *when* those events happened, and in an active forum, they can intuit it anyway, because each other post does have date information. The gray background helps them stand out and declare their importance, so the only thing you might want to consider down the line is how much importance they need to carry. If that information somehow becomes less relevant (is it important for non-admins to know specifically who stickied something or added a tag to a post? I'm not sure), perhaps a lighter shade of gray or another way to minimize that information might be in order.

All said, things look great and I'm really digging the progress you're making.

**Comment by tobscure** [comment]
@jmichaelward Thanks for your thoughts! Yep I commented saying I'd removed the time info, and also that I was considering giving the event posts a light background, but I quickly decided against that I deleted my comment thinking no one would see it. In hindsight, probably should've just edited it.

Anyway I agree with your points (time info for event posts isn't important and can be inferred). I don't think they need to carry much importance or stand out at all, so I'm quite happy to leave them with a white background :)

These changes are all live on discuss.flarum.org.

**Comment by franzliedke** [comment]
Hmm, interesting. I actually liked the cards-style look you posted above and very much dislike the horizontal rules. On one monitor, I can barely see them anyway. On the other one, they break up the reading flow.

Here's my suggestion: how about a vertical line connecting the avatars? For marking the end of a post, we have multiple options:
- a small gap in the line
- a short horizontal line branching off from the vertical one before a post
- "suggesting" a box around each post by only drawing the top left (and maybe the bottom right) corner

And, of course, we can still try to make the posts themselves look more compact, while slightly increasing the whitespace between posts.

**Comment by amdad** [comment]
@franzliedke  cards-style look is very BOLD. I agree with Toby in that case. Flarum CORE should be simple, based on white space. We can apply own css themes if we want have more heavy visual style.

Also I don't see reason for vertical line. If you want see where post is done, just add some style to authors names (if avatars isn't enough). Because now, bold text is almost the same as authors name.

Vertical lines added also under headings... Gosh, too much mess... distraction.

@tobscure I rather suggest to use **lines** (top and bottom) **ONLY for special messages** like: Toby stickied the discussion. Or any other _non-standard_ discussion / reply _information_. Normal replies should go with regular no-distraction (no-lines) mode.  Your first subtle lines to split time gaps like **3 days  later** was perfect, now is like bar similar to quotes, not very classy. Not very needed, quotes needed visual separation like this, because it's special type of content, rather than just simple additional info.

## Controls

When it comes to controls, I suggested before, that reply button should appear directly in place where we just stop selecting text to quote. Not it's not-friendly on long post when you select line and need scroll down to find reply button. Shortcut key also would be very handy. Select and click **Q** to quote selection.

**Comment by tobscure** [comment]
> @amdad I rather suggest to use lines (top and bottom) ONLY for special messages like: Toby stickied the discussion. Or any other non-standard discussion / reply information. Normal replies should go with regular no-distraction (no-lines) mode.

Interesting idea, will try it out.

>When it comes to controls, I suggested before, that reply button should appear (also) directly in place where we just stop selecting text to quote.

Yes, it's on the todo list :)

**Comment by amdad** [comment]
You can do nice styling for **every special element** that show up on discussion. Play with different colors for different infos like you did for sticks and moderation moves etc. But regular discussion, with one line time gaps separators and pure white for all the rest was very great to read. So play with styles on any other elements. Discussion must be clear as you wanted. I know from experience that when you brake this pureness with anything you'll never get this clarity as you planned from beginning. 

So when I scroll I can watch only on usernames and text I read, when any other thing show up I immediately know some special event has place in this discussion. Everything just pop up much more boldly then.  When thousand lines flashing my eyes, then another one or two are just more mess.

**Comment by amdad** [comment]
Also @tobscure, you can in some way (like subtle color vertical line) highlight, for ** user own replies **, because we treat own posts a little bit differently (one time just skipping them, another time read more carefully to check is everything correct as we mind it, when write/correct it, incl. typos etc,). Like here on github, we have blue highlight, for own posts. 

Also, as another addition by some small icon on avatar,  single out topic author replies. Or 1px border around avatar or whatever.
