### ISSUE TITLE
Avatar upload can be used to leak server IP

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1357]
## Explanation

I'm a big fan of services like Cloudflare but I've noticed the way Flarum handles avatars allows anybody to leak the server IP.

When registering or updating your user settings, you can pass an `avatarUrl` attribute that will be downloaded and set as avatar.

This looks deliberate, however this allows any user to ask the server to perform a request to any given url.

Maybe this should be limited to admins or controlled via a permission ?

## Technical details

- Version of Flarum: master

Both `Flarum\User\Command\RegisterUserHandler` and `Flarum\User\Command\EditUserHandler` allow the use of `avatarUrl` without restrictions.

**Comment by tobscure** [comment]
You're right, let's restrict this to admins.

**Comment by datitisev** [comment]
Is this closed by #1358?

**Comment by clarkwinkelmann** [comment]
No #1358 doesn't solve this (solves lack of permission check). But if you use assertAdmin in both cases then my fix in that PR is no longer needed.

**Comment by franzliedke** [comment]
Where do we even use this feature currently? It's not available through the frontend, as far as I can tell? It seems to be meant only for use with third-party authentication providers, right?

In this case, disallowing the passing-through of such an attribute from the API would be enough, right? The command handler should still accept it, so that the various auth controllers can "suggest" the attribute as received from the authentication providers (which could be assumed as trustworthy here).

**Comment by franzliedke** [comment]
Also see https://blog.christophetd.fr/bypassing-cloudflare-using-internet-wide-scan-data/ - this leak might not be the biggest problem after all ;)

**Comment by tobscure** [comment]
Relevant: #1359
If we allow authentication providers to store additional non-identifying attributes in their payload, then the command handler can read the avatar URL from that.

**Comment by franzliedke** [comment]
In any case, we will need (at least) a test case that proves that setting the `avatarUrl` attribute via API does no longer have any effect.

**Comment by CDK2020** [comment]
I like what @sijad proposed. Make the whitelist empty by default and allow extensions (specifically the SEO ones) and/or admins to add approved hosts
