### ISSUE TITLE
If I use phone to view the  * others like this, the title will move.

### ISSUE THREAD

**Issue by skywalker512** [flarum/core#1369]
## Explanation

If I use phone to view the  ```** others like this.``` the title will move.

![_ _20180214095650](https://user-images.githubusercontent.com/12960906/36184305-dfec2c08-116d-11e8-9112-a3c346c31471.gif)

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org

**Comment by TurboProgramming** [comment]
Isn't discuss pulling the latest commits from dev-master? Shouldn't it be the same?

**Comment by luceos** [comment]
@TurboProgramming discuss is occasionally being updated with dev-master, but this only happens when the calculated risk for problems will be close to zero. The current dev-master is still very volatile, the imminent merge of the database changes making it even more so. Discuss will be updated before beta 8 is tagged though.
