### ISSUE TITLE
SETUP: Installer should check directory/file ownership

### ISSUE THREAD

**Issue by siberian1967** [flarum/core#1389]
## When installing Flarum , the installer should check that the storage and assets directory owner matches the http server user.

Currently the installer is great about checking file perms (0775) but it does not check file ownership. This results in instructions that are incorrect (0775 on the wrong user won't fix the issue).

Its a minor detail but would enhance the user experience during setup.

This may be a feature request? Not sure. 

Flarum is awesome.

## Technical details

- Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 OpenSSL/1.0

**Comment by franzliedke** [comment]
Hey @siberian1967, thanks for the proposal. You are indeed on the right track, and this is something I would really like to improve. The thing is, it's pretty complicated, because there are many ways to set up permissions.

In any case, we already have an issue for this - so feel free to join in on the discussion in flarum/issue-archive#336.
