### ISSUE TITLE
Migrations as a mechanism to perform non-database upgrade tasks

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1446]
With #1445, migration callbacks are now given a schema builder and nothing else. This simplifies the interface but ties their hands in terms of performing non-database tasks.

The main use-case I can think of is using a Filesystem adapter to write some files (eg. into the `public` directory).

We need some kind of mechanism to run these tasks, and to me it makes good sense to put them in migrations, since migrations are supposed to be run each time a package is installed/upgraded.

---

In terms of what this would look like, the migration callbacks would need to be able to define their dependencies. I can think of a few options:

1. Re-introduce use of the Container's `call` method when calling these callbacks so that they can define their dependencies as their parameters
2. Just pass in a Container instance (less desirable)
3. Now that we require PHP 7.2, we could make migration files return an anonymous class like the example below, which would be instantiated by the container. However, I'm not sure if this is as nice as option 1 because it's less direct and the dependencies for the up/down methods may be different.

**Comment by rob006** [comment]
> With #1445, migration callbacks are now given a schema builder and nothing else. This simplifies the interface but ties their hands in terms of performing non-database tasks.

This actually may be a good thing. From my experience using migrations for different tasks usually ends up with maintenance hell. Migrations by design should not change - if I create migration today, it should work in the same way 5 years later. But 5 years later application may work completely different - may use different API, different components, and different file structure (only DB structure the same). So either I should constantly update and test my whole migration history, or I have non-working migrations because migration X requires component Y, which is no longer available.

**Comment by tobscure** [comment]
@rob006 That's a very good point, perhaps extensions being able to hook onto their own "installation" and "updated" events to run non-database tasks would be sufficient?

**Comment by rob006** [comment]
Yes, I would separate DB migrations from post installation/upgrade scripts. These are actually different tasks and should work in completely different way. 

I would also encourage people to not use components, models and helpers in migrations. For example in:

https://github.com/flarum/core/blob/3bf74eaf10135cf683440b56741937a4a2713613/migrations/2016_02_04_095452_add_slug_to_discussions.php#L23-L29

What if we remove `Str` helper or change how it works? Migration will stops working or will work in different way than before. This is usually undesirable because migrations should act in a deterministic way and always have the same result.

**Comment by franzliedke** [comment]
@rob006 Thanks for chiming in.

Yes, I always recommend to avoid referencing models in migrations, too. (I think we did ensure that a few months ago.) Other classes are always worth discussing. Utility classes from external dependencies are okay - you have to search for all their usages anyway when upgrading / changing those. The `Str` util is an interesting case. Again, for a refactoring one would have to search for usages etc. In this particular case, I can imagine some changes where we would not bother to do so. So yes, if it's easy, its implementation should probably be inlined.

**Comment by franzliedke** [comment]
So... do we agree that this issue (or a new one, given the potentially misleading discussion) should be about adding these events / hooks to extensions?

**Comment by tobscure** [comment]
Yes. #1463

I suppose we shouldn't be referencing SettingsRepositoryInterface and updating settings in migrations either then. We should be able to move that logic to these events.

**Comment by franzliedke** [comment]
@tobscure We [aren't](https://github.com/flarum/core/blob/07eda605615b20b7a9152b2eb1a78c735f8234e7/src/Database/Migration.php#L103-L105) using the interface in migrations. :grinning:
