### ISSUE TITLE
[Suspend] Display suspension to user

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1447]
At this time, it is unclear to a suspended user that they have been suspended. There is no indication to them why they cannot make new posts or replies, or perform functions they could before. 

Create a banner or indication to suspended users that they are suspended, and also the duration if not indefinite. 

Related to #1287

**Comment by Ralkage** [comment]
I would suggest a few things with this actually, with regards to the suspension system and all:

Within the scope of this discussion:
- Add a notice just above the hero (for now, or will these improvements be for beta 8 of then suspend extension?) stating that the user has been banned because of [insert said reason here] followed by the length of their ban.

Out of the scope of this discussion:
- Remove visibility of discussion lists, access to the API, search bar, etc.

Though a typical user punishment/banning system allows a "banned/suspension" group to be assigned to assert permissions per groups.

**Comment by jordanjay29** [comment]
> Out of the scope of this discussion:
>>Remove visibility of discussion lists, access to the API, search bar, etc.  
>
>Though a typical user punishment/banning system allows a "banned/suspension" group to be assigned to assert permissions per groups per say.

That's discussed in flarum/framework#1419

**Comment by datitisev** [comment]
My PR flarum/flarum-ext-suspend#11 was merged, which adds notifications that tell the user they have been suspended and unsuspended. However, I agree a message like the confirm email address would be good too.

**Comment by jordanjay29** [comment]
Thanks. I thought your PR was an issue, so when I couldn't find it in here I assumed I had been dreaming.

I'll close this unless a dev wants to reopen for the email issue.

**Comment by SychO9** [comment]
Implemented in flarum/suspend#41
