### ISSUE TITLE
Sticky sidebar overlaps header when swiping past page top

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1495]
## Bug Report

**Current Behavior**
After scrolling a lot to the top (where the discussion already finished) the UI elements start getting into themselves, giving the forum a bad look.

**Steps to Reproduce**
1. Go to a topic
2. Scroll up
3. See error

**Expected Behavior**
The UI elements should stay where they need to be, giving a look to the user that the page is only scrolling to the top like other websites.

**Screenshots**
Video: https://youtu.be/XwJdiQpsw9I

**Environment**
Flarum Community
https://discuss.flarum.org

**Note: Keep in mind that this is a mobile-only issue.**

**Comment by franzliedke** [comment]
It could be fixed with CSS' `position: sticky` instead of the current `fixed` value, but that [isn't supported widely enough yet](https://caniuse.com/#feat=css-sticky) IMO. (Then again, using `position: fixed; position: sticky` should be forward-compatible so that only old browsers get the current behavior?

As an alternative, `position: sticky` can be replicated with a bit of JavaScript (meh).

**Comment by TurboProgramming** [comment]
The only solution here looks like what you said, get `position: sticky` to forward-compatible browsers and let the old ones use `position: fixed`. 

Lot's of users are using updated browsers these days, so it won't be a huge deal. But still, we have some people with the old ones.

But as I see from the link you sent, lot's of browsers support it, yes, not all of them but it would be enough for most users.

Also, let's not forget that this issue is not visible if someone is testing Flarum, no one will continue scrolling to the top if they know the article finishes there.

**Comment by askvortsov1** [comment]
I am unable to replicate this with modern flarum, could anyone confirm?

**Comment by ardacebi** [comment]
I'm no longer able to replicate this as well.

**Comment by askvortsov1** [comment]
Thanks! Closing for now, feel free to comment if anyone can replicate.
