### ISSUE TITLE
Marking notifications as read without visiting the discussion

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#151]
Sometimes I just want to approve that I've seen a notification without actually visiting the referenced post. e.g. when Toby goes on a liking spree ;)

Could we have a button next to each notification (or each group, not sure) similar to the one that marks all notifications as read?

**Comment by tobscure** [comment]
Good idea :)

**Comment by tobscure** [comment]
Also I need to fix the way the all notifications are marked as read - currently it makes an individual request for each one

**Comment by tobscure** [comment]
What needs to be done:

* Add a Button with a check icon to each notification list item in the NotificationList component.
* Style this button to float right, only show on hover, and be a bit smaller than normal.
* Mark the notification as read when this button is clicked, and call e.stopPropagation() so that the notifications dropdown does not close.
* Integrate the `slidable` util, so that notifications can be marked as read by swiping them to the right, using DiscussionListItem as an example.

**Comment by alexbagirov** [comment]
Also if I have a notification for a specific post and visit it manually, then that notification won't be marked as read.

**Comment by tobyzerner** [comment]
@alexbagirov see flarum/issue-archive#442 for that
