### ISSUE TITLE
PHP Extender: Frontend

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1601]
We need a `Frontend` extender that allows *extending* (read: inheriting) a "frontend" (group of routes, middleware and assets such as the forum). This is needed for reviving the embed extension.

More thoughts and discussion starting at https://github.com/flarum/core/issues/851#issuecomment-407207717

**Comment by tobscure** [comment]
I don't think this should block beta 8, can't the embed extension can still function using the Compat extender?

**Comment by franzliedke** [comment]
Possibly. That would need to be done as well, though - it might be easier to finish the extender instead. Still torn on the best way forward, I have some WIP code lying around

**Comment by tobscure** [comment]
Closed in edaca3160ed856ef2b42d043c8276c33dc8ea6cd

**Comment by datitisev** [comment]
I think this broke something. `Flarum\Extend\Frontend@content` doesn't seem to be working anymore, I have the following code trying to make flarum/statistics work again, and `app.data.hello` is undefined
![image](https://user-images.githubusercontent.com/6401250/48905907-c83bc000-ee30-11e8-91af-80e024ce0183.png)

I also have a bunch of logs in the callbacks (not included in the screenshot) and none of them show up in the corresponding log file.
Throwing an exception does nothing too.

**Comment by franzliedke** [comment]
In the first `content` call, the listener class is probably implementing the `ContentInterface`, which has been removed.

**Comment by datitisev** [comment]
@franzliedke Actually, it's not.

I think I see the reason why.

- In `Extend\Frontend@registerContent`, when the container is resolving `flarum.$this->frontend.frontend`, one of the argument is `Flarum\Extend\Frontend` instead of `Flarum\Frontend\Frontend`.

- It also seems like the container never resolves, I put an extension inside the callable and it does not throw... only exceptions before resolving the container throw.

  https://github.com/flarum/core/blob/master/src/Extend/Frontend.php#L143

  ![image](https://user-images.githubusercontent.com/6401250/48906168-a989f900-ee31-11e8-830a-2d19b92c4e04.png)
  _first `throw` actually errors with `$content` not being defined, but still shows that the code is 
  being executed_
