### ISSUE TITLE
b8 behavior to suppress initial errors during boot

### ISSUE THREAD

**Issue by luceos** [flarum/core#1607]
## Bug Report

**Current Behavior**

In case you have an extend, with an incorrect return value (in my case an empty file 🤷‍♂️), the error produced is something like this (from memory, but easy to reproduce with an extend.php in the root) "error on boot, reference in Arr class". This is caused by:

https://github.com/flarum/core/blob/5a9b47cdf719a7bb6e208d95a3e116b7f235ee48/src/Foundation/Site.php#L72

There are two issues here:

- assuming the included file returns an array
- erroring only with the message of the exception and no trace whatsoever to find the cause, not even with debug on..

**Steps to Reproduce**
1. Install Flarum
2. Create `extend.php` in your flarum root path.
3. Open forum

**Expected Behavior**

No error, or a better error with debug enabled.

**Environment**
- Flarum version: dev-master

**Comment by franzliedke** [comment]
Ideas from today's meeting:
- Show at least the first line of the stack trace (add file + line to the error message)
- Attempt to log the error (tricky because we haven't fully booted)
- Show the full stack trace, but handle sensitive (i.e. database) exceptions separately

**Comment by franzliedke** [comment]
I've taken care of showing the exception message, class, file and line. Showing the full stack trace feels a bit too dangerous to me.

@flarum/core Is this enough for now?

**Comment by franzliedke** [comment]
I've also fixed the underlying error about extend.php not returning an array. Really, the "boot error" should never be seen in production, so if you ever encounter one, it should be reported and fixed / prevented.

---

That said, I noticed we're only handling errors thrown when booting the app, but not around the `RequestHandlerRunner`:

https://github.com/flarum/core/blob/689d767f828c80c583135a56c9d334767908d0b5/src/Http/Server.php#L36-L46

And that's actually where the error originally reported by @luceos would be thrown with the current code. So maybe that code should be wrapped by the try/catch as well? The term "boot error" would then not be correct anymore.

**Comment by luceos** [comment]
If possible with an easy test, can we cover this scenario? I count on this happening often.

**Comment by franzliedke** [comment]
Found an easy way to catch a few more errors. Everything else that's not handled by a `try`/`catch` block is either inside our middleware stack (where we have another layer of error handling) or pretty much only code from Zend Diactoros/Stratigility, so we should be fine here.

@luceos The original error that triggered the discussion around improving early error handling ("extend.php with an incorrect return value") has also been fixed. Basically, every time a user sees the "Flarum encountered a boot error", either they did dramatic errors in their PHP code (extend.php), or something needs to be fixed in Flarum.
