### ISSUE TITLE
Why don't use laravel/socialite instead of thephpleague/oauth2-facebook

### ISSUE THREAD

**Issue by gagarine** [flarum/core#1612]
Why you are not using https://github.com/laravel/socialite instead of https://github.com/thephpleague/oauth2-client ?

I'm asking this question mainly because of bug https://github.com/thephpleague/oauth2-facebook/issues/39 .

**Comment by luceos** [comment]
The problem here is not the package that is being used, but keeping up to date with them. We've taken care of this problem in beta 8. Future patches to our core extensions will be made sooner to prevent this from happening.

And please next time don't post these kind of questions on the issue tracker, the tracker is meant for amongst others bug reports as clearly explained in the issue template.
