### ISSUE TITLE
3 dots menu for last extension in column is moved to next column when clicked

### ISSUE THREAD

**Issue by KyrneDev** [flarum/core#1685]
**Current Behavior**
3 dots menu for last extension in column is moved to next column when clicked.

**Steps to Reproduce**
1. Go to extensions page
2. Click 3 dots menu on extensions in last column

**Expected Behavior**
Should be below the extensions that was clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/13856015/49623225-a1799f80-f981-11e8-9c3c-b8abf2e636e6.png)

**Environment**
- Flarum version: dev-master
- Webserver: apache
- Hosting environment: XAMPP local
- PHP version:7.2
- Browser: Chrome 70

**Comment by clarkwinkelmann** [comment]
I had a look at reproducing this. It appears to be a Chrome-only issue. I tested with Chrome 74. On Firefox 66 everything was looking good. The issue is present in beta 8 as well as dev-master.

The issue seems linked to the `columns` feature that is used for the extension list.

I noticed something interesting. If you have enough items to have 2+ columns and scrolling, the column break does not happen at the same place everytime. When scrolled up the dropdown breaks above the first button, but if scrolled to the bottom of the page, the dropdown breaks after the button.

![image](https://user-images.githubusercontent.com/5264300/57130461-d1df3180-6d99-11e9-9b8f-f3ca7c59da0f.png)
![image](https://user-images.githubusercontent.com/5264300/57130478-e28fa780-6d99-11e9-8fdb-ff952ebef9a1.png)

**Comment by towuk118** [comment]
> I had a look at reproducing this. It appears to be a Chrome-only issue. I tested with Chrome 74. On Firefox 66 everything was looking good. The issue is present in beta 8 as well as dev-master.
> 
> The issue seems linked to the `columns` feature that is used for the extension list.
> 
> I noticed something interesting. If you have enough items to have 2+ columns and scrolling, the column break does not happen at the same place everytime. When scrolled up the dropdown breaks above the first button, but if scrolled to the bottom of the page, the dropdown breaks after the button.
> 
> ![image](https://user-images.githubusercontent.com/5264300/57130461-d1df3180-6d99-11e9-9b8f-f3ca7c59da0f.png)
> ![image](https://user-images.githubusercontent.com/5264300/57130478-e28fa780-6d99-11e9-8fdb-ff952ebef9a1.png)

MS Edge have this problem too!
![image](https://user-images.githubusercontent.com/28830162/83352534-c4a5c500-a354-11ea-8d8c-20dada98f9b2.png)

**Comment by tolgaaaltas** [comment]
> MS Edge have this problem too!

Which one? Spartan (Edge-HTML) or Chromium?

**Comment by askvortsov1** [comment]
No longer applicable as of #2409
