### ISSUE TITLE
Visually distinguish posts that you authored

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#169]
Somehow

**Comment by rodrigoargumedo** [comment]
Are you saying like **Rodrigo Argumedo (you)** _authored_ this post x hours ago? I'm not sure if I am understanding this correctly. But that would be great.

**Comment by tobscure** [comment]
Like how your comments in a GitHub issues are highlighted blue

**Comment by rodrigoargumedo** [comment]
Ooh, yeah. That makes sense. You could possibly do:

```
if current.user are signed in?
HTTP POST comment.id with user.id
else
enter their comment again.
```

I think this can be achieved by styling it with some .css class or something. I dunno, that's my two cents.

**Comment by jberlyn** [comment]
I'd just go with a slightly grey CSS class for your own comments. It's not overly obtrusive but distinguishable enough that you know by scrolling through.

**Comment by tobscure** [comment]
What needs to be done:

* Add a class `.Post--self` to the Post component if the author === app.session.user.
* While we're here, we should add classes to the Post component based on the author's groups. e.g. `.Post--group4`. And the same for the username helper (`.username--group4`)
* Experiment with styles for `.Post--self`. Personally I think a background color will not work, because post content should really be displayed on a consistent background... but we could try a border/glow around the whole post, or just around the avatar, or a background on the header, or whatever else.

**Comment by tankerkiller125** [comment]
I've tried adding a border around the post to distinguish it as such:
![image](https://user-images.githubusercontent.com/3457368/68065014-8e8a5f00-fcf9-11e9-8729-b2f15d758fd8.png)

Let me know what you think/what refinements you'd like to see.

**Comment by luceos** [comment]
Class already added. Closing.
