### ISSUE TITLE
Delete Forever? I don’t think so says beta 8.

### ISSUE THREAD

**Issue by zerosonesfun** [flarum/core#1717]
In the main list deleting posts forever works fine. But, on the post’s permalink page, after selecting delete forever, an “oops” error occurs. 

<img src="https://i.ibb.co/ZBGhNBt/70191-E8-C-E2-F7-4-F92-8014-5484644-D0-D37.jpg" alt="70191-E8-C-E2-F7-4-F92-8014-5484644-D0-D37" border="0">

**Comment by Ralkage** [comment]
@datitisev I can reproduce using the Beta 8 release (not dev-master) BUT, my suspicion that this was brought on by an extension rather than a core issue.

As seen in his screenshot, he's using Gamification and I was able to reproduce this error with Gamification enabled.

Give it a try with Gamification installed and enabled.

**Comment by zerosonesfun** [comment]
I’ll close this issue then since it has to do with an extension. I can confirm that disabling gamification solves the issue.
