### ISSUE TITLE
Mail: Handle incomplete email configuration

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1763]
**Continues #1169**

- [x] Show a warning message when a driver is selected but not fully configured (i.e. missing values for required fields).
- [x] Fall back to a `NullDriver` that does not send any mails when that is the case.

This needs an extension to the `DriverInterface` - something along the lines of `getRequiredFields()` or, more flexibly, `isFullyConfigured($settings)`.

**Open question:**
Do we want to allow selecting the "log" driver explicitly? What's the value in that?

**Comment by luceos** [comment]
What if we enabled the log driver only when debug is on? I can't see why the log driver would be useful in production environment really..

**Comment by franzliedke** [comment]
> What if we allow the log driver only when debug is on? 

Do you mean allow selecting it in the dropdown? Or enable automatically when logging in?

I almost tend towards never listing it in the dropdown, and simply using it automatically when settings are not complete for any of the other drivers.

**Comment by tobscure** [comment]
I don't think we should fall back to the log driver automatically, because if someone hasn't configured their mail settings correctly it doesn't necessarily mean they want emails to go to a log file. If a driver isn't configured correctly, just don't send mail.

I think we should allow selecting the log driver explicitly in any environment to keep things simple.

**Comment by franzliedke** [comment]
Fair enough. I've updated the issue and TODO list accordingly.
