### ISSUE TITLE
[tags] Sortable is not a function in admin tags grid

### ISSUE THREAD

**Issue by luceos** [flarum/core#1786]
## Bug Report

This happens when trying to re-order tags on discuss admin area, latest core.

![image](https://user-images.githubusercontent.com/504687/58278411-43f4d600-7d9c-11e9-8e4c-c16c748f95ef.png)

**Comment by luceos** [comment]
I cannot reproduce this locally. So I tried recompiling this on discuss, but that didn't help.

**Comment by taddis** [comment]
I can confirm that this error appears when running with flarum/tag master.

This bug was introduced here [Update JS dependencies to fix vulnerable packages](https://github.com/flarum/tags/commit/c80cbe8ae7063d1c18784e983e9789554dbe4e03) when upgrading html5sortable 0.2.0 -> 0.9.8.

I can try and dig deeper to figure out why.

**Comment by datitisev** [comment]
https://github.com/lukasoppermann/html5sortable/commit/40a138798fd43d571e89348be9a9c3993486c940

jQuery was removed in v0.4.5, it now uses vanilla JS.

**Comment by matteocontrini** [comment]
It's probably because jQuery support has been removed, [3 years ago](https://github.com/lukasoppermann/html5sortable/releases/tag/v0.4.0).

**Comment by taddis** [comment]
Anyone working on a fix or is this something I can take on? If the latter, should html5sortable still be used or is there another/better solution?

**Comment by datitisev** [comment]
Most likely than not, html5sortable can still be used. I'll look into it later today if I have the time to see if I can make it work.
