### ISSUE TITLE
Discussion title

### ISSUE THREAD

**Issue by kamildei** [flarum/core#179]
https://vid.me/SUgR

Safari 8.0.7 (10600.7.12) OS X Yosemite 10.10.4 + uBlock 0.9.50

**Comment by DCSJAPAN** [comment]
This appears to be the same as the issue I filed.

https://github.com/flarum/core/issues/161

**Comment by tobscure** [comment]
@DCSJAPAN hmm, can you think of any way to discourage people from typing a title in the tag selection box? Otherwise will probably just go with your second suggestion.

**Comment by DCSJAPAN** [comment]
Is there a way to display selected tags in the header of the dialog box *without* using an editable field?

If not, the only thing I can think of would be to format the dialog as a list of tags with checkboxes next to them ... which I admit wouldn't be nearly as slick as the current way of doing it.

**Comment by tobscure** [comment]
Well, we want to allow the user to type so that they can filter the tags to find the one that they're looking for. On a forum with lots of tags, this will be essential. There's also the possibility of a user-created tags feature in the future.

What about either:

- Always having placeholder text in the input which says "Add another tag" or something
- Changing the title of the dialog from "Start a Discussion About..." to "Choose Tags for Your Discussion"

**Comment by DCSJAPAN** [comment]
Yes, I can see why you wouldn't want to get rid of the text box (which is what both my suggestions amount to). In fact, I was wondering if users would be able to type in their own tags there...

I actually like how the "choose one or more..." text disappears when you select the first tag; it might be difficult to leave that there without it looking clunky.

So I'd vote for the second option. "Start a Discussion About..." could also be read as though it's asking the user to enter a title, so making it more specific should help eliminate the confusion.

**Comment by tobscure** [comment]
Alright, will make that change.
