### ISSUE TITLE
Review/deprecate global helpers functions

### ISSUE THREAD

**Issue by luceos** [flarum/core#1796]
We need to prevent the use of helpers. The core still has a helpers set at `src\helpers.php` we should consider which of these should remain or whether we should deprecate them all.

**Comment by clarkwinkelmann** [comment]
Just to be clear, this issue is about PHP helpers ? Not javascript ?

**Comment by franzliedke** [comment]
Yep, only about PHP.

**Comment by askvortsov1** [comment]
I would say the event one should go, since we want events as private API (if at all). I'd also say app gives extensions waaayyyyy too much access into the container, and should be removed. I think the path ones are alright (unless there's a better place to get that information, in which case I'd say we remove them too?

**Comment by datitisev** [comment]
@askvortsov1 Extensions must sometimes be able to fire their own events & Flarum events to work properly though

Also - this isn't the place to discuss private vs public API, though I think in the past we've said that private API would be discouraged to use but still available for very specific things an extension may not be able to do with the public one (public API will never account for all the functionality extensions will need).

**Comment by luceos** [comment]
If we keep the app Helper that should open up our code sufficiently for developers to hook into the deeper workings. Everything else, could or should, potentially be droppable.

**Comment by clarkwinkelmann** [comment]
I'd say it's all a question of convenience. Just like in Laravel, most of the stuff is just there to make the developer life easier, and sometimes make the core more readable.

I'm actually using every helper function we have left in one extension or another. I know I could also use `app()` and go from there, but those functions are quicker to write and more readable.

The `_path` methods seems like the less useful, because it doesn't add much to the `app()->somethingPath()` that already exists.

`app()` and `event()` I would keep. It's also probably more convenient to users that come from Laravel and expect those methods to exist.

**Comment by askvortsov1** [comment]
Couldnt app be injected into any part of any extension? At least thats the approach I've been taking.

**Comment by clarkwinkelmann** [comment]
Constructor injection is not always the best option. You might want to resolve a class as late as possible, either for performance or simply to let other extensions act before yours.

For example, I only resolve the SettingsRepositoryInterface after I checked the user is allowed to see the settings. Or I only resolve the logger once an exception has been triggered. The `app()` function is extremely useful for that.

I don't see any disadvantage of keeping those functions. As long as we keep a single one, the `helpers.php` file will be loaded anyway, so removing half of the functions will not reduce the number of files loaded by the autoload either.

**Comment by franzliedke** [comment]
Generally, I view using `app()` as an anti-pattern. Definitely so if used in core code. It hides dependencies and encourages using more (hidden) collaborators in classes, which is usually a sign that a class is doing too much.

Of course, it's dangerous to judge so broadly and we need to find the best solution on a case-to-case basis.

I definitely want to have a shot at not using the helpers in core code - if this is possible (and I think it is), then we can discuss whether to keep (some of) them for extensions.

**Comment by franzliedke** [comment]
> I would say the event one should go, since we want events as private API (if at all).

That's only half true. Events are fine when we use them to model *real events* (something that happened in our business domain - e.g. a reply was posted).

In the past, we abused the event concept for extensibility, though, because we did not yet have better mechanisms - `ConfigureMiddleware` would be an example that comes to mind. I say "abuse" and "better" because while the mechanism worked well, it also felt awkward and like a mismatch when using it, at least IMHO.

**Comment by askvortsov1** [comment]
As much as I don't like it and prefer dependency injection wherever possible, I think `app` has to stay (but be strongly discouraged), because dependency injection isn't always possible. We might want to consider renaming it to `container` so it more accurately reflects what it represents (this also applies to the same-named property of service providers).

I see no reason to keep `event` around, since an event dispatcher instance can be easily injected or instantiated via `app` (or `container` if we rename it). I think we should deprecate it.

The rest are already gone.

**Comment by clarkwinkelmann** [comment]
My concern with removing those last few helper methods is consistency across extensions.

My primary use case for those helper methods is when using libraries that were designed for Laravel which expect those methods to exist.

If we removed the methods from Flarum, this means I will have to define them myself in my extension.

And now if two extensions need to do the same, we have competing declarations of functions, and assuming everyone used conditional declaration properly, only the first one will remain.

If the two extensions declared those methods slightly differently, this will lead to extension conflicts through those basic helper methods.

That's why I am against removing those methods. I'm all for recommending against, but I think `app()` should definitely remain (as an alias to `container()`) because it's an important method in the Laravel ecosystem and I'd like extension to be able to reliably rely on how it works without having to worry about other extensions defining it first.

Similarly, I'd very much prefer `event()` and all the `_path()` methods to stay because they make Laravel library integration much easier.

**Comment by askvortsov1** [comment]
As much as I don't like this design pattern, this is a compelling reason to keep these around. I also looked at the Laravel source, and their `app` helper does in fact return a `Container` instance, so renaming that is probably unnecessary.

How frequently do Laravel libraries use these under the surface? And when they do, are there others not defined here that you need to manually define?

If we decide to keep them fully (and restore the path ones), I'd be in favor of perpetually deprecating them so they will show up crossed out in IDEs?

**Comment by clarkwinkelmann** [comment]
Well-designed libraries usually have a non-Laravel version, and then a Laravel version. Those usually don't rely on "magic" methods like these. It's the few packages made specifically for Laravel that cause issues. I don't know if there are that many.

The one I dealt with so far is https://github.com/Maatwebsite/Laravel-Excel . I'm not sure of the full list of methods they use, but there's definitely `app()`, `collect()` (this one comes directly from illuminate helpers) and `config()`. Though `config()` is a special one since it never existed in Flarum, so I had to implement my own.

Even if we had `config()` directly matching with `SettingsRepositoryInterface::get`, it probably wouldn't help since Laravel has a different settings hierarchy from Flarum, so we can probably ignore that one.

**Comment by SychO9** [comment]
Clark makes a good point, in fact I had to deal with that while updating clockwork (https://github.com/FriendsOfFlarum/clockwork/pull/6)

**Comment by clarkwinkelmann** [comment]
Or maybe we could have some sort of a `flarum/laravel-layer` package that inserts common helper methods found in Laravel? That way it's not part of the official extension API, but extensions that need it can rely on the method implementation in case they need it?

I still think `app()`/`container()` should be part of core in any case.

**Comment by askvortsov1** [comment]
I prefer for packages whose purpose is to be used by extensions to be core / core-affiliated (e.g. how we're planning to merge fof/console functionality into core). I think a `flarum/laravel-helpers` package would be an excellent solution here. Then we could proceed with renaming `app` to `container`: it's more accurate, and draws a line between `container` (which should be used when dependency injection is impossible) and the Laravel helpers (which should only be consumed by external, Laravel-based packages)

**Comment by askvortsov1** [comment]
In that case, why don't we do the following:

- The `app` and `event` helpers are deprecated, as done in the linked PRs
- We publish a new `flarum/laravel-helpers` package that just copies `app`, `event`, and the `path` helpers (can always add more if necessary)
-

**Comment by clarkwinkelmann** [comment]
That sounds good to me.

That would be our first composer package that isn't an extension or core/skeleton I think? We will still use the same kind of dependency on core as extension I suppose. We probably won't have to update it often if it's just pulling things out of the container through methods.

We'll need to document it somehow, though its README or with a dedicated docs page?

**Comment by luceos** [comment]
ps not sure whether `container` was still under consideration, but Laravel uses `resolve()` in addition to `app()`. I'd be in favor of that.

**Comment by askvortsov1** [comment]
`resolve` doesn't allow passing in a null `abstract` to get an instance of the container, but that might be even better, since other container stuff (bindings, mainly) should be done in service providers. Also preferably to stick to Laravel convention for these since they originate in Laravel. 

@clarkwinkelmann I think you're the best versed in usage of these helpers; is there any legitimate use case for getting a container instance, not just resolving, outside of service service providers? If not, I'll update my PR.

**Comment by clarkwinkelmann** [comment]
The most important use case I can think of for `app()` without any argument is the `app()->bound()` check. I don't think that one can be done with `resolve()`. But I've only used it very rarely.

There's also the (in my opinion) even less used `tagged`, `call`, `resolved` and `makeWith` which might be called outside of a service provider. But since it's rare, I don't think it's unreasonable to first resolve the container (even potentially from `resolve()`) before calling those.

Otherwise I'm all for `resolve` over `container`.

**Comment by clarkwinkelmann** [comment]
Addition to the previous message? Isn't the app or container bound as the string `app` or `container` ? In such case you'd just need to do something like `resolve('app')->bound()` if you needed.
