### ISSUE TITLE
Modal is not showing

### ISSUE THREAD

**Issue by luceos** [flarum/core#1813]
## Bug Report

**Current Behavior**

Whenever you open the edit tags modal, it hides itself. This is caused by the missing class `in`. This makes editing tags a pain.

**Steps to Reproduce**
1. Go to discuss.flarum.org, open a discussion
2. Click on edit tags
3. Modal hides

The behavior is sporadic, but just now it happened to me constantly on discuss using firefox.

**Comment by luceos** [comment]
Happened to me again, marked all notifications as read. Refreshed page, nothing.

Can someone try to reproduce on firefox: https://discuss.flarum.org/d/21396-solved-twitter-login-shows-the-page-you-requested-could-not-be-found/16

**Comment by VanillaScent** [comment]
Can confirm luceos, I am using the keyboard shortcut extension as you saw and the modal is not showing either.
I seem to be using firefox too. Using any crhome variant it does work.
So this seems to be a firefox related issue.

note: I didn't reproduce on twitter login, but on kvothe/keyboard-shortcuts which is a fork by kvothe.

**Comment by luceos** [comment]
@vanillascent does it happen without the keyboard shortcuts extension as well? We don't have that one on discuss. If so, please post your flarum info output.

**Comment by VanillaScent** [comment]
No only seems to happen with keyboard shortcuts. I haven't seen this issue in editing tags on firefox. The tags modal has showed up fine for me since the start. it does seem to be the same issue though as the modal from keyboard shortcuts doesnt show up in firefox.

**Comment by GameBurrow** [comment]
As I posted here: https://discuss.flarum.org/d/21503-tags-edit-overlay-opens-and-immediately-dissapears

I have this issue with one of the chromium based browsers **Vivaldi** 2.7.1628.33 (Stable channel) (64-bit).

I didn't have this issue with the same browser in August, I've updated flarum and replaced deprected extensions in the time between. It happens both on discuss.flarum.org and on my own flarum installation.

**Comment by datitisev** [comment]
Looks like this was reported last year, see #1504. 🤔

**Comment by GameBurrow** [comment]
For me, this issue is new. Last time I actually tried this function (flarum was in beta.9 then) and then I didn't have the issue.

**Comment by taciturasa** [comment]
Currently having this issue still on my forum. Using Firefox as well. Here is a gif.

https://cdn.discordapp.com/attachments/369174406909394944/637787236749934623/whyisthishappening.gif

**Comment by matteocontrini** [comment]
It started to happen to me as well, with Firefox and only on one discussion for some reason 🤔

**Comment by tiuram0n** [comment]
I am also having problems with Google chrome.

Version: 78.0.3904.87
SO: Windows 10 OS Version 1903

**Comment by luceos** [comment]
People involved, also mention whether you use an adblocker and virus software.

**Comment by matteocontrini** [comment]
I use Firefox 70 built-in tracking protection, but no ad blocking (I have AdGuard for Firefox in opt-in mode, but it's not enabled on my forum).

**Comment by luceos** [comment]
I also use AdGuard and it is enabled for me on discuss.

**Comment by matteocontrini** [comment]
@luceos this has just happened to me again and I tried disabling both Firefox's tracking protection and the AdGuard extension, but the problem is still there, so it's probably unrelated

**Comment by the-turk** [comment]
This issue is driving me crazy for days but damn, i think i found the problem.

So we have `<div class="ModalManager modal fade"></div>` lies on the source code by default. When we open a modal, it adds a new class called `in`: `<div class="ModalManager modal fade in"></div>`. This class is using for fade effect & sets `opacity: 1;` for `div.ModalManager`

https://github.com/flarum/core/blob/c23af9550efbaa0fe1058c5b0568d3175edf9403/less/common/scaffolding.less#L115-L121

However, the Tags extension uses `redraw()` function as soon as the modal pops up:

https://github.com/flarum/tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/js/src/forum/components/TagDiscussionModal.js#L277

This removes the `in` class and causes the `div.ModalManager` element to return its inital position. Furthermore, not just the _Tags extension_ but the _core_ itself has this issue. People who encounters with this issue may see that the same thing happens if they enable an extension which has settings modal (it'll try to show the extension's settings modal after enabling it but it'll fail eventually).

What we need to do is redrawing the **Modal** component-only instead of the **ModalManager** component but eventhough there are some workarounds for component redrawing (see https://github.com/MithrilJS/mithril.js/issues/2388), i couldn't find any elegant ways to do it in _Mithril_.

**Comment by the-turk** [comment]
So we have `<div class="ModalManager modal fade"></div>` lies on the source code by default. When we open a modal, it adds a new class called `in`: `<div class="ModalManager modal fade in"></div>`. This class is using for fade effect & sets `opacity: 1;` for `div.ModalManager`

https://github.com/flarum/core/blob/c23af9550efbaa0fe1058c5b0568d3175edf9403/less/common/scaffolding.less#L115-L121

However, the Tags extension uses `redraw()` function as soon as the modal pops up:

https://github.com/flarum/tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/js/src/forum/components/TagDiscussionModal.js#L277

This removes the `in` class and causes the `div.ModalManager` element to return its inital position. Furthermore, not just the _Tags extension_ but the _core_ itself has this issue. People who encounters with this issue may see that the same thing happens if they enable an extension which has settings modal (it'll try to show the extension's settings modal after enabling it but it'll fail eventually).

What we need to do is redrawing the **Modal** component-only instead of the **ModalManager** component but eventhough there are some workarounds for component redrawing (see https://github.com/MithrilJS/mithril.js/issues/2388), i couldn't find any elegant ways to do it in _Mithril_. We also could find different ways to apply fade effect or manually add `in` class to `div.ModalManager` element after `redraw()` function.
