### ISSUE TITLE
Extensions unable to change default route controller

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1819]
This is an unintended side effect introduced in https://github.com/flarum/core/commit/e4514d84131a82785157dd15550ba2278a5cc154.

By not populating the routes _after_ resolving, this means the default route is resolved before any extensions are able to add routes to the route collection.

Neither `api` nor `admin` need the same fix as they do not have customizable/backend default routes.

I found the bug after trying to find out why fof/tags suddently stopped passing the correct API document, and discovered that it was not using my custom `Content` class and instead passing an array of discussions to the page.

**Comment by clarkwinkelmann** [comment]
For future reference, this issue also affected our own Tags extension.

Reported and investigated here https://discuss.flarum.org/d/20960-home-page-selection-inconsistent/6

The issue caused Flarum to always pre-load the discussion list, even when Tags was set as the homepage.

Then, when clicking any link that was supposed to filter the discussion list from the Tags page (clicking a tag, or "following", or similar links), the initial load of the discussion list would use that pre-loaded data and ignore the filter, causing all discussions to show without regard to the current selected tag.

The issue was reproduced on the beta test site.

The issue was confirmed solved on the nightly test site.
