### ISSUE TITLE
Deleted posts are visible to all visitors

### ISSUE THREAD

**Issue by ajvdeutekom** [flarum/core#1827]
Deleted posts are visible to all visitors. 

The issue can be reproduced by disabling the Tags Extension. Writing a post, delete it and logout. The deleted post is collapsed and Grayed out, but can still be opened. 

- Flarum version: Flarum core 0.1.0-beta.9

Requires fix in the PostPolicy
https://github.com/flarum/core/blob/master/src/Post/PostPolicy.php

**Comment by luceos** [comment]
Confirmed on beta.flarum.site

**Comment by clarkwinkelmann** [comment]
I have identified the issue being with the nested where here https://github.com/flarum/core/blob/06cd062a1b8f63bc71ba1202c794f342e2a15269/src/Post/PostPolicy.php#L101

If no listener adds any query to the nested where, the builder acts like the only `where` is the one to join the table, so the query always `select 1`.

I can reproduce on beta 8 as well, so it doesn't look like something caused by the Laravel update.

**Comment by luceos** [comment]
@clarkwinkelmann sounds about right and funny this was never identified.

Solving this issue requires a test.
