### ISSUE TITLE
Loading speed optimization "from the box"

### ISSUE THREAD

**Issue by safead** [flarum/core#1866]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Can you please integrate all google suggestions in the engine "from the box"?  All suggestions are described here in detail: https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&url=https%3A%2F%2Fdiscuss.flarum.org&tab=mobile&hl=en

**Describe the solution you'd like**
- Preload key requests
- Remove unused CSS
- Serve images in next-gen formats
- Ensure text remains visible during webfont load
- Minimize main-thread work 
- Reduce JavaScript execution time
- Minimize Critical Requests Depth

**Comment by tankerkiller125** [comment]
The Unused CSS on one page might be used on another page. This makes it very difficult to remove the unused CSS without breaking things. Serving images in the next-gen formats should not be something you expect flarum to do. You should do that via an image proxy or some form of extension. I feel like image manipulation would be out of scope for the core.

I can see pre-loading being implemented but honestly that about it. No dynamic website ever gets a perfect score from the google pagespeed insight system because it's extremely difficult. It's one thing when a site is static but on dynamic sites (especially ones that use a lot of JS like flarum) will never get a perfect score.
