### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by WelaurS** [flarum/core#1920]
## Bug Report

**Current Behavior**
If an error occurred while trying to register, the user is created despite the error

**Steps to Reproduce**
1. Install forum, but don't setup mail settings.
2. Try to register user
3. You will got error: https://i.imgur.com/Gi19irD.jpg

**Expected Behavior**
If the error occurred the user account won't created.

**Environment**
- Flarum version: 0.1.0-beta
- Website URL: -
- Webserver: nginx
- Hosting environment: VPS
- PHP version: PHP 7.2.19-0ubuntu0.18.04.2
- Browser: Chrome 78.0.3904.70
--

```
Flarum core 0.1.0-beta.10
PHP version: 7.2.19-0ubuntu0.18.04.2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+----------------------+----------------+--------+
| Flarum Extensions    |                |        |
+----------------------+----------------+--------+
| ID                   | Version        | Commit |
+----------------------+----------------+--------+
| flarum-approval      | v0.1.0-beta.8  |        |
| flarum-bbcode        | v0.1.0-beta.8  |        |
| flarum-emoji         | v0.1.0-beta.10 |        |
| flarum-lang-english  | v0.1.0-beta.10 |        |
| flarum-flags         | v0.1.0-beta.9  |        |
| flarum-likes         | v0.1.0-beta.9  |        |
| flarum-lock          | v0.1.0-beta.9  |        |
| flarum-markdown      | v0.1.0-beta.10 |        |
| flarum-mentions      | v0.1.0-beta.10 |        |
| flarum-statistics    | v0.1.0-beta.9  |        |
| flarum-sticky        | v0.1.0-beta.9  |        |
| flarum-subscriptions | v0.1.0-beta.9  |        |
| flarum-suspend       | v0.1.0-beta.9  |        |
| flarum-tags          | v0.1.0-beta.10 |        |
+----------------------+----------------+--------+
Base URL: https://my.site.gg
Installation path: /var/www/community
Debug mode: off
```

**Comment by clarkwinkelmann** [comment]
I'd say this is a feature. The idea is that you can then trigger a new verification email after the account was created if there was an issue, instead of completely blocking the registration. This also lets admins manually validate an account if for some reason email can't be delivered to that address.

Same thing happens with replies. If notifications fail to send, we don't cancel the whole reply.

It goes in the "unintuitive mail error messages" category. Not sure if we already have an issue on GitHub that talks about that. There was some discussion recently on the forum about the fact visitors can't know the difference between an error processing the request and an error sending the emails.

**Comment by luceos** [comment]
@flarum/core this is an example where sending the mail on a queue would reduce visual feedback to the user.

**Comment by franzliedke** [comment]
@luceos I politely disagree (and agree with @clarkwinkelmann, I think), for the following reasons:

- The error message is more confusing than a possible delay in receiving the email.
- Email providers are third-party services (whether it's SMTP or some specific service's API) that could be down / slow / not reachable due to many different circumstances (network problem, provider problem, rate limiting) not under our control, as is normal in distributed systems. We don't want these effects to block, delay or break our web frontend, where it would hurt scalability or stability.
- We already allow re-sending in our UI, which makes it clear that sometimes emails is not received (immediately).
- Queues can retry on error, the sync handler cannot.
- There's no reason to break the actual user registration just because the side-effect failed (temporarily).

Sending all (!) kinds of emails via background workers is the de-facto standard in most modern software systems I know.

**Comment by franzliedke** [comment]
That said... it's likely that with @datitisev's PR #1921, the exact problem from the OP will not appear anymore, because *no email will be sent at all*, silently. That's another problem, though, and the discussion about queueing this email is a good one to be had.

**Comment by luceos** [comment]
I think I never was against Clark's reasoning. I just gave an example based on a previous meeting where queues could have unforeseen side effects, this being one example. I agree it's fine to dispatch the email in the queue as well.
