### ISSUE TITLE
[Flags] Add validation to Flag objects

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1936]
With https://github.com/flarum/flags/pull/18 (and even without!), users might encounter errors when putting too much content into the details.

We need validation that can be easily extended (e.g. akismet) that can check for the proper things.

**Comment by franzliedke** [comment]
Out of interest: Would we actually throw an error, or would MySQL silently truncate the data?

**Comment by datitisev** [comment]
Unless I'm mistaken, we still require validation.

**Comment by franzliedke** [comment]
I think with the final version of flarum/flags#18 that got merged (and tweaked in master), we actually have more validation than expected (for not providing a reason when it's required) and less of a problem with large content, because we stuck with a `text` column, where people would have to try hard to hit errors. :wink:

**Comment by franzliedke** [comment]
a.k.a. I'm suggesting to close this again.

**Comment by datitisev** [comment]
Ah, my apologies then.

**Comment by datitisev** [comment]
As Franz suggested closing this back in February, and this hasn't had much traction, I'm gonna close it.
