### ISSUE TITLE
Fix composer preview button on mobile

### ISSUE THREAD

**Issue by alexbagirov** [flarum/core#196]
It is described [here](http://discuss.flarum.org/d/406/preview-button-does-nothing-on-lg-nexus-5/1).

**Comment by SolidOrphan** [comment]
Did you minimize your message ? I'm on Chrome on a Galaxy S5 and it works.

**Comment by tobscure** [comment]
Steps to reproduce:

1. Open up reply/edit post composer on mobile
2. Tap the preview button. Flarum might scroll a bit, but no preview will be visible.

Expected behaviour:
Tapping the preview button on mobile should minimise the composer and then scroll to the preview.

Technical info:
On desktop, the composer's preview button scrolls so that the reply placeholder or post being edited (which shows a live preview) is visible. On mobile, because the composer behaves as a modal window, this button is ineffective.

What needs to be done:

* In the ReplyComposer and EditPostComposer components, add code to the preview button handling code that detects whether or not the composer is behaving as a modal window (probably check for the presence of .composer-backdrop).
* If it is, tell the composer to minimise.
