### ISSUE TITLE
Make PostStreamScrubber display numbers relating to only "comment" posts

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#197]
Setting a post as sticky is adding to the count of posts. For example, if a post (a single one) is set to sticky, the sticky "action" will count as a comment or reply. See the [corresponding thread](http://discuss.flarum.org/d/407/stickies-count-as-a-post/1).

**Comment by Fastidious** [comment]
Adding to this. It seems any action taken on the original post (adding or removing a label, for example), will add more "post" count. [This post](http://discuss.flarum.org/d/392/frequently-asked-questions-please-read-here-before-posting/1), for example, now has a post count of three, even though it is only one.

**Comment by tobscure** [comment]
Steps to reproduce:

1. Go to http://discuss.flarum.org/d/392/frequently-asked-questions-please-read-here-before-posting/1
2. Scroll down to the bottom
3. Observe that the scrollbar says "1 of 3 posts"

Expected behaviour:
It should say "1 of 1 post"

Technical info:
In Flarum, there are different "types" of posts. Typical posts that users create are of the `comment` type. Other post types may reflect events within the discussion, such as changing the title (`discussionRenamed`) or stickying the discussion (`discussionStickied`).

The PostStreamScrubber, the scrollbar showing the current position within the discussion, displays the index of the last post visible in the viewport, as well as the total number of posts (e.g. "1 of 3 posts"). However, it doesn't take post type into consideration, and displays the index/count of all posts. It would be better if it only displayed the numbers relating to `comment` posts.

What needs to be done:

* In the PostStream component, add a data-type attribute to stream items which contains the post's type.
* In the PostStreamScrubber component's `update` method, when looping through stream items, check on the item's data-type attribute and work out the index of the last visible comment post.
* Change the PostStreamScrubber component's `view` to display that index instead of `this.visibleIndex()`, and the discussion's `commentsCount` instead of `this.count()`.
