### ISSUE TITLE
Require PHP 7.2+

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1988]
Let's give everyone a two months heads-up, and then dump PHP 7.1 (does not even receive security fixes anymore) for beta.13.

Related:
- https://github.com/wikimedia/less.php/pull/17#issuecomment-580886403
- This would enable further Laravel upgrades. Any LTS we can fix our eyes on?

**Comment by tankerkiller125** [comment]
This seems like a very reasonable time frame, especially since every major PHP project I know of has already been updated to support 7.2 and 7.3, and all Linux distros that I know of ship with 7.2 as the default or newer. Plus if we manage to update our illuminate components in beta.13 7.1 would be unsupported anyways.

**Comment by tankerkiller125** [comment]
> This would enable further Laravel upgrades. Any LTS we can fix our eyes on?

I just now noticed this line here, Laravel is at 6.0 LTS which will receive security updates until September of 2022. As a note Laravel switched to Semantic versioning, as such the upgrade process going forward will be from version 6.0 -> X.0 instead of the old 5.0 -> 5.X

The proper composer version string for the LTS of laravel components is `^6.0` the following is the comparison between our version (5.7.x) and the latest LTS release (6.0) and does not include all the latest patches (which are non-breaking) https://github.com/laravel/framework/compare/v5.7.28...v6.0.0
