### ISSUE TITLE
[Tags]: Topic slideout not working if page opened from link

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#1993]
## Bug Report

**Current Behavior**
The topics slideout that pops out when you move your cursor to the left edge of the screen only works if the current page was reached by clicking on a link from the flarums tag page. If the page was reached via opening a URL, refreshing the page, or opening the page in new tab, the slideout doesn't work.

**Steps to Reproduce**
1. Go to https://discuss.flarum.org/d/859-flarum-community-guidelines (or any page)
2. Move your cursor to the left side of the screen. The expected slide-out doesnt pop out
3. Open the same page, but by directly clicking on it from the tags page.
4. Move your cursor to the left side of the screen. The slideout works.

**Expected Behavior**
The slideout should work regardless of how the discussion page was reached.

**Environment**
- Discuss (flarum.org)
- Browser: Chrome 80

**Possible Solution**
I'll look into making a PR to fix.

**Comment by askvortsov1** [comment]
Addressed in flarum/framework#1998

**Comment by franzliedke** [comment]
Hmm... I am almost certain that this behavior is intentional, even though it may be confusing at first. The point of the left sidebar, as I understand it, is to keep you in the context where you came from - and that could be any form of pre-filtered discussion list:

- page 103 of the "All discussions" page
- any tag
- a search result
- a tag that is excluded from appearing in "All discussions"

In some of these cases, having the left sidebar with a bunch of posts that have no relation to the topic being viewed would have the potential for confusion in my humble opinion.

I can see how it's confusing when you refresh a discussion page and the list suddenly disappears, but I also don't think that's a 80% use-case. The other case is a direct link to a discussion - and in those cases there's no reason to be confused; also, you're likely most interested in the discussion itself.

---

I see no indication that this is not intended as working. That being said, we can of course have a discussion about the feature, but I'm labeling it as such.

**Comment by askvortsov1** [comment]
Maybe we could consider keeping only the adjustment where the cached discussionList is set to retain @franzliedke. This should solve it being lost on refresh while not necessarily recreating it on direct access to a discussion page.

**Comment by franzliedke** [comment]
> Maybe we could consider keeping only the adjustment where the cached discussionList is set to retain @franzliedke. This should solve it being lost on refresh while not necessarily recreating it on direct access to a discussion page.

Can you expand on how the `retain` change would affect reloads exactly? (My understanding of Mithril is limited, to be honest.) I may or may not be misunderstanding you, but AFAIK the cache is just an in-memory cache that's filled while doing client-side navigation, so it would be empty after a refresh.

**Comment by askvortsov1** [comment]
I'm not by any means a mithril expert either, but I can confirm that from my testing, adding "retain" keeps the discussionList there after refresh.

**Comment by franzliedke** [comment]
Just stumbled across flarum/issue-archive#396, so a) apparently Toby was open for changing this and b) this is a duplicate. :wink:
