### ISSUE TITLE
Upgrade to Laravel 5

### ISSUE THREAD

**Issue by tobscure** [flarum/core#2]
Currently Flarum is running on Laravel 4.2. We will want to begin the transition to Laravel 5 sooner rather than later.

I don't know how stable Laravel 5 is at the moment, but I can't imagine that the changes will really affect Flarum's code that much. Can anyone who is more familiar with the changes in Laravel 5 comment?

**Comment by yulianovdey** [comment]
Since L5 is finally out I'll start working on this.

**Comment by tobscure** [comment]
Thanks @yulianovdey. I have a few thoughts:

- We can ditch the laracasts/commander command bus and domain events for the native L5 one (which you've already mentioned :)
- I wonder if we should refactor the whole Api/Actions thing to be more "native"? Make use of controllers and middlewares and stuff? Haven't thought about this in detail, and I do like the current setup (it's a nice layer of decoupling from Laravel), but I'm open to suggestions.
- Will also need to work on the flarum/flarum repo and installation instructions. Specifically, workbench is gone.

**Comment by yulianovdey** [comment]
@tobscure I like the current setup, it helps enforce simple classes. I don't think there is any advantage to using controllers if you like the way it is now, unless making things more 'native' is worth the extra bit of familiarity new contributors will have.

As far as middleware, it may be a nice way to move your attemptLogin filter to its own class. I gotta look around more to see what else would make sense for it. Either way I'm assuming you want to keep as little as possible in flarum/flarum so we'll need a clean way to register any middleware out of the core. At least the [default stuff](https://github.com/laravel/laravel/blob/v5.0.0/app/Http/Kernel.php) doesn't even look like it's going to be needed since you're not using (cookie) sessions at all :).

**Comment by thangngoc89** [comment]
@yulianovdey  It looks like we have to remove everything inside app/Kernel.php

**Comment by tobscure** [comment]
@yulianovdey OK, let's keep the current Api/Actions stuff :)

Don't worry too much about all of the auth stuff at the moment. I'm going to implement OAuth2 soon so it's gonna get a makeover. Will probably also make use of cookies somewhat (maybe).

**Comment by tobscure** [comment]
Hey @yulianovdey turns out I have been working quite heavily on the Laravel app — mainly auth stuff, and I'm refactoring API Actions so that it's easier to call them from within other routes. Will be pushing soon. Let me know how far along you are (if you've made a start) and I'm happy to help merge.

**Comment by yulianovdey** [comment]
@tobscure I haven't started yet, still working on something else. Looking forward to seeing your changes :).

**Comment by tobscure** [comment]
@yulianovdey No worries. The refactoring has become a bit of a mess and the next logical step is really to do the L5 upgrade. So I'll be making a start tomorrow!

**Comment by RugWarrior** [comment]
Great work with the upgrade!
