### ISSUE TITLE
Refresh doesn't update notifcations

### ISSUE THREAD

**Issue by jberlyn** [flarum/core#200]
**_1 Upvote**_ Although the refresh implementation is a temporary solution until the Pusher extension is developed, I think it would make sense for the refresh functionality to also update any possible notifications you may have received. Currently, it only updates the discussion listing.

**Comment by tobscure** [comment]
+1

**Comment by tobscure** [comment]
When the Pusher extension is disabled, Flarum shows a refresh button at the top of the discussion list. Clicking this button refreshes the discussion list, but it should also check for new notifications.

What needs to be done:

* Add a click handler to the refresh button so that it reloads the user data (`app.store.find('users', app.session.user.id())`) in addition to refreshing the discussion list.
* After the data is reloaded, calling `m.redraw()` should be sufficient because the number of unread notifications is a part of the user entity.
