### ISSUE TITLE
PostStream scroll bug

### ISSUE THREAD

**Issue by w-4** [flarum/core#2001]
## Bug Report

When refreshing the discussion-page in chrome sometimes it jumps 10 number forward or back to a different post. 

![image](https://user-images.githubusercontent.com/36057469/74506158-8dd5ab80-4f2b-11ea-98f2-ddb7d20b533b.png)

Setting a timeout of 200ms for the scrollToNumber fixed the issue for me.

**Comment by askvortsov1** [comment]
We still want to fix this

**Comment by matteocontrini** [comment]
Out of curiosity, does the fix for this issue also fix the issue that can be seen in [this video](https://drive.google.com/file/d/1OglVK0t3zdANCwWbGcxFkH9A_HdqLtmy/view)?

(For future reference: the screen recording shows the user tapping on a mention, but after some time of loading the scrolling settles on the wrong message, about 10 messages above the correct one.)

**Comment by askvortsov1** [comment]
It should. There are still some things wonky with the post stream and scrubber, but I believe that particular issue should be fixed.

**Comment by matteocontrini** [comment]
@askvortsov1 awesome, thank you!
