### ISSUE TITLE
Authentication Revamp

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2043]
Right now, we have a pretty decent foundation for various authentication methods, but I think a bit of infrastructural revamp is warranted. I propose the following:

- Keep authentication within the Forum service provider, so that the various views can take full advantage of the frontend
- Providing an extender for authentication methods. This would support managing authentication drivers, as well as pre/post login, logout, and registration middleware
- Creating an interface for authentication drivers (they would define login, registration, logout, and possibly other things (e.g. resetting passwords).
- making the current username password system an instance of these drivers
- cleaning up code so that login and registration via SSO isn't dependent on a login modal being open while not disturbing the convenient system.
- Similarly to the above point, standardize an abstract class of "SSO Auth Providers".  as an implementation of the authentication driver instance. Right now, there's a lot of code duplication across all the SSO systems that we could easily manage centrally.
- adding a section to the user profile page where users can connect and disconnect login providers
- adding a section to the admin panel where forum admin can enable / disable authentication providers (and possibly configure other settings, like disabling sign-up and requiring email validation). Require that at least 1 be enabled at all time though.
- Add a console command to disable custom authentication drivers and reenable the username/password driver so that admins don't get locked out of their forum if SSO breaks. 

And as a very eventual wishlist feature, offer a way to test SSO providers from the admin portal before enabling them.

Considering that our goal is to provide a stable API for extensions and that a large portion of extensions have to do with various SSO providers, I think this is something (or at least components of it) that warrants being included in Stable. It would also provide an elegant solution to https://github.com/flarum/core/issues/641, https://github.com/flarum/core/issues/1858, https://github.com/flarum/core/issues/897, and others.

**Comment by tankerkiller125** [comment]
I have no problem with creating an auth extender that makes it easy for SSO, I like having the ability to disconnect SSO providers from accounts, disabling authentication providers is already part of the extensions page, but being able to disable regular register/login forms would be useful to some forums and I would love to see something so that extensions can inject themselves into every part of the login/registration flow (good for extensions that do fraud prevention)

My biggest concern is this:
> * making the current username password system an instance of these drivers

Why? What benefit does this have? I see no benefits to doing this and in fact I see nothing but extra complications and extra time supporting people with this. I can't think of any software that doesn't have the username/email password system built in and usually hard coded in. They usually just have a way to disable them but removing it entirely into a "driver" seems like it's going to cause more problems than it solves.

**Comment by askvortsov1** [comment]
> Why? What benefit does this have? I see no benefits to doing this and in fact I see nothing but extra complications and extra time supporting people with this. I can't think of any software that doesn't have the username/email password system built in and usually hard coded in. They usually just have a way to disable them but removing it entirely into a "driver" seems like it's going to cause more problems than it solves.

Maybe this isn't always the best approach, but I feel that special cases are generally not worth it. It wouldn't be completely separated away (I agree with having the option to disable it separate from the option to enable/disable SSO providers), but I think that the actual implementation of handling login/registration views could be abstracted away across all providers. We could use a GET parameter or path parameter to decide which provider would be used for a given request, and ultimately have a cleaner system. I agree that username/password should absolutely not be removed from core, but implementation wise, I think this could be easier.
