### ISSUE TITLE
Fix styling issue for emojis in spoiler

### ISSUE THREAD

**Issue by luceos** [flarum/core#2053]
Fix all issues with the spoiler, check with emojis, links etc

**Comment by franzliedke** [comment]
See discussion in flarum/markdown#13.

**Comment by tankerkiller125** [comment]
Doing some testing the tag edit from the original pull request will need to stay in the main markdown extension, the LESS is something that can be split out to different extensions. LESS for core features (eg. links) will remain in the markdown extension.

**Comment by tankerkiller125** [comment]
The reason I split it was because it didn't make sense to me to include CSS for something that isn't enabled. However I'm fine with putting the CSS modifications in core if that's where we want them. However the PHP fix from flarum/markdown#13 should remain there in my opinion as it's markdown specific and does not apply to BBCode.

**Comment by franzliedke** [comment]
Closed by https://github.com/flarum/markdown/pull/14.
