### ISSUE TITLE
Switch component background merges with Modal background

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2119]
The switch background when not turned on is the same as the modal background, making it very hard to see.

![image](https://user-images.githubusercontent.com/6401250/79021789-74776700-7b4a-11ea-9221-0a83d3c6c08a.png)

**Comment by nina-py** [comment]
So what would be a good solution for this issue? The backgrounds are indeed the same. One way would be to add an outline to the switch - i.e. a thin white border so that it would still be the same on white backgrounds but be visible on the modal background. The switch styles are pixel-perfect and should probably not be messed with though... Can changes to the modal background be considered?

**Comment by nina-py** [comment]
One possible option would be to make the background for the disabled switch white just on modals. That way global styles would remain untouched. See screenshot below:

![flarum-modal-switch](https://user-images.githubusercontent.com/22447785/98428666-9b087b00-20f6-11eb-9d1a-c45f7541631c.png)

**Comment by askvortsov1** [comment]
That would work for me
