### ISSUE TITLE
Flarum gives a cookie warning in console

### ISSUE THREAD

**Issue by therealsujitk** [flarum/core#2157]
Flarum gives the following warning in v1.0-beta.13:

![image](https://user-images.githubusercontent.com/60378235/81477890-c12c8b80-9237-11ea-8eb3-bee569c7e32f.png)

*Cookie “flarum_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies*

**Comment by rob006** [comment]
AFAIK this is the result of lack of HTTPS. With HTTPS enabled Cookie has `Secure` attribute and there is no warning.

> The None directive requires the Secure attribute.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by tankerkiller125** [comment]
@rob006 This is actually untrue, Flarum in the past has not set a explicit same-site value which would cause this issue to appear. Setting the secure flag and using https does not clear this warning. If there was no HTTPs enabled and we did explicitly set the None value the error would be different (as noted in the very documentation you linked too)

**Comment by rob006** [comment]
@tankerkiller125 I actually tested this on Firefox 76.0, and it works as I said - enabling HTTPS clears the warning on Flarum. And it makes perfect sense for me - since `SameSite=None` (or `SameSite=Lax`) is implicit, why it should behave differently if you set `SameSite` explicit? The meaning is the same in both cases (assuming there is `Secure` attribute preset, which is in case of Flarum).

**Comment by tankerkiller125** [comment]
@rob006 I've made some adjustments so that it can be configured, by default it will still be set to lax (as it's a sane default and compatible with HTTP sites)
