### ISSUE TITLE
[Mentions] Allow mentioning groups

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2175]
## Feature Request

If groups are used to indicate teams, it would be useful to be able to mention a group of users and have all of them be notified.

**Comment by luceos** [comment]
A technical issue with this is that one would have to prevent users to use the same slug or maybe prefix the slug with `group-`?

**Comment by askvortsov1** [comment]
I've been in favor of requiring unique slugs for groups (in addition to the name) for a while now, provisioning based on ID is an absolute headache

**Comment by clarkwinkelmann** [comment]
This raises the question of which part of our codebase should be responsible for each of those features:

- Which one registers group slugs
- Which one verifies the uniqueness of slugs across usernames and groups

I expect some complicated settings to be needed for such a feature due to the potential for abuse.

Maybe it would make more sense to delegate this to some kind of "Teams" community extension which would handle everything without over-complicating our core software and core extensions.

What would be the use cases of a group mention extension be and why would it belong in the core ecosystem? I don't think I have seen many requests for such a feature.

**Comment by askvortsov1** [comment]
If we go the route in https://github.com/flarum/core/issues/1734#issuecomment-644391424, we don't need slugs for groups, and can just store the group ID, preixed by "G". That would alleviate all these issues

**Comment by tankerkiller125** [comment]
Still relevant, possibly something to work out during the UTF-8 work for beta 15
