### ISSUE TITLE
Discussion list item controls are too close to reply count

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#218]
Hovering on the there dots on topic list, the round follow button will almost overlap numbers or comments, on topics with many replies. [Pertinent forum post](http://discuss.flarum.org/d/461/hover-on-topic-at-the-end-three-dots/1).

**Comment by tobscure** [comment]
Steps to reproduce:

1. Log in and go to the discussion list
2. Hover over a discussion with 100+ posts
3. Observe the three dots

What needs to be done:

* Give the discussion list item a bit more padding on the right (no more than 5px) to leave more room for the controls

**Comment by franzliedke** [comment]
Also, when hovering over the three dots, the circle around them is way to close to the right edge of the hover background of the discussion item...

**Comment by franzliedke** [comment]
We have a similar issue when hovering over the three dots when the discussion list is moved to the sidebar.

How about moving the three dots and the menu to the avatar - it already has the same shape. We'd then show the three dots instead of the avatar when hovering over a discussion.

Alternatives:
- more padding (there's not much room)
- leaving out the moderation controls when the list is so slim (though really it is the same on mobile screens)

What do you think, @tobscure?

**Comment by tobscure** [comment]
I don't like the idea of moving the dots over the avatar. (1) it makes the hover more ugly, (2) I think there's an unspoken UX convention for dots to be on the right, (3) I was thinking eventually we'll use the avatar hover as a checkbox for selecting multiple discussions, like Google Inbox.

I don't like the idea of leaving out the moderation controls because they can definitely be useful in the sidebar. You're right that there's not much room for more padding. (Though, we could afford to move the dots 5px to the right)

IMHO I don't think it's an issue because the reply count is still visible – it only gets obfuscated if you actually hover over the dots. 

Another alternative though would be to make the reply count smaller and move it to the start of the second row, or something like that. (Only for the sidebar view)

**Comment by franzliedke** [comment]
> IMHO I don't think it's an issue because the reply count is still visible – it only gets obfuscated if you actually hover over the dots.

We definitely need to move them a little, because they even obfuscate longer reply counts when hovering over the list item.
