### ISSUE TITLE
About Mail Settings

### ISSUE THREAD

**Issue by nathanli97** [flarum/core#2247]
Please forgive my confusing statement，My English are very poor.

## Feature Request

I have a issue when configuring my mail settings.My Server`s SMTP ports was banned by server provider for security.

I can not use any of mail provider options you provided  because My Server located in China Mainland,these provider I can not visit.

The only I can visited mail service provider is company which located in China Mainland,or sendgrid.

Could you add a custom option of mail settings that let me to configure a custom mail sender URL and custom POST format of HTTP request of mail sending?

or just add a option of sendgrid in mail settings .

Thank you.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**

Mail functions are located in your flarum/core package,so I post this issue here.

**Describe alternatives you've considered**
 Add a option of sendgrid in mail settings.

**Comment by askvortsov1** [comment]
Hi! It looks like send grid actually accepts connections over SMTP: https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/, you should try the various ports and see if any of them work. Otherwise, if you need a custom email email driver, that's something that's doable via an extension using the mail extender. I'm going to close this issue as this isn't really something we would maintain within core, but I encourage you to look into a custom extension, or to open a support ticket on our forum if you're unsure how to do that.
