### ISSUE TITLE
Web timeouts when installing through web installer

### ISSUE THREAD

**Issue by katosdev** [flarum/core#2258]
## Bug Report

**Current Behavior**
From @luceos : 
Seen an increasingly number of support issues relating to installing through the web interface. The database installs incorrectly probably due to execution or proxy timeout.

**Comment by katosdev** [comment]
Initial issue created as requested - details to be updated.

**Comment by luceos** [comment]
That's all in fact. The issue seems that the number of migrations and their complexity occasionally seem to be processed only partially. Some of our migrations (eg one the one that adds foreign keys to the posts table) require quite some processing power I assume and together they take too long. 

As @franzliedke already had in mind, we should create different migrations; one set for upgrades and one for new installs.

**Comment by askvortsov1** [comment]
Squash migrations down, start fresh on stable; add existing migration that would update. Or separate package?

Migration helpers more flexible: check if columns exist?

Info about fixing stuff manually?

It'd be really nice if we could do them atomically.

**Comment by luceos** [comment]
I still prefer having one package that supports beta forums in upgrading so that they can be removed after the upgrade to stable. Squashing the existing ones into new ones for v1 would then be a solution to the above issue and fix #2442 ; we could repeat this for v2.

**Comment by askvortsov1** [comment]
My greatest concern is having to maintain 2 separate sets of migrations, it'd be so easy to mess up and introduce inconsistencies. Any system we choose should have the following features:

1. Use atomic (single operation) migrations as much as possible. The worst issue by far is that if we fail between operations within a migration, everything's messed up. Could we support `up` and `down` being arrays of closures (or associative arrays mapping step names to steps) instead of single closures? It'd be more code, but then we could try/catch the individual steps when attempting to roll back. On the other hand, that increases the number of queries needed dramatically.
2. We'd need to support a case where someone tried to update from before this intermediate package exists to after this intermediate package exists. IE if we're at Flarum v2.2 and someone tries to upgrade from beta 9, that should be accounted for.

**Comment by askvortsov1** [comment]
New proposal for approaching this:

-  On every major release, generate sql dump files ala https://laravel.com/docs/8.x/migrations#squashing-migrations. Do this for MySQL, and for Postgres, if we ever add support for it. Commit a dump per supported DB to the migrations folder
- For new installs, use the dump + any migrations after the dump. Upgrades should use the CLI, which will just use migrations.
- Support subfolders in migrations, so that we can group the 0.x migrations, 1.x migrations, etc. We'll still have just one dump, but this should make organization cleaner, as we'll know that any migrations in a subfolder are in one of the dumps.

Potential challenges:
- We'll need to make sure that the dump generation ONLY includes migrations from core
- Could this eventually support extensions?

**Comment by askvortsov1** [comment]
> Could this eventually support extensions?

No, because a dump is instructions to create a table from scratch. Incremental dumps don't seem to be supported.

> We'll need to make sure that the dump generation ONLY includes migrations from core

Do we need to though? Maybe we should have 2 dump files: one for just core, another for core + bundled extensions. Run the first or the second depending on whether Installation extensions have been overriden (see #2718). This would make new installs **extremely** fast.

**Comment by luceos** [comment]
@askvortsov1 I wouldn't include migrations from extensions. These are fairly small and not causing too much issue. And it wouldn't make sense to add dumps for optional bundled extensions to core.

**Comment by askvortsov1** [comment]
> @askvortsov1 I wouldn't include migrations from extensions. These are fairly small and not causing too much issue. And it wouldn't make sense to add dumps for optional bundled extensions to core.

On my local install:

Connecting to database
STEP TIME: 0.0047080516815186

Writing config file
STEP TIME: 8.7976455688477E-5

Running migrations
STEP TIME: 8.3668730258942

Writing default settings
STEP TIME: 0.22235608100891

Creating admin user admin
STEP TIME: 0.10173606872559

Publishing all assets
STEP TIME: 0.015758991241455

Enabling bundled extensions
STEP TIME: 3.2332360744476
