### ISSUE TITLE
We can change other users’ discussion tags.

### ISSUE THREAD

**Issue by LianSheng197** [flarum/core#2355]
## Bug Report

**Current Behavior**
We can change other users’ discussion tags. Maybe have exploit risk.

**Steps to Reproduce**
1. Go to any discussion
2. Open develop tools
3. Copy code from this file [[changeDiscussionWithSelectTags.js.txt](https://github.com/flarum/core/files/5322271/changeDiscussionWithSelectTags.js.txt)], and change `var _tags = [1];` to specifics tag id.
4. Most conditions can be successfully changed.

**Expected Behavior**
Only the discussion initiator and admins should have the permission to change the tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/18535495/95001094-4c4c5a80-05f9-11eb-924b-031217b02435.png)

**Reference**
https://discuss.flarum.org/d/25036

**Comment by luceos** [comment]
Thank you for reporting this, it's very much appreciated. We'll look into this, reproduce it and provide a fix as soon as we can. We're in the middle of a feature freeze for the upcoming release, so I'm not entirely sure we can patch this in. If the issue is confirmed we will follow up with a new tag/version for the tags extension.

**Comment by SychO9** [comment]
Can confirm this happens on the latest dev build.

**Comment by SychO9** [comment]
woups, my apologies, did not notice it was assigned.

**Comment by askvortsov1** [comment]
No worries, awesome to see someone take this on!
