### ISSUE TITLE
All callable-based extenders should accept and resolve invoke-able classes

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2401]
Right now some extenders method only accept `callable` arguments. This complicates development when we want to place a large amount of code in a separate file. It's possible to create an invoke-able class and manually resolve it ourselves before passing it to the extender, but it would be even better if all extenders could do this for us, so that we can only pass the `::class` name to them.

Right now we have:

:heavy_check_mark: = accepts invoke-able classes and resolves them through container
:negative_squared_cross_mark: = only accepts `callable`

- [Compat](https://github.com/flarum/core/blob/master/src/Extend/Compat.php): :heavy_check_mark: (uses container `call`)
- [Event.listen](https://github.com/flarum/core/blob/master/src/Extend/Event.php): :heavy_check_mark: (supported by Laravel's Dispatcher)
- [Formatter.configure](https://github.com/flarum/core/blob/master/src/Extend/Formatter.php): :heavy_check_mark: (manually implemented)
- [Frontend.content](https://github.com/flarum/core/blob/master/src/Extend/Frontend.php): :heavy_check_mark: (manually implemented)
- [Model.default](https://github.com/flarum/core/blob/master/src/Extend/Model.php#L57): :negative_squared_cross_mark: [uses is_callable()](https://github.com/flarum/core/blob/master/src/Database/AbstractModel.php#L85) in the model. Can't really resolve strings through the container since strings are also valid arguments
- [Model.relationship](https://github.com/flarum/core/blob/master/src/Extend/Model.php#L171): :negative_squared_cross_mark: argument restricted to `callable`
- [User.permissionGroups](https://github.com/flarum/core/blob/master/src/Extend/User.php#L47): :negative_squared_cross_mark: argument restricted to `callable`

I think the two that need changing are `Model.relationship` and `User.permissionGroups`. We need to change the method signature to accept string, and manually resolve strings through the container or make everything go through the container `call`.

I'm also not sure whether there's a difference between those different methods of calling the invoke-able classes. We need to make sure it's consistent across the API.

When I started writing this issue I had problems not being able to pass invoke-able classes to `callable` arguments at all. But it seems like I made some kind of error. Invoke-able classes work fine with `callable` arguments, we just need to instanciate the class ourselves beforehand.

**Comment by askvortsov1** [comment]
This is a really good point: invokable classes allow us to inject anything needed into the handler. For `User.permissionGroups` this is relatively easy: all we need to do modify https://github.com/flarum/core/blob/7055f6d9412bfdfbb5c5499cbecd45d9e6615d6d/src/Extend/User.php#L56-L58 so that it runs it through container->make if it's a string.

For the Model ones, the first thing that comes to mind is declaring a singleton and extending it like we do everywhere else, and only resolve it when DatabaseServiceProvider boots. Then, set that `AbstractModel::$customRelations` to that. Same thing we do now, just an extra step.

My only concern is that all these singletons are repetetive and a fair chunk of boilerplate. We're not bound by BC issues since the extenders are the only public API, but I wonder if there's a better way. Although pure LoC wise, the events we're using now probably take up more... Either ways, I'd be in favor of making these changes but thinking about ways to clean it up a bit.

**Comment by clarkwinkelmann** [comment]
Note from today's meeting: when resolving the classnames as late as possible, we run into the issue that we don't have access to the container "the proper way". For example when the `User\User` class calls the `$groupProcessors` callbacks, it doesn't have a container instance available.

If we want to avoid `app()` in those situations, we can still just have the extender register an anonymous function that does the container call, like (untested)

```php
$container->extend('flarum.user.group_processors', function ($existingRelations) use ($container) {
    return array_merge($existingRelations, array_map($this->groupProcessors, function ($groupProcessor) use ($container) {
        return function () use ($container) {
            return $container->call($groupProcessor);
        };
    }));
});
```

So I think this point is a non-issue. We can use different strategies for different situations. We just need to have the extender API consistent.
