### ISSUE TITLE
Notification Channel Extender

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2419]
Part of #1891 

The following changes are needed IMO:

1. A "NotificationDriverInterface" interface should be created.
2. Implementations of this driver for sending regular notifications and mail notifications should be created
3. In NotificationSyncer, https://github.com/flarum/core/blob/34e98c884fe47537744d0567171dc9fde505fddc/src/Notification/NotificationSyncer.php#L105-L111 should be replaced with code that calls all registered notification drivers. Logic for deciding whether to send a notification and for enqueuing jobs should be part of the drivers
4. Calls for `event(new Sending($this->blueprint, $this->recipients));` should be moved from `SendNotificationsJob` to `NotificationSyncer`, and deprecated (and the event should be deprecated too)
5. An extender to add new notification drivers  should be added `(new Extend\Notification)->driver(driver_name, CustomNotificationsDriver);`, with integration tests

**Up For Discussion**

In `ConfigureNotificationTypes`, we allow the type to specify which drivers/channels it should be enabled for by default. Do we want to do a similar thing here, where channels can provide an array of types that they should be enabled for by default? If so, `NotificationServiceProvider` might need to be refactored. @flarum/core

**Comment by SychO9** [comment]
So, for the notification driver interface, I guess we'll have three methods, as you already mentioned, one for deciding whether to send the notification and another one for enqueuing the notification job.

An additional one would be for adding(or not) the user preference.
https://github.com/flarum/core/blob/0b2a5fa5b85cd82c4dfd83924d7a38ea712b45b8/src/Notification/NotificationServiceProvider.php#L47-L59

Also a static method to return the name of the driver would be needed I believe. (alert or email for example)

```php
interface NotificationDriverInterface
{
    public function canSend(BlueprintInterface $blueprint, array $users): bool;

    public function enqueueJob(BlueprintInterface $blueprint, array $users): void;

    public function addUserPreference(string $blueprintClass, bool $default): void;

    public static function getDriverName(): string;
}
```

The two implementations we'll have would be `AlertNotificationDriver` and `EmailNotificationDriver`.

> In `ConfigureNotificationTypes`, we allow the type to specify which drivers/channels it should be enabled for by default. Do we want to do a similar thing here, where channels can provide an array of types that they should be enabled for by default? If so, `NotificationServiceProvider` might need to be refactored.

I don't think we have an actual use case for that in any of the bundled extensions, but I do like the idea of having that, It should be easier now as well since we can edit the enabled channels by default of the notification types through the container.

**Comment by askvortsov1** [comment]
For the driver name, it's not really used in implementation, only in registration. I'd prefer to see it like with MailDriver and DisplayNameDriver, where it's a part of the mechanism to register the driver, but isn't part of the implementation (essentially, the singleton that stores drivers is an array that maps driver names to the drivers themselves). This has the additional advantage of allowing drivers to be overriden by extensions (if necessary).

I also feel like it might be simpler to have `canSend` and `enqueueJob` to just be 1 method called `send`.

**Comment by SychO9** [comment]
> For the driver name, it's not really used in implementation, only in registration. I'd prefer to see it like with MailDriver and DisplayNameDriver, where it's a part of the mechanism to register the driver, but isn't part of the implementation

Hmm, sorry if I'm a bit slow, but I don't really understand what you mean here, the drivers here as I understand are a bit different than the mentioned ones in terms of implementation. I cannot see how this interface can be involved in their registration.

Perhaps I'll be able to understand through the pull request reviews.

**Comment by askvortsov1** [comment]
What you have in the PR is pretty much exactly what I had in mind.

**Comment by SychO9** [comment]
Good to know, just me slightly missing the point there then.
