### ISSUE TITLE
"Service Provider" extender

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2421]
Part of #1891 

As the team has been slow to provide official extenders, many community extensions have started using `Flarum\Extend\ExtenderInterface` to register code that runs when flarum boots and has access to the `Container` instance. This isn't really the intended use case of extenders, but it's an important use case nevertheless.

Instead, what if we had a `ServiceProvider` extender, which would essentially just run a function with an instance of `Container` provided?

@clarkwinkelmann @luceos I know you've used this pattern in your extensions; how would you feel about something like this?

**Comment by clarkwinkelmann** [comment]
I have used both extenders AND providers and I think they serve different roles.

When I use an extender, I usually try to register stuff at the same time as other native extenders. Sometimes it's an extender that uses logic from a native extender but does something more complex that can't be done with the native extender (for example, dynamically generating javascript content)

The other use case is to listen for events. But this use case will disappear since we now have the Event extender, or because the events in question will receive their native extender in b15.

When I use a service provider, it's usually because I want to do something after other extensions have registered their stuff, or because the things are not constrained by the order Flarum loads them.

I've never used custom extenders just to "access the container". As you will have seen if you read my code, I very rarely access the container via dependency injection.

I'm pretty sure there are a few use cases where you would like to run stuff during the extension loading and before the service provider register. This could include replacing existing service providers :)

That being said, I do think having a service provider extender would be a very good idea. The extender could even allow defining callbacks for `register` and `boot` "events" instead of a full class.

**Comment by askvortsov1** [comment]
Sorry for the confusion, I think this is where my lack of Laravel knowledge is letting me down.

If I understand correctly, boot process is as follows:

1. `register` for all proper Laravel service providers runs during https://github.com/flarum/core/blob/524b0a53e9dc2116fd6ed95a723be537cdbf1ad0/src/Foundation/InstalledSite.php#L111-L137.
2. `extend()` for all extenders in full extensions runs
3. `extend()` for all local extenders runs

If I'm understanding you correctly, you use service providers to execute code between (1) and (2), and custom extenders to execute code between (2) and (3)? Would those be the `register` and `boot` "events" you propose? As for replacing core's service providers, that sounds like a solid use case, but would need some refactoring of `Application`. Perhaps that might be good as a later addition?

**Comment by clarkwinkelmann** [comment]
I think I got a bit confused with the loading order. You're correct.

`ServiceProvider::register()` happens right when the service provider is added. This means Flarum core providers are registered before extensions, while extension providers are registered in the order the extensions are loaded.

`ServiceProvider::boot()` happens right after all extensions have been registered. Extensions registration happens in the booting callback of the container, which is basically just before the providers boot.

So in practice, extensions could use `ServiceProvider::register()` in place of `ExtenderInterface::extend()` with no functional difference. And `ServiceProvider::boot()` can be used to execute code after all extensions have been registered.

And it seems it's not actually possible to replace/remove a service provider.

All that being said, I'm not sure what we actually want to do with this information? Most developers will need neither custom extender nor service provider. I think we can do the following:

- Yes, implement a service provider extender
- Document both custom extenders and service providers in our documentation
- Recommend custom extenders only for code intended to be called from other extensions

**Comment by askvortsov1** [comment]
> I think we can do the following:
> 
> * Yes, implement a service provider extender
> * Document both custom extenders and service providers in our documentation
> * Recommend custom extenders only for code intended to be called from other extensions

I like this approach. All the extender would need to do is run the Application's `register` method with the service provider.

I don't know if we want to split these into 2 separate methods; we'd need to either package it into a wrapper service provider class, or add logic that runs all the `ServiceProvider::boot()` after extensions have loaded.

**Comment by clarkwinkelmann** [comment]
I think `boot` will work just fine without anything custom, no?

We just make an extender with a signature like `Extend\Provider::register($serviceProviderClass)` which calls `$app->register($serviceProviderClass)` and we should be good to go (?)

I have used service providers with boot methods before and I don't remember having any issue.

We could even accept service provider classnames right in the extender array... Or would that be too sacrilegious?

**Comment by askvortsov1** [comment]
Sorry, my bad. If you're talking about registering a server provider class with `::register`, yeah that'll work fine. But if we're splitting the two methods as `Extend\ServiceProvider::register` and `Extend\ServiceProvider::boot`, that'll be a lot. But I'm not sure that's necessary (or particularly useful).

**Comment by clarkwinkelmann** [comment]
That was my suggestion a few posts above actually, to also offer a `::boot($callable)` method on the extender. But we could always do that at a later stage if we discover there's a usefulness in registering a very short callback for the boot.

**Comment by askvortsov1** [comment]
Alright, let's go with just `::register` for now and adjust if needed in the future!
