### ISSUE TITLE
Add Extension Interface

### ISSUE THREAD

**Issue by idk-pixel** [flarum/core#2445]
Add Extension Interface, this is what it is looking like right now:
![image](https://user-images.githubusercontent.com/63606830/98560193-1f7d0a00-226d-11eb-92ca-19aab2d3b7ba.png)

- [ ] Make Text Bot Install Script
- [ ] JavaScript execute with child_process

You can make an install interface by doing this javascript code:

`require('child_process').execSync('composer require pkg/pkg')`

Maybe make some box like what is the command to run to install this package and instead of going into your SSH console you can just do `require('child_process').execSync('text bot install script')`
Thanks! Looking forward to see it soon!

**Comment by askvortsov1** [comment]
Since Flarum's backend is in PHP not in Node, that unfortunately won't work. The main blocker for an extension management page is the lack of an official extension marketplace, which is something that definitely won't happen until stable.

**Comment by idk-pixel** [comment]
@askvortsov1 You can make another backend:

http://localhost:newPort

```js
const express = require('express');
const app = express()

app.listen(8080)

app.get("/runcmd", (req, res) => {
require('child_process').execsync(code)
})
```

**Comment by idk-pixel** [comment]
this would be localhost:8080 for this example

**Comment by askvortsov1** [comment]
This won't be happening. Running 2 backend services in different languages / frameworks is a mess to maintain / install, and comes with a lot of issues (you'd need to recreate the entire authorization / authentication system in parallel. Besides, PHP has `exec` and `exec_shell` which can be used to run shell commands. The blocker here isn't the backend, but the lack of an official extension marketplace (or official protocol) from which a Flarum instance could get data about available / out of date / etc extensions.

**Comment by clarkwinkelmann** [comment]
There used to be this community extension which ran composer commands in the backend https://github.com/extiverse/bazaar

However it has since been abandoned due too the many issues, some of which were:

- Still bound to the same system limitations as Composer itself
- Dealing with even more limited system resources when running in web instead of `cli`
- Providing good messages for unsupported systems
- Dealing with extension updates
- The necessity of maintaining a marketplace API
- Conflict resolution and suggested dependencies

Running a separate system raises even more issues:

- Access control
- Error management

We have this existing issue to discuss the way we will handle extensions post-stable https://github.com/flarum/core/issues/691

For now the plan is to continue using Composer over the command line for extension management and troubleshooting.

Unfortunately having a graphical interface that has the same system requirements as the official Composer client (even more if you need nodejs!) only creates more work for maintainers without offering any proper benefit in return.

**Comment by luceos** [comment]
The blocker isn't the marketplace so much; it's stable. Having to work on enabling extension installation from within Flarum will delay stable by at least 6 months.
