### ISSUE TITLE
Add target="_blank" and rel="nofollow" to all formatted links

### ISSUE THREAD

**Issue by tobscure** [flarum/core#247]
Steps to reproduce:

1. Make a post containing the following: `http://google.com [url=http://google.com]google[/url] [google](http://google.com)`
2. Observe that none of the posted links have target="_blank" or rel="nofollow" attributes.

Expected behaviour: All formatted links should have the aforementioned attributes. We want all links in posts to open in a new window. We also don't want search engines to follow them, to discourage spammers.

What needs to be done:

* In Flarum\Core\Formatter\Formatter::getConfigurator, we need to configure the URL tag's template to add these attributes
* Refer to s9e\TextFormatter docs for how to do this http://s9etextformatter.readthedocs.org/Templating/Modify_a_template/
* Confirm that target and rel attributes are added to all links (autolinks, as well as links created by the BBCode/Markdown extensions)
* Note that the cache will need to be cleared (delete the contents of system/storage/framework/cache) in order to force a rebuild of the configurator

**Comment by s9e** [comment]
By the way, that doc page doesn't mention it because it focuses on modifying templates using DOM operations but you can read/write a tag's template as a string, e.g.

```php
$tag = $configurator->tags['URL'];
echo $tag->template, "\n";
$tag->template = str_replace('<a ', '<a target="_blank" ', $tag->template);
echo $tag->template, "\n";
```
```html
<a href="{@url}"><xsl:copy-of select="@title"/><xsl:apply-templates/></a>
<a target="_blank" href="{@url}"><xsl:copy-of select="@title"/><xsl:apply-templates/></a>
```

Modifying templates using DOM is more robust and futureproof though, so that's what I'd recommend. Autolink, BBCodes and Litedown all use the same `URL` tag by default, you only need to modify this one tag. If you want to modify every `a` of every template, you can set up a [template normalizer](http://s9etextformatter.readthedocs.org/Templating/Template_normalization/Change_default/) before adding tags.

```php
$configurator->templateNormalizer->append(
	function (DOMNode $template)
	{
		foreach ($template->getElementsByTagName('a') as $a)
		{
			$a->setAttribute('target', '_blank');
		}
	}
);
```

Although I guess you could also iterate through `$configurator->tags` and modify each template one by one too.
