### ISSUE TITLE
Refactor Admin Dashboard (next steps)

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2498]
It would be very nice if we could move the `buildSettingComponent` logic (and other underlying logic) from ExtensionPage to a new base AdminPage, and try to standardize how each admin page works as much as possible: that would make it easier to maintain and add new admin pages.

Also, `buildSettingComponent` currently doesn't support placeholder, min, max, etc. Perhaps all non-reserved keys in the setting object should be applied as attrs to the input?

**Comment by askvortsov1** [comment]
I added this to 0.2, but it would be good to get the attrs part for 0.1

**Comment by askvortsov1** [comment]
Related:

- https://github.com/flarum/core/issues/2503
- https://github.com/flarum/core/issues/2504
- https://github.com/flarum/core/issues/2520

**Comment by SychO9** [comment]
Few things I noticed while working on a theme, let me know if I should create separate issues for them:

**Decouple ExtensionsWidget JSX**
The component's content method builds all of the JSX, as in, the widget element itself, each category, and each extension item, making it harder to customize as you have to override the whole thing if you just wanted to edit extension items for example. We should either separate them into different methods and call those methods.

https://github.com/flarum/core/blob/a2d5dd3397707be167fd27a23af0da133f7579f0/js/src/admin/components/ExtensionsWidget.js#L16-L43

**Some CSS selectors are overly specified**
Here's an example, `.ExtensionsList-Category` should be moved out of `.ExtensionsWidget-list` because it creates unnecessary over-specification. So when admins or theme designers try to override these styles (since there's no current mechanism of completely replacing a specific set of styles) they would have to overly specify even more, and that can become a mess.

https://github.com/flarum/core/blob/a2d5dd3397707be167fd27a23af0da133f7579f0/less/admin/ExtensionWidget.less#L6-L14

Another file with noticeable over-specification is `AdminPage.less`

**Leftovers**
I think we forgot to remove the AddExtensionModal and possibly its language strings?

**Comment by askvortsov1** [comment]
Moving this back to beta 16 milestone for everything except the first bit (completely refactoring Flarum's core config admin pages), which is still planned for 0.2
