### ISSUE TITLE
[Tags] Extension permission grids can be confusing

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2503]
One can see all the tag-specific permissions in an extension's permission grid even if there are no tag-specific permissions specific to that extension.

The problem with this is that the tag-specific feature is global and not per-extension. This is made confusing by the fact that you have an X to delete tag-specific permissions for a specific tag

_Permission grid of fof/drafts on Flarum Discuss_
![image](https://user-images.githubusercontent.com/6401250/102726269-64c03d00-42eb-11eb-9431-5b69742cf5a1.png)

Users may think this is specific to the extension they're currently in the page of and may delete ALL their tag-specific perms for that tag without meaning to.

**Comment by clarkwinkelmann** [comment]
I've also found a confusing counter-case.

If you *add* a new tag scope from the extension page, then you can't select anything in the dropdown because you first need to visit the permissions page to change the access to something different than admin under "View discussions" :roll_eyes: 

Step 1
![image](https://user-images.githubusercontent.com/5264300/105065079-c35d1000-5a7d-11eb-9967-41ca99b56aaa.png)
Step 2
![image](https://user-images.githubusercontent.com/5264300/105065100-c9eb8780-5a7d-11eb-941a-43dae7d4276e.png)

What I think we should do:

- Prevent creating or deleting scopes from extension page
- Add button saying "Configure scopes" or something that leads to Permissions page
- Hide the scope columns if none of the extension's permissions are scopable
