### ISSUE TITLE
Start new discussion without any tags

### ISSUE THREAD

**Issue by LianSheng197** [flarum/core#2510]
## Bug Report

**Current Behavior**
We can start a new discussion without any tags, it can bypass the setting of tags in forum.

**Steps to Reproduce**
1. Copy code from this file [[newDiscussionWithoutTags.js.txt](https://github.com/flarum/core/files/5740059/newDiscussionWithoutTags.js.txt)]
2. Run it in console.

**Screenshot**
![image](https://user-images.githubusercontent.com/18535495/103096793-1212b800-4640-11eb-813e-0a5ff9b551d6.png)

**Reference**
https://discuss.flarum.org/d/25754

**Comment by LianSheng197** [comment]
By the way, some people in other forums have reported that there will be no tags in PS4's built-in browser. (But I don’t have a PS4, I don’t know the details)
Therefore, I think having a default tag is better than rejecting it directly (such as 400 bad request).

**Comment by maomaru** [comment]
I think this issue is come from flarum/tags extensions 
in flarum/tags extensions's Listener -> SaveTagsToDatabase.php
it seems handle doesn't make sense by start a new discussion？
```php
public function handle(Saving $event)
    {
        $discussion = $event->discussion;
        $actor = $event->actor;

        // TODO: clean up, prevent discussion from being created without tags
        if (isset($event->data['relationships']['tags']['data'])) {
                ...
     }
```
this if statement doesn't has else to check isset($event->data['relationships']['tags']['data']) are false
in this case, $event->data['relationships']['tags']['data'] is null, 
and i know there have  // TODO: clean up, prevent discussion from being created without tags

but once actived flarum/tags extensions, api post request should pass here to check about tags data

my solution is add a new check discussion are new then let another if to check another thing,
and add elseif  statement to handle $event->data['relationships']['tags']['data'] are null. 
(i know elsestatement  can do same thing ..)

like this.
```php
public function handle(Saving $event)
    {
        $discussion = $event->discussion;
        $actor = $event->actor;

        // First, let's check  dicussion exists or not exists....
        if (! $discussion->exists) {
        // TODO: clean up, prevent discussion from being created without tags
        if (isset($event->data['relationships']['tags']['data'])) {
            if ($discussion->exists) {
                $actor->assertCan('tag', $discussion);
            }

            $linkage = (array) $event->data['relationships']['tags']['data'];
              //there's more...but cut it for better read ...
   } elseif (!isset($event->data['relationships']['tags']['data'])) {
            throw new ValidationException([], ['tags' => 'Some error message.']);
        }
        if ($primaryCount === 0 && $secondaryCount === 0 && ! $actor->hasPermission('startDiscussion')) {
            throw new PermissionDeniedException;
        }
    }
```

But because  i'm newbie of php,
i think maybe have more better solution can do.

By the way..
I want to apologize,
sorry for my english, and i don't know comment rules..
so if i'm look like rude, don't get me wrong.
Have a nice day.
