### ISSUE TITLE
JavaScript code is rendered while saving a new discussion title

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2619]
## Bug Report

**Current Behavior**

When editing the title of a discussion, while the saving is in progress, the title of the discussion beneath the modal becomes some JavaScript code.

https://user-images.githubusercontent.com/2164763/108609999-67fea480-73d2-11eb-93da-a44ce781e94e.mp4

**Steps to Reproduce**
1. Go to https://nightly.flarum.site/
2. Create a discussion
3. Rename the discussion title
4. Notice that while the new title is being saved, the title beneath the modal becomes some JavaScript code

**Environment**
- Flarum nightly

**Comment by Ralkage** [comment]
I can confirm this is also reproducible on https://beta.flarum.site which is on Beta 15 atm:

https://user-images.githubusercontent.com/2059356/109227509-6f390000-778e-11eb-8010-959c6adc1e86.mp4

**Comment by deebug** [comment]
I have a recording with a slight delay on when the issue occurs. Might be helpfull.

https://user-images.githubusercontent.com/4797720/110934155-f315ef00-832d-11eb-9495-74805059a02e.mp4

**Comment by datitisev** [comment]
I think this is because we're passing the Stream function instead of its value.

https://github.com/flarum/core/blob/0a6c5217c11e625aab5deec05bf6a6caf31bfa0d/js/src/forum/components/RenameDiscussionModal.js#L14

https://github.com/flarum/core/blob/0a6c5217c11e625aab5deec05bf6a6caf31bfa0d/js/src/forum/components/RenameDiscussionModal.js#L52-L60

Looks like the Mithril request automatically calls the function, but the Model value is temporarily set to the function and not its output.

The fix here, if I'm correct, would be to change `const title = this.newTitle;` to `const title = this.newTitle();`

**Comment by askvortsov1** [comment]
That fixes it for me locally. Could you open a PR?

**Comment by datitisev** [comment]
@askvortsov1 Done :)
