### ISSUE TITLE
[Flarum/Tags] TagsDiscussionModal - listing of child tags is unstable/bugged

### ISSUE THREAD

**Issue by dkzeb** [flarum/core#2658]
Listing of child tags in the TagsDiscussionModal seems bugged on beta-14.1

![bug](https://user-images.githubusercontent.com/7126560/109970954-f558c780-7cf5-11eb-9a74-79658ab43509.gif)

This happens when you are on a child tag and starting a new discussion - if you are not on a child tag when starting the discussion the child tag is never shown in the TagsDiscussionModal``

**Comment by datitisev** [comment]
Are you able to reproduce in https://nightly.flarum.site/ or https://beta.flarum.site? I seem to be able to view the child tags whether I open the Discussion composer in the child tag page or not.

**Comment by askvortsov1** [comment]
I am unable to replicate this too. Could you check your browser devtools console for errors? Also, what extensions are you using?

**Comment by askvortsov1** [comment]
If it's reproductible on 14.1 but not on 15, it probably got fixed accidentially somewhere in between. Since we're still in beta and there aren't massive incompatibilities for the extension API between b14.1 and b15, I think the likely solution if this is the case is recommending an upgrade to beta 15.
