### ISSUE TITLE
Implement translation on backend

### ISSUE THREAD

**Issue by tobscure** [flarum/core#267]
Currently all text output by the backend (validation messages, emails, etc.) is hardcoded in English.

What needs to be done:

* [x] Make the Translator class adhere to Symfony's Translator interface. This is so that it can be used with Laravel's validation component.
* [x] Add translations for Laravel's validation component messages.
* [x] Instantiate the Translator instance in LocaleServiceProvider using the actor's preferred locale.
* [x] Make emails translatable.

**Comment by franzliedke** [comment]
We also need to make the YAML parser resolve references, right?
Probably a good place for me to start adding some more unit tests.

**Comment by tobscure** [comment]
Yep, good idea. Though should we resolve the references in the YAML parser, or in the Translator (front + backend)? The former would be more DRY, the latter might save some bytes on the compiled JSON?

**Comment by franzliedke** [comment]
I think I'd like to have the references already resolved in the compiled version... so that means do it in the parser, right?
(And I think this makes sense, since it really is a feature of our specific YAML syntax).

**Comment by tobscure** [comment]
Yep ok, makes sense.

**Comment by tobscure** [comment]
@dcsjapan How's something like this for the email translation keys:

```
core:
  email_activate_account_subject: Activate Your New Account
  email_activate_account_body: |
    Someone (hopefully you!) has signed up to {forumTitle} with this email address.

    If this was you, simply click the following link and your account will be activated:
    {url}

    If you did not sign up, please ignore this email.
```

**Comment by franzliedke** [comment]
Hmm, we could also use per-language [templates for the mails](http://laravel.com/docs/5.1/mail#sending-mail). Since Laravel supports sending HTML mails with text fallback, that should make things easier, no?

**Comment by tobscure** [comment]
I don't think language packs have any business customising the template of an email, just as they don't have any business with the templates for the rest of the app. We should keep all translations together in the same format.

**Comment by franzliedke** [comment]
Okay, fair point.
Am 17.10.2015 11:45 vorm. schrieb "Toby Zerner" <notifications@github.com>:

**Comment by dcsjapan** [comment]
@tobscure Per-language templates probably wouldn't be necessary in any case, but if the mails are going to be sent as HTML (I think the subject was brought up in the forums at some point) we'll need to have some way of specifying the language and encoding.

As for the keys, I've been wondering about that a bit. Since we've got the `forum:` and `admin:` keys, perhaps an `email:` key would be another logical one to add.

**Comment by tobscure** [comment]
@dcsjapan Hmm interesting. Now that the plural syntax doesn't involve sub-keys, we could potentially use them to namespace chunks:

```
core:
  forum:
    change_password:
      send_button: Send Password Reset Email
      text: Click the button below and check your email for a link to change your password.
      title: => core.change_password
  email:
    activate_account:
      subject: Activate Your New Account
      body: | ...
```

What do you think?

**Comment by dcsjapan** [comment]
Yes, the very same idea (of using keys instead of prefixes) occurred to me while reading the Symfony docs you linked. We can still add the comments above the chunk keys to explain them more fully.

It won't make much difference to the length of keys as they appear in the JS, but I think it will make the YAML file much easier for translators to deal with.

**Comment by dcsjapan** [comment]
And some further thoughts on the subject:

If grammatical gender *won't* pose any problems, then I'd vote to do it this way. Removing the prefixes from the keys would make it possible to change how we describe the key structure in the i18n docs:

- What we've been calling the *suffix* could be called the *root*. That makes sense, because it is the only part of the key that is mandatory. The purpose of the root is to describe *how the string is used*.

- What we've been calling the *root* could be described as an optional *prefix*. The purpose of this prefix would be *to distinguish between multiple instances of the same root* (i.e., a `dismiss_button` versus a `submit_button`) *within the same sub-key*. 

This implies that *we don't really need prefixes at all* if the same root is not reused within the same sub-key. That is, if we've got a sub-key for a dialog box that contains nothing but a title, a text, a placeholder, and a button, there's really no reason to describe the strings further than that. If the translator wants a clue as to what the string *says*, well, he can just look at the string itself.

But if you're uncomfortable with the idea of making prefixes (formerly roots) completely optional, we can call them "optional but recommended".

The main point I want to make here is that by (1) turning our prefixes in to sub-keys and (2) talking about what's left in terms of *optional prefixes and mandatory roots* instead *optional roots and mandatory suffixes* we can make the i18n documentation a lot less confusing and easier for devs to follow.

**Comment by tobscure** [comment]
@dcsjapan I guess long plurals could be arranged vertically using YAML's `>` (folded block) syntax. e.g.

```yaml
key: >
  There is one potato
  |There are {count} potatoes
```

> Would we be forced to use sub-keys for gender, and if so, would that interfere with the idea of replacing prefixes with keys?

No it shouldn't interfere. I imagine gender will look something like this:

```yaml
core:
  forum:
    chunk:
      key1: hello world
      key2:
        male: hello mr. {name} 
        female: hello mrs. {name}
```

I agree, let's do it this way. All sounds good to me. When you have a chance, do you think you'd be able to put this into action?

**Comment by dcsjapan** [comment]
Sure! I'm trying to wrap up my translation mess at the moment. (Actually I've been hit by two acute jobs as well as the chronic one.) Once I've got that done (in perhaps a couple days or so) then I can get on it.
