### ISSUE TITLE
[Flags] Flagged post notification does not take you to post in long discussions

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2678]
## Bug Report

See https://github.com/flarum/QualityAssurance/issues/17

**Environment**
- Flarum version: dev-master
- Website URL: nightly
- Webserver: nginx
- Hosting environment: VPS
- PHP version: 8.0.2
- Browser: FF 68

**Steps to Reproduce:**
- Go to https://nightly.flarum.site
- Sign up as a mod
- Flag any of the last 10 posts in this discussion: https://nightly.flarum.site/d/41-henlo-waldo/2268
- Go back https://nightly.flarum.site by clicking on the "Flarum/nightly" logo text
- Click on the Flags notification icon
- Click on the post you flagged from the previously mentioned discussion.

Possibly related to https://github.com/flarum/core/issues/2404 with regards to the relationships issue.

**Comment by SychO9** [comment]
looks more like an issue with the post stream, https://nightly.flarum.site/d/41-henlo-waldo/2268 will take you to https://nightly.flarum.site/d/41-et-ipsam-et-et-et-nulla/2230 instead

**Comment by askvortsov1** [comment]
Much time has been spent here. The issue is thst fake data creates all posts at the same time, and we rely on sorting by created At (in the frontend, AND for retrieving posts in the backend). This doesn't pose an issue for a few posts made at the exact same time, but if there are dozens in a row (which isn't something that happens in real life, even in the biggest sites), it will glitch. I've sent a PR to fake data which would space posts out by a few seconds but there's some nuances to that too.
