### ISSUE TITLE
[Request/Inquiry] Flat vs. Threaded Structure

### ISSUE THREAD

**Issue by logannc** [flarum/core#272]
Is there any plans to support a Threaded (tree) forum structure?

If no, would you be opposed to contributions toward supporting that?

If no again, if I decided to fork y'alls ***awesome*** work for my own threaded ends, how hard is it gunna be to adapt it?

**Comment by tobscure** [comment]
No plans in core. I'd like for this to be possible via the Extension API though. It probably isn't at the moment, but I'd be happy to work towards it. Not an immediate priority though.

**Comment by logannc** [comment]
Awesome. I shall have to do some browsing of the code then! :)

**Comment by franzliedke** [comment]
We still don't have any plans to implement this in core, so I'm closing it.

@logannc We're pretty confident in our extension system. If you encounter any difficulties in making it work, we're very happy about your feedback and willing to make it easier for you. :)

**Comment by Dituar** [comment]
Reply chains are the most painful part of forums. To read all the related replies, you have to constantly click to display/jump to parent/reply replies, making it impossible to see everything at once, and sometimes figuring out who’s replying to which message.

For example, this post https://discuss.flarum.org/d/39448-flarum-200-rc4-released-audit-joins-core-20-stable-in-sight/14 . When you open it, you can’t immediately see which message it’s replying to (you have to hover mouse over “parent post”), the content of the replies (you have hover mouse over “XXX replied to this.”), or if there are more replies to this post and how many (you have to click “Jump to replied post”).

I’m a master of compromise :) and I came up with this compromise. The main display is a flat forum, but a post with parent/reply has a BUTTON that opens the ENTIRE chain of related posts in a new window, in a thread/tree view, in which this message will be in focus, but make it so that 10 nested / threaded are displayed without clicks (to do this, make the Topic width wider up to 50%. You could create a special wide theme (so that posts occupy 50-60% of the FHD-2K-4K screen width; currently, 30% is too little) for the  threaded view, so that frequent users can enable it. Or, even better, create two different themes for flat and tree views. Or 
clicking this button opens the ENTIRE chain of related posts, not in a new tab, but as a block on the right. And everything fits the screen width: on the left is a 10% navigation block, as it currently is, next to it is a 30% block of posts, as it currently is (can be increased to 40%), and on the right is a 50% block in which the nested/threaded ENTIRE chain of related posts will open. As an example, 10 nested fit normally in width [forum.opennet.ru - "У меня отжали 2 квартиры в Москве с помощью ЭЦП" (81)](https://www.opennet.ru/openforum/vsluhforumID10/5564.html#66) ; [Полная доказательная база аудита мессенджера MAX / Хабр](https://habr.com/ru/articles/1047490/#comment_30120786) ), if there are more than 10 nested, then “show more” Opens a new window from this point, but displays the two threads before this message and the eight threads after, etc., to avoid reducing the width. For mobile devices, make the 5 nested.)
This is especially useful in a thread with 1,000 posts when you search for a word, find a post, go to it, and it’s not clear which post the answer was to, and you have to click 10 more times to display the parent/reply link.
You can combine this BUTTON with the number of replies and the thread depth display, so it’s clear that the message is within a larger discussion even before opening it in a new tab.

This combines the advantages of a flat forum (easy reading of the entire thread) and a tree-based forum (the context of a specific reply is visible), without forcing the user to constantly click “go to message” and “show reply” links.
Let’s make forums more convenient than instant messengers and social networks to offer better usability and functionality!
