### ISSUE TITLE
[Feauture] Add textarea in extension settings

### ISSUE THREAD

**Issue by justoverclockl** [flarum/core#2809]
## Feature Request
Possibility to add "textarea" as a field on backend extensions settings.

**Comment by davwheat** [comment]
This is possible if you use a custom settings page instead of the settings helpers.

https://github.com/davwheat/flarum-ext-custom-sidenav-links/blob/3a42fc9d70e8472553efc03b10d31ece13ddcd65/js/src/admin/index.ts#L7

https://github.com/davwheat/flarum-ext-custom-sidenav-links/blob/main/js/src/admin/components/SettingsPage.tsx

**Comment by askvortsov1** [comment]
Well yeah, or if you use a callback-based setting. But we could support it under the "type" field fairly easily.

**Comment by davwheat** [comment]
Very true -- just stuck it there for reference until we add it into core.

**Comment by askvortsov1** [comment]
> ...also I never knew we supported callback-based settings see_no_evil

Needs docs

**Comment by justoverclockl** [comment]
Any chance to have this implemented? 😊

**Comment by SychO9** [comment]
`texteditor`could be nice indeed, but let's leave that for another time when the need for it with a use case actually arises and consider this done with the textarea addition.
