### ISSUE TITLE
[Mentions] Using mention autocomplete results in last quote being converted to a smart quote

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2879]
**This is a browser-specific bug for iOS Safari.**

The last `"` in a mention becomes a 'smart quote' when pressing ENTER, breaking the mention syntax.

**Steps to reproduce**
0. Use a browser testing tool to switch to Safari https://app.lambdatest.com/
1. Create a new post
2. Start mentioning someone via text `@tes`
3. Press TAB to accept a suggestion
4. Press ENTER to go to a new line
5. See that last `"` becomes a 'smart quote'

![image](https://user-images.githubusercontent.com/7406822/119403417-35688e80-bcd6-11eb-8b52-5185a2e419a8.png)

**Comment by askvortsov1** [comment]
Is this done by the client device / autocomplete, or by something in the code?

**Comment by davwheat** [comment]
This is the browser performing the change. Nothing in the code does it.

**Comment by askvortsov1** [comment]
> This is the browser performing the change. Nothing in the code does it.

Maybe we should just include smart quotes in the regex, but remove them on unparse?

**Comment by SychO9** [comment]
would using the unicode of the quote instead fix the issue ? (can't test this myself 😢) but that's what I seem to understand from some answers online.

`\u0022`

**Comment by luceos** [comment]
Usually this issue should have been closed because it does not adhere to the issue template. The issue template exists to ask for information that requires core team member, but also outside contributors, in providing a solution as it asks for steps to reproduce, version information etc.

This information has been asked privately from OP and as this is a pressing issue for our stable release we'll ignore bureaucracy for now.
