### ISSUE TITLE
Confirmation links are only valid once

### ISSUE THREAD

**Issue by haarp** [flarum/core#2969]
## Bug Report

**Current Behavior**
When an confirmation link has been opened once, subsequent attempts will result in an error such as "This confirmation link has already been used or is invalid.". This is still confusing to some users. Especially since some email clients such as Outlook Online will attempt to "preview" links by opening them (which is **utter insanity**, but that's another matter), so when the user eventually clicks the link, they will always see a (suspicious looking) error message.

**Steps to Reproduce**
1. Have email client that previews links (Outlook Online)
2. Start email verification
3. Click on link in mail
4. See error message in browser

**Environment**
- Flarum version: 1.0.4
- Browser: insane mail client

**Possible Solution(s)**
- Ideal: Nuke Microsoft datacenters and ban their decision-makers from ever working in the tech sector again
- If there's a way to format the mail in a way to stop previews, that would be best
- Two-step verification? Must open mail and click on a button
- Don't show an error message, redirect directly to forum

**Additional Context**
This could be considered a sequel of #1337 :)

Thanks!

**Comment by matteocontrini** [comment]
IMO the best solution would be to avoid automated requests having an effect.

Mailchimp has a clever implementation for unsubscribe links: they show a button on the unsubscribe web page, but the action is taken automatically with JavaScript if your user agent can run JavaScript.

**Comment by askvortsov1** [comment]
> IMO the best solution would be to avoid automated requests having an effect.
> 
> Mailchimp has a clever implementation for unsubscribe links: they show a button on the unsubscribe web page, but the action is taken automatically with JavaScript if your user agent can run JavaScript.

I would agree with this approach.

**Comment by haarp** [comment]
Turns out gmail is doing the same. Unbelievable. https://news.ycombinator.com/item?id=28240279

**Comment by tankerkiller125** [comment]
From a security perspective it's perfectly reasonable for Google and Microsoft to open links with their bots to scan for phishing attempts and spam automatically. In this day and age waiting for reports from people who got the emails is dangerous and can cause millions in damages.

Using a proper POST request is the correct way to go here. An important note though is that automatically submitting the form with JavaScript may not resolve the issue because some of these bots execute JavaScript (I know the Microsoft Exchange accounts with Advanced Threat Protection do).

**Comment by haarp** [comment]
Thansk a lot!
