### ISSUE TITLE
[Likes] Generalise to a "Rate" extension

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#306]
_From @tobscure on August 27, 2015 13:52_

I think it might be good to make this extension a bit more powerful, allowing people to configure the following:
- Optionally enable downvoting, giving each post a numeric score
- Customize the terminology used, e.g. "like", "agree", "+1"
- Customize the icon used, e.g. thumbs-up, heart, caret-up
- Think about the concept of reputation/karma
- Think about "reactions", like Facebook have recently added, and GitHub have just added to their comments
- Add an option to allow/disallow the liking of one's own posts

At the same time, we want to keep things reasonably simple. Discuss.

_Copied from original issue: flarum/likes#1_

**Comment by rodrigoargumedo** [comment]
Reputation system: it would be great if you take inspiration from Stack Exchange's approach. It makes easy to make posts interesting.

Thoughts on this?

**Comment by Luceos** [comment]
If you leave out the reputation/karma idea of your suggestions the criteria simple is still possible, I tend to believe however if you include that feature it will grow a little more complex. What if you split the reputation element into a separate feature and include all other listed features in the Like extension?

**Comment by KnownSyntax** [comment]
I think going for a slightly customized system would fit everyone's needs across the board. Having the default "like" system could stay, where the extension configuration of the admin panel can toggle to have the rating extension either show or hide the "dislike". Then, this can easily be turned to any text for the like/dislike, such that one can say +1, thumbs up, love it, etc. for the positive call or -1, thumbs down, dislike it, etc. for the negative call.

Maybe using font awesome icons for the available icons would work out best, that way the user could pick from a range of small icons to replace the thumbs up (as it currently is) into whatever they want. 

As for reputation, that could be the same. Have a system where the user can replace the text to whatever they want in the extension configuration of the admin panel (with the same ideas as before, having it limited to only positive, or both positive and negative calls).

**Comment by kirkbushell** [comment]
The great thing about an extension system, is you don't have to build something that fits everyone's needs - others can build it.

**Comment by jordanjay29** [comment]
As far as icons go, I like the system for choosing icons for groups at the moment. It has a finite amount of images, but they're pretty diverse and should accommodate most boards. I think they could also serve for icons for this feature, too. 

Instead of a specific +/- system, why not start with Like and allow admins to add other ratings. That would allow them to do something like a Thumbs, Heart, Smiley, Exclamation Point as ratings, or Like/Ambivalent/Dislike, or just plain +/- if they so choose. In this system, I envision ratings would have an ID, name, display icon (overwrites the name on display if present) and rating value (numerical, blank is disabled) in the database. The rating value could be displayed on profiles or disabled (so that ratings would only appear on posts with the value being held in the database somewhere but not actually in use). 

If this were to be built into the `core`, or as a built-in extension, that's how I'd do it.

**Comment by moutonnoireu** [comment]
I second the post writed by @jordanjay29 .

**Comment by tobscure** [comment]
Making a note to think about "reactions", like Facebook have recently added, and GitHub have just added to their comments

**Comment by franzliedke** [comment]
Great thinking! That's exactly what I thought about, too, when I saw that GitHub announcement. Though we could also create this as a separate extension...

**Comment by dav-is** [comment]
Perhaps we could use the github emojis and based on the positive or negative connotation of the emoji generate a user's karma/reputation.

**Comment by Cu8eR** [comment]
@dav-is - yes, that would be nice

**Comment by datitisev** [comment]
I started to develop a Reactions extension, but I sadly had to stop developing as I got another project to finish. It'd be nice for someone to try to continue developing, and then PR me the changes (everything works except for Flarum to show the reaction name in the relationship).
The last development is at [datitisev/flarum-ext-reactions#fixing-reactions-names](https://github.com/datitisev/flarum-ext-reactions/tree/fixing-reactions-names)

**Comment by Eldenroot** [comment]
Is there a working extension for this? If yes, close this one. Better to handle with extension.

**Comment by matteocontrini** [comment]
There's [FoF Reactions](https://discuss.flarum.org/d/20655-friendsofflarum-reactions).

**Comment by datitisev** [comment]
Yeah, I'm going to close this in favor of the third party extension by fof (previously reflar).

**Comment by Chealer** [comment]
@tobyzerner: Please clarify which extension you refer to.

@dsevillamartin: Please clarify how this was completed.

**Comment by dsevillamartin** [comment]
@Chealer Please do not bump old issues and ping old contributors. As mentioned two messages above yours, the third-party extension that adds reactions to posts is [FriendsOfFlarum Reactions](https://discuss.flarum.org/d/20655-friendsofflarum-reactions). 

This issue has not needed further discussion since it was closed almost six years ago - I don't see any reason to keep the conversation unlocked.
