### ISSUE TITLE
[Suspend] Give user a notification when they are suspended/unsuspended

### ISSUE THREAD

**Issue by tobscure** [flarum/core#322]
_From @tobscure on August 27, 2015 13:54_

What needs to be done:
- Create a "SuspendedBlueprint" notification blueprint.
- Sync that blueprint using the NotificationSyncer when a user is suspended/unsuspended.
- Create and register a component to render the notification on the front-end. It should display the amount of time remaining on the suspension.

_Copied from original issue: flarum/suspend#1_

**Comment by andypmw** [comment]
Hi, I am new to open source software contribution.
I am interested to do this task

**Comment by Luceos** [comment]
Hello @andypmw welcome to the community! In order to pick up this task you need to have a proper development environment. This issue is related to the suspend extension and as such all modification will probably be taking place in that repository. Fork that repository, set it up in a workbench or using franz liedkes' studio package. The official forums has a sticky written by myself on how to kickstart extension development, it's located under the tag "dev". Once set up let us know how you think you will approach the solution and we can give some pointers.
