### ISSUE TITLE
Title bugs

### ISSUE THREAD

**Issue by Yusaki-Akito** [flarum/core#3259]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Create some discussion include quot in the title "
2. Now you got it

**Expected Behavior**
Normal title 
Input: "welcome"
Output: "welcome" not &quot;welcome&quot;

**Screenshots**
https://imgur.com/hqbFO9h

**Comment by clarkwinkelmann** [comment]
The problem appears to be related to this change https://github.com/askvortsov1/rich-icu-message-formatter/commit/7d0a31c5d2dbdb605b8613ebfe2766a86991bddf

The characters `&<>"'` are replaced with HTML entities. But both Mithril and `document.title` are unable to deal with them.

The unit tests in `askvortsov/rich-icu-message-formatter` don't cover Mithril through `.rich()` and I'm not even sure where to add those tests in a way that makes sense. I'm really not sure why this change was made since it's only tested against a custom formatter implemented just for the tests.

**Comment by askvortsov1** [comment]
Opened https://github.com/askvortsov1/rich-icu-message-formatter/pull/1 to fix this, would appreciate review from @flarum/core before I merge, release, and bump core's deps in case there's anything I missed.
