### ISSUE TITLE
Chrome browser version 60 is not supported

### ISSUE THREAD

**Issue by li-xiansheng** [flarum/core#3296]
What should I do to support lower version browsers? I hope I can give some suggestions or opinions.

**Comment by tankerkiller125** [comment]
You can try adding the polyfill scripts using https://polyfill.io/v3/polyfill.min.js and see if that will correct anything. However it is likely that we are using much more modern features that polyfills can't fix.

Chrome 60's release was in 2017, during that time a huge amount has changed in terms of browser technology, JS, HTML, etc. it would be my recommendation at least to update the browser instead of trying to get Flarum working on it.

The Flarum team will most likely not attempt to make Flarum work on browsers that have been completely EOL for a very long time. We already face issues making sure that the most recent versions of browsers are all working correctly across a wide variety of devices.

**Comment by li-xiansheng** [comment]
@tankerkiller125 Thank you for your answer .I've tried to use your tankpolyfill dependency. The internal logic judges the low version of the browser and references it in the head“ https://polyfill.io/v3/polyfill.min.js ", but the browser version is too low and failed, so we discuss whether there is a better scheme here
