### ISSUE TITLE
[Likes] Newly registered users will not see the "Like" button 

### ISSUE THREAD

**Issue by modInfo** [flarum/core#344]
Only I, as the first user to see the Like button.
Newly registered users see only the "Reply" button.

**Comment by tobscure** [comment]
"Newly registered" as in guests, or other users who are logged in?

**Comment by modInfo** [comment]
Other users who are logged in dosent see the Like Button

**Comment by modInfo** [comment]
Update: Only Admins see the Like Button.

**Comment by tobscure** [comment]
OK, I think the problem is that there is no migration in the likes extension to set up the default permissions. Will look into a fix.

P.S. @modInfo if you find a problem like this, there's no need to post about it so much across the chat and forum. Once you've reported an issue, we *will* see it and make sure it's fixed – please just be patient. Creating extra noise about it on the chat and forum is unnecessary and annoying.
