### ISSUE TITLE
Multiple Language Support

### ISSUE THREAD

**Issue by Felli** [flarum/core#346]
After having more than one language extension installed it seems that you're not able to use more than one (Besides the default English.)

**Comment by tobscure** [comment]
From the [docs](http://flarum.org/docs/contributing/):

> If you find a bug, we’d like to know about it! Remember that the goal of a bug report is to make it easy for us to replicate the bug and develop a fix. Therefore, you should include as much relevant information as possible, and communicate it in a clear, factual way. [This article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is a great resource on how to report bugs effectively.

Please be more specific. Which language extensions are you using? What happens when you enable them both?

**Comment by Felli** [comment]
French & Russian are the two that I was using, but what was happening was an “Opps“ message would popup, and then I was stuck on the “Please wait...“ message till I refreshed.

**Comment by tobscure** [comment]
OK, thanks. This is because the French and Russian extensions appear to use the same namespace (`Qia`) because they have been created by non-developers before we've had a chance to properly document the language pack creation process.

In other words, this is not a bug with Flarum, just an impatient translator creating a broken extension.

**Comment by Felli** [comment]
Thanks for explaining this I was wondering what was going on. :smile:
