### ISSUE TITLE
[Tags] Ability to ignore a tag to hide it from All Discussions

### ISSUE THREAD

**Issue by maxyc** [flarum/core#370]
now i cant it?

**Comment by tobscure** [comment]
From the [docs](http://flarum.org/docs/contributing/):

> If you find a bug, we’d like to know about it! Remember that the goal of a bug report is to make it easy for us to replicate the bug and develop a fix. Therefore, you should include as much relevant information as possible, and communicate it in a clear, factual way. [This article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is a great resource on how to report bugs effectively.

Your bug reports are particularly unhelpful – please be more specific.

**Comment by tobscure** [comment]
OK, got it, thanks.

**Comment by DCSJAPAN** [comment]
Ever since [Luceos mentioned the concept of "favorite tags" in response to my mention of muting](https://github.com/flarum/core/issues/370) the idea has been nagging at me. It may well be a good idea to integrate this functionality into a "favorite tags" feature.

In fact, I think the concept of "favorites" is a much better fit for this functionality than that of "ignoring" because the user doesn't necessarily want to *ignore* discussions in a tag, he just doesn't want them shoved in his face all the time.

Here are some ideas for how it might work:

- Give the user a way to flag tags as "favorite" tags.
- Add a "Someone starts a discussion in a favorite tag" user setting under "Notifications".
 - Notification by alert would be on by default.
 - Would notification by email be needed? Maybe not; worth discussing.
- Add a "Favorites" user setting (slider toggle) to handle the muting aspect.
 - The description could read: "Display only favorite tags in All Discussions.
 - This setting would be OFF by default.
- Optional: give admins the ability to set default favorite tags for new users.

When the mute function is enabled, Flarum should provide some indication of which tags are being shown in the All Discussions list. I don't think non-favorite tags should be *removed* from the tag list on the left, because that would make it hard for people to view discussions in those tags. (Again, we're not really ignoring those tags, we just don't want to be told about them all the time.) But maybe it would be possible to change the tag icon a bit to indicate when a tag isn't included in the listing. For example:

![muted](https://cloud.githubusercontent.com/assets/13129997/9689521/9f04cb3a-5371-11e5-9e2f-8f1bfc495b31.png)

Adding a white hole in the center of the icon could be a good way to indicate that a tag is not included in the All Discussions list. But this variation of tag icons would not be necessary when the non-favorite muting function is disabled. Would that be workable?

Just a few ideas for you, please take or leave them as you wish. I thought I'd jot them down because it seemed like a constructive way to deal with insomnia. ;)

**Comment by dcsjapan** [comment]
Some further thoughts on this feature request:

Regardless of whether my idea of "favorites" idea is the right way to do it, I do think that we need to give users some way to decide which tags appear in the All Discussions view.

Currently that decision is made by the Admin for all users. The problem there is that an admin ends up imposing his own preferences on users. Take the Sandbox, for example. Certainly most users probably won't want to stay up-to-date with all the junk in there, but as a moderator I think I would rather be able to see those threads in the All Discussions view so that I can act on spam and such quickly. (As it is, I try to make periodic passes to check on the Sandbox, but when I'm busy those tend to fall by the wayside.)

So I think it would be better to allow users to choose which tags they want to ignore. And for cases like the Sandbox, where the admin feels most users will want to ignore a tag, it should be possible to set the ignore flag on that tag as the default setting for all new users.

**Comment by datitisev** [comment]
This can be done with third party extension fof/follow-tags, as it’s a feature I added to it. Does it implement this feature? If so, we can close it for the third party implementation.
