### ISSUE TITLE
[Tags] Ability to view a tag without sub-tags

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#394]
For example, it'd be nice to be able to list all discussions with the [Extensions tag](http://discuss.flarum.org/t/extensions) that don't have the Languages sub-tag.

Not sure how to do this in terms of UX though. Maybe when you click "Extensions" in the sidebar, have "none" as one of the options underneath? Or maybe a Shift-click modifier or something? Discuss.

**Comment by Mecvak** [comment]
A extension label at top, with a + then additional secondary tags?
Clicking on extensions behind the + would list only extension tagged.
Limitation of limited length + # of secondary tags
![alt](http://i.imgur.com/QdTjysd.png)

Another idea is clicking on a open arrow will only load the primary tag. I actually like this idea more since it doesn't involve clicking twice or requiring knowledge of keyboard short-cuts and is mobile friendly (go ahead and tell a phone user to shift click). Making it appear as you hover in pc clients would indicate this does something special. Plus, having it point to the extension itself indicates it deals with the extension - not as a starter to subtags.
![open arrow](http://i.imgur.com/9keJRHR.png)

**Comment by dcsjapan** [comment]
How necessary is it to have this available via the GUI?

If this wouldn't be used all that frequently, it could be handled via search gambits, e.g.:

+ Extensions, -AnyOtherTag
