### ISSUE TITLE
[Emoji] Use Emoji cheat sheet

### ISSUE THREAD

**Issue by tobscure** [flarum/core#397]
http://www.emoji-cheat-sheet.com

We can base our implementation on https://github.com/squarefractal/githubemoji-dokuwiki

Should have an autosuggest popup when you type `:`, like right here on GitHub. :100:

**Comment by sijad** [comment]
flarum/flarum-ext-emoji#3 gonna fix this but due to TextFormatter emoji plugin [emojiMap](https://github.com/sijad/flarum-ext-emoji/blob/emoji-cheat-sheet/js/forum/src/addComposerAutocomplete.js#L10) hard coded, it also can be done by a json file but I wasn't sure which way is better, also I think it's better to make a custom TextFormatter plugin to allow emoji cheat sheet map be in a global scope...

**Comment by tobscure** [comment]
Thanks for the PR! A few relevant points, though I haven't had time yet to do a full review of the PR:

1. We are planning to move to EmojiOne instead of Twemoji. #744

2. We need to discuss the move to server-side parsing of emoji as opposed to client-side. See https://discuss.flarum.org/d/271-text-formatting-in-flarum/41

3. As we implement yet another autocomplete dropdown, we may as well tackle #264

**Comment by sijad** [comment]
1- is fixed with sijad/flarum-ext-emoji@514baa058699d57e62c7f941620951266be0b4f6
2- I think it can be done latter, I just use textFormatter plugin so it still gonna work on back-end too
3- I'd love to work on this too, I just need more time
