### ISSUE TITLE
Ability to manually confirm a user's email address

### ISSUE THREAD

**Issue by OGKingFox** [flarum/core#414]
Someone mentioned not recieving emails for validation, and manual approval does not exist. Also needs ability to see members online, and possibly a public directory. Basically just needs full user management

**Comment by tobscure** [comment]
We'll make this ticket for implementing manual approval. The rest is covered in https://github.com/flarum/core/issues/283.

**Comment by renyuneyun** [comment]
So I've found the api/backend already contains such ability  -  just need to send PATCH request with data
`{
'data':
        {'attributes':
         {
             'isActivated':'true'
         }
        }
}` to `FORUM_URL/api/users/:userid` .

I tried to modify 'js/forum/src/components/EditUserModal.js' to add a 'activated' checkbox under the 'Email' section, but I have no idea how to reload the js in order to take effect.
In the beginning I though I need to follow `https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md` to recompile the js, but there is still no effect (or maybe I did something wrong).

How can I see the result after changing the js files?

By the way, what's the relationship between Mithril and ES6?

**Comment by dav-is** [comment]
> By the way, what's the relationship between Mithril and ES6?

Mithril at the time being doesn't use ES6. Flarum has ES6 classes to make use of mithril. Then all the rest of Flarum builds on these classes. Does this make sense?

**Comment by renyuneyun** [comment]
Yes.
So the transpiling step is to change ES6 to a lower version (e.g. ES5?) to let it run correctly on current browsers/tools/environment?

Wouldn't the modified JS be then downloaded by the browser (after refreshing the page) after transpiling? Or are there other steps needed?

**Comment by renyuneyun** [comment]
OK, I found that if I set `'debug' => true` in `config.php`, the changes will take effect.
But... Why?

**Comment by dav-is** [comment]
There should a compile.sh that you'll want to run in the core files. Be sure not to commit the compiled app.js files.
