### ISSUE TITLE
Can't make/edit tags 

### ISSUE THREAD

**Issue by Azuraxe** [flarum/core#436]
Hey,
I am getting now output but I am unable to create tags and or edit current ones!

https://drive.google.com/file/d/0B0ULn7OJZtpgc1lUSHpJODh2Rnc/view?usp=drivesdk

I also believe that editing posts doesn't work.

Thanks!

**Comment by franzliedke** [comment]
We need way more details to help you. :)

Please follow the [troubleshooting instructions](http://flarum.org/docs/troubleshooting/).

**Comment by AlexL777** [comment]
Hello Developers,
I feel like with the tags. I could only rename a single tag and I can not create new. It always comes back the same error message like this:


    Oops! Something went wrong on the server. Please reload the page and try again

I can also make any settings in the tags - comes this error message. On the whole, I have this error message anywhere in the backend. Does anyone know what it may be because.

It seems to be so that I am not alone with the error :)

Thanks in advance.

P.S. I use PHP 5.6, the latest version of Flarum and the last mySQL version

**Comment by franzliedke** [comment]
The page I linked to contains information on how you find more information about this error.

Please provide those, otherwise we cannot help you.

**Comment by AlexL777** [comment]
Now I have found the error with the Firefox Inspector:

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead  create the object with the correct initial [[Prototype]] value using Object.create

But I do not understand what that means. Can you use this?

**Comment by franzliedke** [comment]
I'm fairly sure that's just a warning and not an actual error. Are you sure there's no other error message?

**Comment by AlexL777** [comment]
Now I have seen with Google Chrome and discovered this error. It is said that a file or directory can not be called, but I did it. Even on the server

/api/config I can not find me.

    http://flarum.wpzweinull.ch/favicon.ico Failed to load resource: the server responded with a status of 500 (Internal Server Error)
    http://flarum.wpzweinull.ch/api/config Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tobscure** [comment]
Almost there. Please follow the instructions in the troubleshooting docs (linked in Franz's first comment) to inspect the response of the failing request to http://flarum.wpzweinull.ch/api/config.

**Comment by samymassoud** [comment]
I know what this is,

IF you need to Creat Tag, First time tick ("Hide from All Discussions"),and after saving edit it and remove this tick.

The problem is server return 500 Internal error first time, because of 
`Incorrect integer value: '' for column 'is_hidden'`

The default value need to be fixed,so please make this a Bug for schedule fixing.

**Comment by tobscure** [comment]
Ah, this is already fixed for beta 2.
