### ISSUE TITLE
JavaScript style guide

### ISSUE THREAD

**Issue by tobscure** [flarum/core#44]
- [x] Decide on style guide ([this one](https://github.com/airbnb/javascript) seems reasonable)
- [x] Implement code sniffer
- [x] Clean up existing code

**Comment by engleek** [comment]
The Airbnb style guide is pretty clean and fair.

They've even published [linter configuration files](https://github.com/airbnb/javascript/tree/master/linters) although they don't have an ES6 version for ESLint.

They have an [updated version](https://github.com/airbnb/javascript/tree/es6) for ES6, which is a nice touch because Ember.js also [has a guide](https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md) which mentions ES6.

As for cleaning up code, the most popular Atom package is based on [js-beautifier](https://github.com/beautify-web/js-beautify), which works well.

**Comment by tobscure** [comment]
More or less done.
