### ISSUE TITLE
Scroll to show composer preview by default

### ISSUE THREAD

**Issue by tobscure** [flarum/core#450]
More convenient to just show it right away. This will allow us to get rid of the preview button as well.

**Comment by Mecvak** [comment]
This is a good idea. However, don't remove the preview button. I use it to navigate around the forum and reply to posts on other discussions and continue writing. Eventually when I want to return to see my post I hit the preview as a method of "returning home". Otherwise I'd have to manually find it or just hope I did the syntax correctly.

**Comment by tobscure** [comment]
Good thinking.

**Comment by tobscure** [comment]
Fixed in 603537c3d11b2b8c6971d5fe5feef8c4da205f97
