### ISSUE TITLE
is:unread gambit not working

### ISSUE THREAD

**Issue by tobscure** [flarum/core#485]

**Comment by Luceos** [comment]
@franzliedke or @tobscure just to make sure i understand the logic:
https://github.com/flarum/core/blob/master/src/Core/Discussions/Search/Gambits/UnreadGambit.php#L55

From what I can interpret, the problem lies with the fact that the $actor->read_time is very decisive. From my table I see this column remains `null`; can you verify this in the live database?

**Comment by tobscure** [comment]
Looked into it, turns out it was some bad logic in DiscussionRepository::getReadIds().
