### ISSUE TITLE
Password reset was denied

### ISSUE THREAD

**Issue by ftiasch** [flarum/core#486]
Debug was trapped in `flarum/vendor/flarum/core/src/Core/Support/Locked.php:50`. It seems the permission was not set correctly.

**Comment by franzliedke** [comment]
Please review our [contribution guidelines](http://flarum.org/docs/contributing/), especially the section about how to report bugs. :)

We need some more details here: What exactly did you do? What happened vs. what did you expect to happen? And also, the full stack trace would be helpful (rather than just this one line).

Please help us help you.

**Comment by ftiasch** [comment]
1. I clicked `reset password`, and received an email containing reset link.
2. Enter new pass via the reset link, then the server responded me with error code 500.

I retried the above process with an admin account. This time the password was successfully changed. 

Debug logs also suggests the error is related of user permission.

**Comment by Luceos** [comment]
> Debug logs also suggests the error is related of user permission.

Please post the debug log, we need it to find the code that does this. Thank you for posting, please add this so we can resolve it with ease.

**Comment by tobscure** [comment]
I believe this has been fixed for beta 3
