### ISSUE TITLE
Setting open_basedir can cause installation problems

### ISSUE THREAD

**Issue by pauljherring** [flarum/core#487]
Example situation:

Whole domain present at: /var/www/vhosts/example.com/httpdocs and served as http://example.com
Subdomain present in subdirectory at /var/www/vhosts/example.com/flarum and served as http://flarum.example.com

php.ini set to have the parent directory open:
`open_basedir=/var/www/vhosts/example.com/:/tmp`

Installation to /var/www/vhosts/example.com/flarum fails - in the instance experienced - around 
…/­vendor/­s9e/­text-formatter/­src/­Plugins/­BBCodes/­Configurator/­Repository.php30

See http://discuss.flarum.org/d/977-invalid-repository-file for discovery process.

**Comment by logixtreeCode** [comment]
Faced the same problem. 
Problematic file : /vendor/flarum/core/src/Frontend/Compiler/JsCompiler.php
You can simply adjust the sys_get_temp_dir() to getcwd();. Since we are simply creating a temporary file then deleting it. It won't cause any harm. Here is the adjusted code. 
 
```
        // Add a comment to the end of our file to point to the sourcemap
        // we just constructed. We will then write the JS file, save the
        // map to a temporary location, and then move it to the asset dir.
        $output[] = '//# sourceMappingURL='.$this->assetsDir->url($mapFile);

        $this->assetsDir->put($file, implode("\n", $output));
        $mapTemp = tempnam(getcwd(), $mapFile);
        //print_r($mapTemp);die;
        $map->save($mapTemp);
        $this->assetsDir->put($mapFile, file_get_contents($mapTemp));
        @unlink($mapTemp);

        return true;
```

In my case, I had the open_basedir setup perfectly but php was not picking up the local values. But above case sorted out the concern. 

Regards,
Team LogixTree

**Comment by luceos** [comment]
Fixed in https://github.com/flarum/core/commit/54660ebd6311f9ea142f1b573263d0d907400786
