### ISSUE TITLE
Changing password : the window does not adapt to text

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#494]
When I change my password, the window that proposes to send a mail don't adapt its size to the text.
![capture-reglages - flarumfr communaute francophone - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9886793/71ae4f02-5bec-11e5-9705-110d23d30abd.png)

**Comment by franzliedke** [comment]
Hmm, I cannot reproduce this in Firefox and Chrome... instead the content is truncated with an ellipsis at the end.

Given that the modal is a "small" modal that has a maximum width, that seems to be the expected behavior, although I guess one could certainly argue to have it expand to a certain width.

@Petrouchka Two questions:

* Can you still reproduce this?
* Is there no shorter way to translate this button label?

**Comment by franzliedke** [comment]
Looks like Toby added the ellipsis thing in https://github.com/flarum/core/commit/dfef3c1ff196db7c96653472ffd6622ea94bf674.

I'll consider this done.

**Comment by franzliedke** [comment]
@tobscure Hmm, maybe a small thing we can improve here: As it sometimes can happen that a [Button element](https://github.com/flarum/core/blob/eb76767e7098a373445fb5820b8a2597868cd7fe/js/lib/components/Button.js) has overflowing title like in this case - how about we add its label as a `title` attribute? The only problem I see: the content can be nested HTML, too? Is there some easy way in Mithril to get just the text content?

**Comment by tobscure** [comment]
@franzliedke use the [extractText util](https://github.com/flarum/core/blob/master/js/lib/utils/extractText.js) :)

**Comment by franzliedke** [comment]
Thanks for the tip, did that now.
