### ISSUE TITLE
No migration for forum model

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#51]
This causes the topic loading on the index page to fail. Crazy hard to debug. The error happens somewhere in the `DiscussionSearcher` class.

**Comment by tobscure** [comment]
I had this the other day, and yes it was difficult to debug, sorry you had to go through it :P

This is caused by a bug in `tobscure/permissible`, fixed the other day: https://github.com/tobscure/permissible/commit/ac146ee44be5b2c4b99ad065e2cdcd51de1f7860 So just `composer update` and you should be right. (There isn't meant to be any forum migration/table — the forum permission closure returns a boolean so the forum model shouldn't be queried.)
