### ISSUE TITLE
Add gzip/caching directives to .htaccess and nginx configuration

### ISSUE THREAD

**Issue by tobscure** [flarum/core#514]
Something like:

```
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/plain text/css text/xml text/html text/javascript application/javascript application/x-javascript application/xml application/json application/vnd.api+json
  BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
</IfModule>

<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresDefault "access plus 1 seconds"
  ExpiresByType image/gif "access plus 2678400 seconds"
  ExpiresByType image/jpeg "access plus 2678400 seconds"
  ExpiresByType image/png "access plus 2678400 seconds"
  ExpiresByType text/css "access plus 2678400 seconds"
  ExpiresByType text/javascript "access plus 2678400 seconds"
  ExpiresByType application/x-javascript "access plus 2678400 seconds"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\.(ico|flv|jpg|jpeg|png|gif|css|swf|js)$">
    Header set Cache-Control "max-age=2678400, public"
  </FilesMatch>
</IfModule>
```

Thought it would be worth opening this up for discussion before adding though, because I don't know much about Apache config!

**Comment by franzliedke** [comment]
:+1:

I can take a look at this as part of flarum/issue-archive#390.

**Comment by Mecvak** [comment]
Having devs help write the config means it's going to be pretty optimal since you know the backend and know what opportunities (like caching) you can give the webserver.

However, the installation guide should be **basic** installation. You really don't want to be debugging through various modules when you don't even know if the basic set up is correct.
Plus, by suggesting modifying modules, you're now modifying other sites they may be running and opens up the risk of "I installed flarum and now buggy php program X stopped working! Flarum broke it!" etc etc.


Instead, maybe start a "Optimize Flarum" or some such page where users have a running flarum install that works and want it *faster*. 
For example, I dropped page responses from ~260ms to ~180ms by utilizing php5-fpm's op-cache which is pretty sweet. But I wouldn't suggest it for someone who's definition of "configuring" is copying and pasting the [install guide](http://flarum.org/docs/installation/) config.

My 2c

**Comment by franzliedke** [comment]
Currently working on adapting the rules from [here](https://github.com/phanan/htaccess#performance). :)

**Comment by franzliedke** [comment]
Can someone review this on Apache? Nginx works fine for me...

**Comment by phodal** [comment]
@franzliedke Today I do some config with Nginx, it seems the API don't have compress. And I compare the config between Nginx and Apache, I found in Nginx config lost one ``gzip_types`` which is ``application/vnd.api+json``.

**Comment by franzliedke** [comment]
@phodal I don't see `application/vnd.api+json` in our [Apache config](https://github.com/flarum/flarum/blob/569e3a3b5ec862ecae93e0e438dd6a7a4c5012ed/.htaccess).

I jut added one line that was forgotten in the Nginx config, though, thanks for the heads-up.
