### ISSUE TITLE
moment.js: "a day ago"

### ISSUE THREAD

**Issue by amdad** [flarum/core#524]
Very low priority but, 
Instead "a day ago" In this case moment.js should use  
```js
       calendar : {
            lastDay : '[Yesterday at] LT',
```
So instead Relative Time use Calendar Time. Don't know if it can be configured by moment.js or it need to be changed in flarum part.

```javascript
 calendar : {
            sameDay : '[Today at] LT',
            nextDay : '[Tomorrow at] LT',
            nextWeek : 'dddd [at] LT',
            lastDay : '[Yesterday at] LT',
            lastWeek : '[Last] dddd [at] LT',
            sameElse : 'L'
        },
        relativeTime : {
            future : 'in %s',
            past : '%s ago',
            s : 'a few seconds',
            m : 'a minute',
            mm : '%d minutes',
            h : 'an hour',
            hh : '%d hours',
            d : 'a day',
            dd : '%d days',
            M : 'a month',
            MM : '%d months',
            y : 'a year',
            yy : '%d years'
        },
 ```

In some cases Calendar style is much better to read and more precise when it comes to close dates 
(LT = HH:mm) so we get more info.

**Comment by franzliedke** [comment]
Possibly related: In German, we basically can not say "Registered March 26nd, 2015", it needs to be "Registered **on** March 26nd, 2015". That preprosition is unfortunately not included because it's not needed in combination with things like "Registered two days ago" (the German translation for "two days ago" already contains the preprosition that's needed).

/cc @Dominion

**Comment by amdad** [comment]
Franz, this issue was not meant to be about this kind of problem. Because even in English you didn't say: "a day ago" or even worse "a 1 day ago". Rather just "yesterday". Since both are correct, a still "Yesterday at 22:38" is much more informative and natural. Additionally if date is so near, then giving hour time have more sense. 

The same way as we don't write 7 days ago, but week ago. Or instead 34 days ago, month ago.

**Comment by dcsjapan** [comment]
@franzliedke Didn't get your CC because I'm "dcsjapan" here. ;)

As @amdad says it's not high priority, but I would like a chance to review how moment.js works at some point down the road. The prepositions issue you mention will come into play, as will the choice between an "ago" expression and a "calendar" expression.

**Comment by dcsjapan** [comment]
The use of relative time makes it easier for the user to see how fresh the item is, which in many cases is more important than the exact time it transpired. It's not ideal in some cases, but making exceptions in only a few cases would add complexity and reduce consistency.

So, we'll be sticking with the relative time.

**Comment by laukstein** [comment]
I wouldn't consider it as a low priority bug.
Really there are no way `moment(moment().add(-23, 'h')).fromNow()` to return **Yesterday at 9:39 AM** (keep in mind that **Yesterday** is before the last midnight, not between 24 hours and 48 hours ago).

@tobscure, please reconsider to open this issue, flarum/issue-archive#372 isn't related to this issue title.
