### ISSUE TITLE
Create a whitelist for popular email provider weblinks

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#541]
Seeing problems like #62, #480 and #481, we may want to consider only showing the email provider link to emails where we definitely know it works (GMail, Yahoo, Hotmail/Outlook...).

If we have a list of, say, the 10 most popular email providers, we still have a ton of people enjoying this nice touch, but don't confusion with others where we don't know whether our assumption holds...

**Comment by Fastidious** [comment]
@franzliedke as I commented on one of those tickets :-) : 

> "Popular email providers will not cut it. It should not link to the domain of the email, it should simply redirect to forum root, after telling the user to check for email. Many users will have their own domain, corporate emails, etc., and it will not be possible to account for all."

**Comment by franzliedke** [comment]
Of course we can't do it for all. For those where we cannot be sure, I'm suggesting to simply show no link.

**Comment by Petrouchka** [comment]
France :
https://zimbra.free.fr (for people who choosed to use Zimbra) or https://imp.free.fr (normal mailbox)
https://webmail.orange.fr
https://webmail.extra.laposte.fr or https://compte.laposte.net/authentication/login.do?page=webmail
https://messagerie.sfr.fr or https://webmail.sfr.fr
http://webmail.aliceadsl.fr
https://webmail.numericable.fr
https://www.mon-compte.bouyguestelecom.fr
https://www.netcourrier.com
https://webmail.nerim.net
https://webmail.nfrance.com
https://www.nordnet.com/messagerie
https://webmail.fdn.fr

Others : https://fr.wikipedia.org/wiki/Liste_de_fournisseurs_d'acc%C3%A8s_%C3%A0_Internet_pour_particuliers

Should add a link in Flarum to let possibility to add/delete/modify theses links somewhere because the list will change a lot of times.

**Comment by Fastidious** [comment]
The list is close to impossible to maintain, and it will be huge. Simply stating "check your mail to finish your account... etc." should be fine. Having the button with "OK" to return back to forum root (or perhaps to login screen) sounds acceptable [to me].

**Comment by franzliedke** [comment]
It doesn't have to be huge. The idea is to cover many people with just a few (max. 10) providers. But maybe I'm wrong and that would only list good results in the Western world...

**Comment by tobscure** [comment]
> that would only list good results in the Western world

I guess that's still OK though, at least some users will get the benefit rather than no one! I don't think it's worth the extra complexity to make this list long/configurable though.

How about we just use this list? http://www.thewindowsclub.com/commonly-used-email-addresses

**Comment by Petrouchka** [comment]
The idea is good but even with most common providers, the webmail address can change or the name of the provider can change (Google->Alphabet) or the provider can be sold. If you don't add a way for each user to suggest corrections or new names, the list will be obsolete in one or two years.

**Comment by franzliedke** [comment]
I'm pretty sure the ones on the list Toby posted haven't changed in a long time. Why should they? Users are interested in keeping their email address...

**Comment by Petrouchka** [comment]
About this list :
With Google Apps for Business, each organization has its own domain.
mail.com, inbox.com, zoho.com, thewindowsclub.com are not very know in the world and they could disappear or change their name.
I'm not sure aol.com is still used a lot and it will disappear one day like so many others.
If you add a list (and it's a good idea) but don't add a way for each user to modify it, your work will be lost in a few years.

**Comment by Mecvak** [comment]
I think predicting the small bases like this is a nice touch - but I also feel like it's a high investment, low yield kind of thing.

* When told to go confirm their email, the users will probably remember what email they just used
* The user probably has a far more efficient method of quickly accessing their email then attempting to guess what that is.

I mean, a user might already have it open, another might use a client and another might have email open on their phone and simply use that to activate it.

Flarum feels far too... modular to limit itself by hard coding in some white-listed domains.
Why not leave it up to the user in the admin area? If they list a domain, it'll provide a link to that domain and otherwise no.

**Comment by zaksoup** [comment]
I'm definitely in agreement with @mecvak. If this feature survives at all it should definitely be in the form of a whitelist managed by the admins. I feel like this feature will only be a convenience in the rare case when the user doesn't already have their email open in a different tab. Between push notifications to chrome if you're signed into gmail or your tablet/phone/desktop client I'm honestly not sure that this feature will benefit any reasonable number of users whose emails have a web client.

**Comment by franzliedke** [comment]
Hmm, it's becoming harder and harder to justify this. :-/

Unless you're very fond of it, @tobscure, I'd just vote to drop this feature at this point. It's too hard to maintain (and judge *what* to maintain), combined with lots of opportunity for confusion.
I like the thought behind it; but we can keep such niceties in mind, and I'm sure we'll find other places where stuff like this is even more helpful.

**Comment by tobscure** [comment]
@franzliedke Well said. I've replaced all instances of these "go to email provider" buttons with simple "OK" buttons.

**Comment by dcsjapan** [comment]
Back to dismiss buttons then?

Okay, noting it in my reference YAML so I can mention it in the i18n docs.
