### ISSUE TITLE
Use Global Pluralization (Plural Rules)

### ISSUE THREAD

**Issue by maelsoucaze** [flarum/core#550]
The current system requires that the translator have some PHP and JS skills to add the plural rule for its language. I think we want to avoid that. We should include a global pluralization which includes all those rules. It can be done by including them by default in the skeleton. It can scan the locale code to apply the specified rule, or, if you want to avoid that code, ask the translator to specifiy a rule (there are 16 in total). See those useful ressources to work with:
- http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html
- https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals
- http://formatjs.io/guides/message-syntax/#plural-format
- http://l10ns.org/docs.html#pluralformat

**Comment by dcsjapan** [comment]
This would make it easier for translators to create a language pack, since (in most cases) setting the locale code will automatically make the proper pluralization rules available.

It would also make the docs much simpler, because instead of explaining how to define pluralization rules, we can simply list the options and give a couple examples, e.g.:

- In English you can use "one" and "other"
- In Polish you can use "one", "few", and "other"

And then point the reader at the unicode.org chart for further details.

**Comment by dcsjapan** [comment]
I've taken the liberty of starting [this thread](http://discuss.flarum.org/d/1163-a-unified-approach-to-simpler-localization) so we can discuss this issue in combination with #551.

**Comment by maelsoucaze** [comment]
Closed with https://github.com/flarum/english/commit/dae5008162dc9af94d64c6188d418a5f01a814a3
