### ISSUE TITLE
Sign Up action is not going through

### ISSUE THREAD

**Issue by aishwarya85** [flarum/core#589]
After installing flarum in demo site when I tried to signup in that, I was unable to get mail for confirmation so for that I tried to signup for flarum main website to get solution for this but and same issue. Here also didn't received the mail for confirmation so what should I do to resolve issue?

**Comment by Luceos** [comment]
Did you set the mail settings in your database?

**Comment by aishwarya85** [comment]
yes i did
ᐧ

**Comment by Luceos** [comment]
@aishwarya85 you already signed up with the e-mail address. Something went wrong there, I'm not sure it's flarum-based. Also you can't sign up with that e-mail address anymore, because it's already known to a user. You'll have to reset your pass, sadly on the discuss.flarum.org forum this is broken because the ajax request is a 404.

**Comment by aishwarya85** [comment]
so what should I do for this issue?

**Comment by Luceos** [comment]
Reset password should be fixed in the latest master. Please wait for the next beta. Discuss.flarum.org will be updated soon. In the meantime you might try signing up with a `+flarum@` in your emailaddress, for instance: `my+flarum@gmail.com`

**Comment by Luceos** [comment]
Is your issue still valid, please re-open if so.
