### ISSUE TITLE
[Tags] Tag order does not save (drag and drop)

### ISSUE THREAD

**Issue by Code-Name-Debian** [flarum/core#614]
In this screenshot, you will see that I'm trying to move a tag.  Now matter where I drag that, it will always go back to where it started.

![capture](https://cloud.githubusercontent.com/assets/7545839/10805220/841980ee-7da2-11e5-8245-b586f361436f.JPG)

**Comment by tobscure** [comment]
@Code-Name-Debian Are you still having this issue? What browser are you using?

**Comment by Averell7** [comment]
I confirm that this part is really buggy. It is sometimes very difficult to place a tag where you want. Even when carefully positioned with the mouse (the grey rectangle shows where it should go), everything may happen :
* works (fortunately)
* Go back to last position
* Stay primary when you placed it as secondary
* or the opposite. 

I had once to reorder by changing the numbers directly in the database. 

The bug is random and not easily reproduced

**Comment by tobscure** [comment]
@Averell7 what browser are you using?

**Comment by Averell7** [comment]
Firefox 43

**Comment by franzliedke** [comment]
I am closing this issue as it seems to have grown stale. If you still encounter this problem with the latest version, please feel free to re-open it.

Please understand that outdated issues are closed regularly to keep the amount of open issues to a manageable minimum. In any case, thanks for taking an interest in this software and opening the issue in the first place!
