### ISSUE TITLE
After registration: make link to email provider open in new tab

### ISSUE THREAD

**Issue by megamorf** [flarum/core#62]
This small change would improve the user experience :-)

**Comment by megamorf** [comment]
Added my PR: https://github.com/flarum/core/pull/63

**Comment by tobscure** [comment]
Thanks for bringing this up! I'm not going to merge just yet because I did actually have a reason behind this behaviour.

After you sign up, the next step is to go and click on the link in the confirmation email. If you open up your email in a new tab, then click the link, you get another new tab with the forum logged in to your new account (and the goal is to have it bring you back to the exact place you were at before you signed up). So the original forum tab is made redundant, and you'd probably just end up closing it anyway.

I thought that instead, we could just take people straight to their email in the same tab, and then they would return to the forum (and their saved place) via the confirmation link. Maybe then it needs to be made more clear that we will save their place. What do you think?

**Comment by megamorf** [comment]
Well, I see your point of having a redundant browser tab when the link opens a new tab. I personally don't like the feeling of losing control of my internet browser though. I'd be more content with having to close a tab even though functionality-wise it's the same end result.

I suggest asking more people for input.

**Comment by tobscure** [comment]
OK, I see where you're coming from. Good idea, will leave this open for now.

**Comment by franzliedke** [comment]
I'd probably lean more on @megamorf's side.

**Comment by SolidOrphan** [comment]
I use Thunderbird for my emails so I don't have a need with this suggestion.
