### ISSUE TITLE
[Mentions] mentioned_by_self_text is not correctly used

### ISSUE THREAD

**Issue by ghost** [flarum/core#621]
When you replied to a message, the string [mentioned_by_self_text](https://github.com/flarum/english/blob/master/locale/flarum-mentions.yml#L23) is supposed to be used, but actually, [mentioned_by_text](https://github.com/flarum/english/blob/master/locale/flarum-mentions.yml#L22) is used. It's an issue because in French, we say _Toby a répondu à ça_ (_Toby replied to this_) when it's someone different than you, but we use _Vous avez répondu à ça_ (_You replied to this_) when it's yourself. Now, _Vous a répondu à ça_ is shown, but that's wrong.

**Comment by dcsjapan** [comment]
Here is the relevant bit of code, from AddMentionedByList.js (in the Mentions extension):

```
      items.add('replies',
        <div className="Post-mentionedBy" config={config}>
          <span className="Post-mentionedBy-summary">
            {icon('reply')}
            {app.translator.transChoice('flarum-mentions.forum.post.mentioned_by' + (replies[0] === app.session.user ? '_self' : '') + '_text', names.length, {
              count: names.length,
              users: punctuateSeries(names)
            })}
          </span>
        </div>
```

It seems the parenthesized bit in the middle of the `app.translator` call that's supposed to add the `_self` segment isn't working for some reason.

@maelsoucaze The Likes extension uses very similar coding ... do you see the same thing happening with likes in French?

**Comment by maelsoucaze** [comment]
### Mentions Extension

#### Text used in a post

- When I replied to a post, and I'm alone to reply, it's **NOT** correct: *Vous a répondu à ça*. It should be *Vous avez répondu à ça*.
- When someone replied to a post, and he's alone to reply, it's correct: *Toby a répondu à ça*.
- When I replied to a post with several people, it's **NOT** correct: *Luceos, Dominion et Vous ont répondu à ça*. It should be *Luceos, Dominion et Vous avez répondu à ça*.
- When several people like a post, it's correct: *Luceos, Dominion et Toby ont répondu à ça*.

#### Text used in the notification center

Also, I saw that the notification behavior is also wrong:
- When someone replied to a post, it shows me in the notification center *Dominion ont répondu à votre message*, but it should be *Dominion a répondu à votre message*, because he's alone to reply to it.

### Likes Extension

#### Text used in a post

- When I like a post, and I'm alone to like it, it's correct: *Vous aimez ça*.
- When someone like a post, and he's alone to like it, it's correct: *Toby aime ça*.
- When I like a post with several people, it's **NOT** correct: *Vous, Dominion et Toby aiment ça*. It should be *Vous, Dominion et Toby aimez ça*.
- When several people like a post, it's correct: *Luceos, Dominion et Toby aiment ça*.

#### Text used in the notification center

Also, I saw that the notification behavior is also wrong:
- When someone like a post, it shows me in the notification center *Dominion ont aimé votre message*, but it should be *Dominion a aimé votre message*, because he's alone to like it.

**Comment by maelsoucaze** [comment]
Also, I noticied another stuff: when someone like or reply to a content, and then I like or reply to it, it shows me *Dominion and You...*. That's not correct in French because of the capitalization. Is it possible to change it to put *You* always in front of other usernames? Like *Vous and Dominion...*, *Vous, Dominion and Toby...*, etc.

**Comment by maelsoucaze** [comment]
Another stuff noticied: In the notification center, if we pluralize [this line](https://github.com/flarum/english/blob/master/locale/flarum-likes.yml#L19) and [this line](https://github.com/flarum/english/blob/master/locale/flarum-mentions.yml#L16), it doesn't have the correct behavior. It shows the plural, *Toby aiment votre message* or *Toby ont répondu à votre message*, when it should be the singular, *Toby a aimé votre message* or *Toby a répondu à votre message*.

I don't know if it's necessary to allow pluralization on these lines, because it seems that if several users like (or reply to) a content, it will show every likes (or replies) as new notifications, *Toby liked this*, and *Dominion liked this*, not as *Toby and Dominion liked this*.

Here the French locales:
- https://github.com/maelsoucaze/flarum/blob/master/locale/flarum-likes.yml#L19
- https://github.com/maelsoucaze/flarum/blob/master/locale/flarum-mentions.yml#L16

**Comment by dcsjapan** [comment]
> Is it possible to change it to put You always in front?

I thought we were supposed to be doing that already. Perhaps this was only applied to Mentions...

> Another stuff noticied: In the notification center, if we pluralize this line and this line, it doesn't have the correct behavior. It shows the plural...

That's probably because more than one person has liked or replied to the message, even though the notification is only reporting on one like/reply.

> I don't know if it's necessary to allow pluralization on these lines, because it seems that if several users like (or reply to) a content, it will show every likes (or replies) as new notifications...

I agree. I remember discussing this with @tobscure at one point, but I can't recall whether there was a good reason for making the notifications pluralize-able. Now I'm thinking just singular should be enough.

**Comment by dcsjapan** [comment]
I've created a separate issue for the notifications problem (see the latest comment by @maelsoucaze) since it affects both Likes and Mentions, and is only peripherally related to the OP issue.

**Comment by dcsjapan** [comment]
@tobscure It seems that Mentions does not sort the session user to the front of the replies list, as it does for likes. Could that cause the `replies[0] === app.session.user` to evaluate false, so that the `_self` key segment doesn't get inserted?

If so, then it seems we only have to add that sorting to `AddMentionedByList.js`. That would not only take care of the OP issue, it would also sort (pun intended) the capitalization issue that @maelsoucaze mentioned in is second reply above:

> Also, I noticied another stuff: when someone like (or reply to) a post, and then I like (or reply to) a post, it shows Dominion and You [...]. That's not correct in French (and in English too if I'm right) because of the capitalization. Is it possible to change it to put You always in front?

As he says, it's not correct in English either, so the session user really needs to come first.

**Comment by dcsjapan** [comment]
> Could that cause the replies[0] === app.session.user to evaluate as false, so that the _self key segment doesn't get inserted?

Nah, that can't be the cause. Maël said it's not working even when the session user is the only person in the list. Back to the drawing board!

Making the session user first in the list would still be a good idea from the capitalization perspective, tho.
