### ISSUE TITLE
Check whether langpack is the default language before disabling

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#623]
At present it is possible to disable a language pack that the admin has selected as the forum's default language. This can result in the translator attempting to fall back to resources that are no longer valid.

Flarum needs to do the following whenever an admin disables an extension:
1. Check whether the extension is a language pack.
2. If yes: check whether that language pack has been selected as the forum's default language.
3. If yes: fail to disable the extension and warn the user to change the default language first.

Or it could present the user with a list of installed language packs _other than the one the user is trying to disable_, allowing the user to selected a new default language right there ... upon which the extension can be disabled.

**Comment by renyuneyun** [comment]
Hi,

I'm new here (also new to php) and have some interest in solving this issue.

Are there any common fields shared by all language packs so that it can be used to identify an extension's type?

I found there a common one in composer.json ('locale' in keywords), but not sure if it could be used or should be used.

**Comment by Kakifrucht** [comment]
The default locale is identified in the settings table of flarum under the key default_locale

**Comment by renyuneyun** [comment]
@kirkbushell 
Thanks for the reply.

So I can get the default one from the database and check if it's the same as the extension's name?
How to get the value of the key default_locale? Hopefully it's not done by writing a sql statement myself...

p.s. Wouldn't this be a kind of waste since only language packs/extentions should be checked?

**Comment by Kakifrucht** [comment]
I guess you would have to check the composer.json, I'm not sure though.

**Comment by dcsjapan** [comment]
@renyuneyun It should be possible to get a short list of just locale extensions, since the admin UI will be doing something similar to [group extensions by type](https://github.com/flarum/core/issues/746). I'm guessing @tobscure plans to add some sort of "extension type" data to composer.json to facilitate that grouping; if so, that would be the thing to use.

**Comment by franzliedke** [comment]
Hi @renyuneyun, thanks for your interest in solving this issue! And sorry it took a while to get back to you with more information... you know, life. ;)

Anyhow, yes, you are right, the "locale" keyword in composer.json is currently the only way to recognize an extension as language pack. Please note that the `ExtensionManager` already does some work parsing all the extension information from the JSON file, so that is not necessary anymore.

Do you need any other pointers to get started?

**Comment by renyuneyun** [comment]
Hi @franzliedke, thanks for your kindness!

I've found out how to get the needed properties and (I think I've) finished the codes to determine whether the extension is the target or not.

However, I don't know what to do to inform the user (admin) about this situation... Maybe this would be solved in another issue? But at least I should use some mechanisms to broadcast it, right?
So, should I throw an exception or send an event? If using an exception (a custom subclass I think), could you tell me where to place the new class? If using an event, Do I need to do something else other than `$this->dispatcher->fire(some_event)`?

**Comment by franzliedke** [comment]
Hmm, can you send what you have as a work-in-progress pull request? It's easier to discuss this when we actually see the code... :)

**Comment by renyuneyun** [comment]
Sure. I'l create a pull request...

Haven't read through the coding style guidelines yet. If my coding style isn't correct, please point it out :)

**Comment by franzliedke** [comment]
This is now fixed, thanks to @dav-is and @renyuneyun !
