### ISSUE TITLE
clear cache on composer action

### ISSUE THREAD

**Issue by Luceos** [flarum/core#639]
Laravel uses some post-update-cmd events to run cli scripts that clear its cache. Seeing the number of issues with people adding extensions and not seeing changes in the frontend, it might be wise to add a cache clear command which is included in the post-update-cmd events list in the default composer file.

I hope to hear your opinions.

**Comment by tobscure** [comment]
The thing is, after you install an extension with Composer you need to enable it, and before you remove it you should disable/uninstall it (this will be done automatically when we integrate Composer into the admin UI). Enabling/disabling extensions is where cache clearing stuff is done, so I don't think it's actually useful to do this again via Composer.

**Comment by tobscure** [comment]
> Seeing the number of issues with people adding extensions and not seeing changes in the front-end

I assume you're referring to https://discuss.flarum.org/d/1488-translations-never-refresh-after-locale-reinstallation, which is a pretty specific edge case... they're removing the extension without disabling it, then manually editing the en.js file, then installing it again without needing to enable it (because it was never disabled). Again, none of this will even really be relevant once we run Composer within the UI. If there are any more common/realistic scenarios which you're referring to, please explain!

**Comment by Luceos** [comment]
So the conclusion is that adding composer support in the admin area should get quite some priority then @tobscure. And thanks for clarifying these points, you are correct.
