### ISSUE TITLE
Incorrect URLs in "noscript" version

### ISSUE THREAD

**Issue by JD-Robbs** [flarum/core#646]
Hi guys,

Just stumbled upon you. Amazing piece of software!

Just noticed this: https://github.com/flarum/core/blob/232f3b6bc696f8c36b39b1eeaae01c299d4a1622/views/index.blade.php#L11

This outputs the *un*slugged title inside the URL, rather than the properly slugged one.  I couldn't find where you've got your `title-to-slug` utility, so opened an issue instead of a PR.

Cheers!

**Comment by franzliedke** [comment]
Thanks for the report. We will sort this before the next beta release.

**Comment by franzliedke** [comment]
[This](https://github.com/flarum/core/blob/ad2bbdd1157e0520d47ef3627a0b6d81554dfa77/js/lib/utils/string.js#L15-L27) is the current client-side slug function.

Should I just re-create it on the server side? Or should we find a way to transfer the slugged title from the server to the client (e.g. via API)? /cc @tobscure

**Comment by tobscure** [comment]
It's probably wise to generate and store a canonical slug in the discussions table, since in the future we will do some more complex stuff with transliteration and whatnot. Then make it available to the client via the API.

**Comment by franzliedke** [comment]
Okay, I fixed this now. Will require all developers to run migrations (regenerating all slugs on the server side).

Some notes:
- The tag extension seems to be using the client-side slug helper, too. Shall we do a similar thing there?
- Instead of our own helper, we could use the one from Stringy, which is already included (implicitly?) via Composer. This might give us slugs for non-ASCII topic titles for free.
- Slugs are changed when the title is changed. This was the previous behaviour, too.
- I did not yet update the dist files (my Bower dependencies seem to be on different versions).

Please comment, @tobscure.

**Comment by tobscure** [comment]
* Tag slugs are already stored in the database. We only use the client-side slug helper to autofill the slug input based on the title (as you type) when creating a new tag. So it can stay as-is :)
* Yes, absolutely!
