### ISSUE TITLE
Add text to explain why ConfirmPasswordModal has popped up and what it's asking for 

### ISSUE THREAD

**Issue by Luceos** [flarum/core#661]
As an admin you can set a new password for a user. After editing that in the user edit screen you get a popup which asks you to verify this new password. On submitting that form you get a 401 disallowed error, because it requires you to enter the current password of this user.

Also translations are missing here.

```
POST https://discuss.flarum.org/login

{
  "errors": [
    {
      "status": "401",
      "code": "permission_denied"
    }
  ]
}
```

**Comment by Luceos** [comment]
Seems I had to enter my own password. Translations still missing though.
![download 4](https://cloud.githubusercontent.com/assets/504687/11557371/b0355998-99ac-11e5-9dcd-78a2e3e95145.png)

**Comment by tobscure** [comment]
Right – this is the result of a new addition in 9896378b59b3f1d260049c162abe5786c4be8ed0 that I call "sudo mode". Basically you need to re-enter your password when performing any privileged task (like editing a user, permanently deleting anything, visiting the admin CP) if you haven't entered it in the last 30 minutes. That's why you got the confirm password modal.

The translations missing was because I forgot to push changes to flarum/english, should be fixed now. However, we probably do need to add some text to the modal to make it clear why it's there and what it's asking for.

**Comment by Luceos** [comment]
Yes, i was really confused. Your explanation makes sense. I should be more aware of the stability of the official forums ;)

**Comment by tobscure** [comment]
Given that we have decided to remove sudo mode (#674), this will no longer be necessary.
