### ISSUE TITLE
Personal Info Not Completely Removed

### ISSUE THREAD

**Issue by connor0095** [flarum/core#665]
In issue #255 it mentions deletion of personal info. It doesn't remove names from mentions (See screenshot).

![bug](http://i.imgur.com/tz4ljkg.png)
(http://i.imgur.com/tz4ljkg.png)

**Comment by jordanjay29** [comment]
IMHO, this is WAD. You don't want to break references in *other* people's posts when you delete yours. Quotes, mentions and other referential items to a profile should stay, broken links or not, for archival purposes (e.g. someone reading the topic months after it happened and not being able to follow due to deleted accounts).

**Comment by connor0095** [comment]
Perhaps you don't understand. The deleted user's name is listed in the second post (see circled). I think the name should be traded out with 'deleted user' or something.

**Comment by jordanjay29** [comment]
No, I understand and my comment remains the same. If someone wants to delete their personal info, that's fine. But even coded referential items that in someone else's post should stay untouched. 

If someone changes their name, then I'd expect the mention name to change so that the conversation still makes sense. But that's the only reason I can see for the behavior being proposed here. 

Maybe deleting a user shouldn't delete the name, but instead remove the user's profile and login but keep the name in posts and add (deleted user) or some other indication of vacancy.

**Comment by connor0095** [comment]
Perhaps to achieve your name change in sync thing. The '@foo-bar' could be changed to on the server to '@1'. Then any time the post is viewed it would fetch who '@1' is and label them with the real name. If '@1' doesn't exist, it must be deleted. And if someone was to edit their post. The system would change it from '@1' to '@foo-bar'.

**Comment by tobscure** [comment]
@connor0095 This is almost how it works at the moment, except for the final critical step of actually subbing in the username when the post is rendered. See #315. Closing this in favour of that one.
