### ISSUE TITLE
Flarum Beta 4 - You do not have Permissions - Error Message

### ISSUE THREAD

**Issue by AlexL777** [flarum/core#670]
Hello Developers,

I finally installed on a sub domain Flarum, but gets in front at every thing appears that I have no permissions.

Even the Avatar can not be changed. In debug it says that.

    POST http://flarum.wpzweinull.ch/api/users/1/avatar
    {
    "errors": [
    []
    ]
    }

The installation is therefore http://flarum.wpzweinull.ch on the subdomain and I installed it fresh with Composer.

ImageMagick is installed on the server and I use PHP 5.6 and the latest version of MySQL.

How can it then be with this error?

Thank you in advance.

**Comment by Luceos** [comment]
Any errors in the website error log? What are the rights of the storage directories?

**Comment by AlexL777** [comment]
Hello,
So I have the directory /storage and all subdirectories with CHMOD provided 777 aircraft. The directory /assets and all subdirectories also has write permissions.

Then I organized errorlog.txt a file until today and it is in written anything yet. Strangely, even though I did it according to the instructions of my web hosting provider.

In which directory Flarum has the error.log, if it exists?

My server does not have automatic error.log and I had now set himself there. But as I said, it is still empty.

Can it be that Flarum not running on a subdomain or subdirectory?? I want to try to install it on a real domain as http://flarumboard.de. That interests me very easily because it does not work elsewhere. The installation is the first time not so difficult.

**Comment by Luceos** [comment]
The site itself must have an error log, no matter what application you install.

The subdirectory/domain issue should have been resolved in beta 3 already.

**Comment by franzliedke** [comment]
There should also be a Flarum-specific log file in the storage/logs directory.

**Comment by AlexL777** [comment]
Hours later! I wanted to not go on, because Flarum seems to be a very hard nut to crack me. In the German web host All-inkl. and both the subdirectory as well on a subdomain Flarum not working. That's my determination today and throughout the day I have spent.

Why it does not work, I have not figured out.

Fortunately, I have already installed a second web host in Germany called Serverprofis.de and there I have a new domain registered and Flarum including Composer via SSH installed.

The installation was carried out not in the root directory, but the directory /flarum innately. This is so not because it probably would not work again. So I moved in FTP account all the installation package into the root directory and then successfully installed the Forum in the browser.

**I can now create tags in the forum, change avatar, post contributions and install extensions. Then I found out how it is because with the error.log.**

The Forum for All-inkl., this webhost, simply did not write any error messages in the error.log. You see the error only in the frontend in debug, but that you can not do anything. It takes a proper error message that you can decipher :)

So the error.log is now understood for me.

And why it is not working on a subdomain and subdirectory, I can not answer you. I've tried everything and nothing worked. Setting the write permissions also brought no success.

I'll blog more about my installation on http://internetblogger.de so German Flarum users can apply it. And I hope there will be no more mistakes, because I already have the current package with Beta. 4

Those were my evidence emerges today. Puh ... must always be so complicated :)

**Comment by Luceos** [comment]
I'm not sure I follow. Installation on both a subdomain and subfolder failed?

If the explanation is easier for you in German, please do so, both me and @franzliedke are able to understand that perfectly. And we do like to know the exact nature of the issue so we can follow up.

**Comment by AlexL777** [comment]
Also die Installation klappte bei mir bei dem Webhoster All-inkl sowohl auf einer Subdomain als auch im Unterverzeichnis nicht. Ich hatte immer die Fehlermeldung bekommen, dass ich keine Rechte habe und ich habe alles Mögliche versucht.

Kann es sein, dass man in der Datei config.php die URL unbedingt mit "www" haben muss. Ich musste es bei www belassen und dann in die .htaccess RewriteRegeln eintragen, damit meine Forum-Domain immer mit www aufgerufen wird. 

Man hätte wahrscheinlich an der .htaccess etwas ändern müssen oder? Ich hatte sie anfangs so, wie sie war, nur mit RewriteBase /meinVerzeichnis

Dann hatte ich das Problem, dass im Frontend die Icons und Symbole nicht angezeigt wurden. Dann bin ich auf dieses Thema gestossen: http://enable-cors.org/server_apache.html

Ich musste dann zuoberst in der .htaccess einige Zeilen einfügen, weil der Chrome Inspector solche Fehler anzeigte. Ich habe dann nur gegoogelt. 

Letztendlich habe ich Flarum auf einer eigenen Domain installiert, mit all dem, was ich dafür machte. Ich weiss nicht, vielleicht ist es alles nicht so schwer, aber ich empfinde die Installation für Flarum Beginner etwas schwierig. 

Auch muss man bei einem Apache Server herausfinden, dass man nicht "composer update" eingeben kann. 

Man muss da "php56 composer.phar update" eingeben, damit es funktioniert. Das waren halt solche kleinere Sachen, die ich in der englischen Anleitung gesehen habe und die bei mir nicht auf Anhieb funktionierten. Naja, so war die Installation unter http://flarumboard.de nicht ohne. Aber ich sammelte gute Erfahrungen.

**Comment by Luceos** [comment]
Ok so now your issues make a lot more sense. I hope you don't mind me answering some of the issues you encountered in English:

- There is no need to specify www in your config for Flarum to work. Without going into too much technical details about DNS. www is simply a subdomain, just like test.domain.com. They are both a pointer to an IP address. The webserver picks up that hostname and forwards it to the correct website. So if you did not see an installer without WWW, something must have been amiss with either the DNS setting for your domain (not pointing to the webserver) or your apache configuration not having that hostname.
- The installation documentation mentions the composer method assuming composer is installed [globally](https://getcomposer.org/doc/00-intro.md#globally) not [locally](https://getcomposer.org/doc/00-intro.md#locally). With that in mind, running composer using php before the command is unnecessary. Running composer locally requires you to use the php executable, which can be configured differently on each environment/os/webhost. So it's very hard to tell you it's php56, because the default (honestly) is that it's called php. This quickly changes once your server runs multiple php versions, or some idiot sysadmin thinks ahead and named it based on the version. I do agree the installation is quite difficult if you have no knowledge of composer.
- You say you should not run `composer update` on apache, I'm not sure why not on that specific webserver. What I do know is that it's very unwise to run composer update for "normal" behavior. Composer update in fact will update all dependancies, including the flarum/core package. The best thing to use as an unexperienced user is to run `composer install` which uses the composer.lock file and reflects the tested, working environment during release.

Your issues seem mostly to origin from lack of experience in server management, to be frank. I hope @franzliedke can take some time to answer more in detail about your issues where I failed to answer you.

**Comment by franzliedke** [comment]
The base URL configured in config.php should contain the domain either with "www" or not, and you should redirect requests to one form (e.g. with "www") to the other. You got these CORS error messages because the API was being accessed with the URL as configured in config.php, but you were visiting the forum with the other form. Thus, you were visiting one domain, and making cross-domain requests to another.

**Comment by AlexL777** [comment]
Thank you for your answers. Anyway, I had these problems and have yet the Forum installed. You never stop learning, and often it is necessary in the installation instructions that appear on official websites, find out for yourself how you can do it on your own server. Gained valuable experience and good.
