### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by farfeduc** [flarum/core#675]
It would be great to be able to consult flarum when offline with the cache of the last time we visited the website.

Use ? -> Alternative to evernote

In my opinion, flarum will be a decent selfhosted alternative to evernote with the system of tags and the search.
The last thing would be the offline thing. But maybe it will be useful also for other purposes.

Continue your work ! Flarum is great :+1:

**Comment by franzliedke** [comment]
Hmm, well, Flarum isn't worth much without the content. Storing *all* the content offline needs a lot of storage and feels somewhat pointless, since you're typically returning to the forum to see new content, not old one.

So, while I see how your use case (Evernote) would validate the idea, it's somewhat of an edge case, and I'm not sure whether we should go to such great lengths to support that.

**Comment by Luceos** [comment]
Using Flarum as an offline storage for notes is actually a very good idea, but not the intended goal of the software. If this would be useful, I would imagine someone creating (or funding) an extension for this feature set.
