### ISSUE TITLE
MyISAM on posts table

### ISSUE THREAD

**Issue by Luceos** [flarum/core#677]
I'm not sure, but I noticed that the posts table has MyISAM, the others have correctly InnoDB.

**Comment by Luceos** [comment]
Seems this was a [decision](https://github.com/flarum/core/blob/master/migrations/2015_02_24_000000_create_posts_table.php#L37). Any reason why?

**Comment by franzliedke** [comment]
Probably because of that FULLTEXT index right below that line.

**Comment by Luceos** [comment]
I'm not sure that requires myisam.. [Right?](https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html)

**Comment by franzliedke** [comment]
[Not in MySQL 5.5](https://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html), though. That's what we support...

**Comment by matteocontrini** [comment]
Hi everyone, any chance you could reconsider the decision of using MyISAM for the `posts` table? I'm not sure how much this will affect users, but maybe MySQL 5.5 support could be dropped. Since the release of MySQL 5.6, the FULLTEXT index is supported by InnoDB as well.

The fact that there's a MyISAM table among InnoDB table is causing me some headaches here because most backup solutions (including mysqldump) work best with InnoDB, and that MyISAM table is creating some troubles for achieving point-in-time backups.

Thank you.

**Comment by tobscure** [comment]
@matteocontrini Yep in beta 8 the `posts` table will be converted to InnoDB. No more MyISAM 🎉
