### ISSUE TITLE
composer.lock downloadable

### ISSUE THREAD

**Issue by luceos** [flarum/core#692]
We need to inspect and prevent access to the following files:
- [ ] composer.lock ; shows versions and thus allow automated screening of vulnerabilities
- [x] .git directory ; even though not default, a dev might by mistake have added the config to his repository

**Comment by Albert221** [comment]
Can't we just add those items to .gitignore?

**Comment by franzliedke** [comment]
Nope. We want to make sure they cannot be downloaded when they're uploaded on a web server.

**Comment by Albert221** [comment]
This [.htaccess change](https://gist.github.com/Albert221/0740fd93e333fd748323/revisions#diff-8052c42ab3b8aa06a3f5f788a4ddccc2R20) should do the trick. Also there's need to add alternative thing in [nginx  and lighttpd URL rewrite documentation](http://flarum.org/docs/installation/#nginx). Unless this solution should be made in another way.

**Comment by Luceos** [comment]
Your .git patch only works for the root one, maybe this [offered solution](http://stackoverflow.com/a/17916515/717181) is better. A note to the doc team is required to match the update of the documentation at that point.

**Comment by Luceos** [comment]
.git directory has been protected by a commit already:
https://github.com/flarum/flarum/commit/7e17408634c3e60d127b6bd5d3acb6807ed4528f

Now we just need to do the same with the composer files.

**Comment by franzliedke** [comment]
@Luceos Or should we use [this improved solution](http://stackoverflow.com/questions/6142437/make-git-directory-web-inaccessible/17916515#17916515) from the StackOverflow thread you linked to for protecting all `.git` directories and also other Git-related files?

**Comment by Luceos** [comment]
@franzliedke that's still the preferred solution yes, someone might add custom extensions with vcs to the vendor directory for instance.

**Comment by uded** [comment]
May I suggest something for nginx? Instead of listing all of the necessary configuration within the documentation you can include general configuration file in Flarum called, for example, `.nginx.conf` and instruct users to use `include` directive, like 

```include /path/to/flarum/install/.nginx.conf```

This type of approach is as performant as any other solution and would simplify installation and further rewrite rules changes for the users substantially. I guess `FastCGI` configuration still should be in the main config file edited by the user as there are things less predictable or shared between systems to worry about, like the path to PHP-FPM socket.

**Comment by franzliedke** [comment]
With the public folder [now being the webroot](https://github.com/flarum/flarum/commit/c5c81c86512cb4244db75109316f54392c51a28c), this is no longer a problem.

I've added two issues for docs on shared host specific installation/security instructions:
- flarum/docs#15
- flarum/docs#16
