### ISSUE TITLE
E-mail address disclosed after logging in

### ISSUE THREAD

**Issue by Apflufadalia** [flarum/core#693]
In the Profile the users can change their own e-mail address. And when open it, it will show the e-mail address rapidly. It makes changing password possible.
Maybe it can be partical or totally hiding, it'll be better if someone logged in on another way e.g. name+pw.

**Comment by Luceos** [comment]
Editing your password is only possible providing your password again in a separate pop-up designed recently to prevent such unwanted actions. Doesn't that solve this issue?

**Comment by tobscure** [comment]
I don't understand what the issue is?

You can change your email address if you've entered your password in the last half an hour. Otherwise, you'll be prompted for your password. 

Then you must confirm your new email address. 

Once your email address is changed, you can send a password reset email to change your password. 

But all of this hinges on the user having entered their password very recently - what's the issue?

**Comment by Luceos** [comment]
Closing until sufficiently explained.

**Comment by Apflufadalia** [comment]
hi there,
Sorry for long time not responding. Gotcha some problem with internet connection.
I think, it'll be better to cover a part of the e-mail address or the whole address. The user can know which e-mail address should they login(if they have multiple), but the attackers won't know. It's maybe hard to crack a lot of e-mail address with that prefix/suffix, so i think it can protect the users better if you cover the e-mail address, that will increase the time the attackers should spend.

**Comment by dcsjapan** [comment]
@Apflufadalia It's not clear how the attackers you refer to are accessing the information. Since a user must be logged into his/her Flarum account in order to access the Settings page, it sounds like you must be concerned about attackers who have physical access to a computer after that computer's user has logged into a Flarum site.

If someone has this sort of access, they could simply change the email address and then click a couple buttons to reissue the password. That would give them full control of the account. In this scenario, hiding the original email address seems a bit pointless.

If you're thinking of a different scenario, please explain the steps to reproduce the situation you envision.
