### ISSUE TITLE
Add "you need to confirm your email" informational message with "resend" functionality

### ISSUE THREAD

**Issue by tobscure** [flarum/core#709]

**Comment by Averell7** [comment]
Perhaps it is useless, but since no description was given to this "bug", I explain what happens :

- flarum 0.1.0-beta-4
- New user signs up, but does not confirm. 
- He tries to Log In
- The proper message appears : _You need to confirm your email before you can log in. We've sent a confirmation email ... _
- Strangely enough, there is a DEBUG indication with :
```
401 Unauthorized
POST http://bf2016.chartreux.org/login
{
  "emailConfirmationRequired": "<email address>"
}
```
The indicated email address is correct. 
- Nevertheless, an email is sent with an uncorrect content :

```
Hey <user>!
Someone (hopefully you!) has changed their email address on <forum name> to this one.
If this was you, simply click the following link and your email will be confirmed:
http://xxxxxxxxxxxxxx
If this was not you, please ignore this email.
```
The link is correct and works, but the message is disturbing for the new user who does not understand.
