### ISSUE TITLE
Show who deleted a post, and create a new "moderation notes" extension

### ISSUE THREAD

**Issue by luceos** [flarum/core#753]
The flags extension adds an entry in a discussion when a action occurs in the thread. For moderators it would be highly valuable (big understatement) to be able to see who deleted a post or discussion. We could probably implement the same functionality with the post history, from what I understand so far it's a custom Post type, selected on Post creation.

For mods: see [this](https://discuss.flarum.org/d/1895--) moderated discussion.

**Comment by dcsjapan** [comment]
This would only apply to posts deleted using the Flags extension UI. It might also be nice to add information about why a post was deleted to posts that are deleted directly using the post controls.

Another way to handle this would be to modify the post delete function so that it would pop up a modal dialog (or something) allowing the moderator to:

1. Select a reason from deletion from a list of options (e.g. radio buttons or dropdown list)
2. Optionally type specific details about the deletion in a text box.

This information could then be appended as an edit to the deleted post, with a bit of formatting such as:

=====
***Moderator action:*** *This post has been deleted as* `<reason>`.
`<details>`

This would facilitate documentation of moderator action regarding both flagged and unflagged posts.

**Comment by Luceos** [comment]
@dcsjapan my request is more about who deleted the post. Because at this time you can't differentiate between posts deleted by the author or by a mod.

**Comment by dcsjapan** [comment]
Good point ... that could also be incorporated in my suggestion:

=====
***Moderator action:*** *This post has been deleted by* `<moderator_name>` *as* `<reason>`.
`<details>`

**Comment by tobscure** [comment]
OK so the first part of this issue is simply exposing a post attribute that already exists (`hide_user_id`) in the UI. That can become part of core, easy.

To attach a deletion reason, I think the best way to do this is to implement a new attribute called `hide_reason` or `hide_notes`. When a post is deleted, there can be a little button that says "Add notes" or something, which opens a text field when clicked. The notes are visible right below the post to the OP and moderators, but only editable by moderators.

This also raises the question of whether we should implement a similar thing for edited posts. If a moderator has edited a post, they may want to explain to the OP in private why they have done so. Perhaps the attribute could be generalised to be named `moderation_notes`, and the "Add notes" could be a moderator control on every post, regardless of whether it's deleted or not.

This could be a new core extension called "Moderation Notes". Or we could come up with some other snazzy single-word name like "Whispers". What do you think @dcsjapan + @Luceos?

**Comment by dcsjapan** [comment]
Sounds good!

> When a post is deleted, there can be a little button that says "Add notes" or something, which opens a text field when clicked.

You could also autofill that information using the reason specified in the Flags modal. The moderator could then edit or add to that information as needed.

> This also raises the question of whether we should implement a similar thing for edited posts.

That sounds like a good idea ... it would be wonderful if it could be done as a single action. Would it be possible to extend the "edit post" composer when both (1) the person doing the editing is a moderator, and (2) that person is editing someone else's post?

> This could be a new core extension called "Moderation Notes". Or we could come up with some other snazzy single-word name like "Whispers".

How about "Psst!" ;)

**Comment by Luceos** [comment]
Moderation Notes should then have a checkbox or dropdown for visibility. Sometimes you only want to add a note to your fellow mods and not to OP and sometimes you might want to make it public..

But in general :+1: because this will immensily assist moderative tasks!

**Comment by dcsjapan** [comment]
> Moderation Notes should then have a checkbox or dropdown for visibility. Sometimes you only want to add a note to your fellow mods and not to OP and sometimes you might want to make it public..

That's a great idea!

**Comment by tobscure** [comment]
@franzliedke and I discussed and have decided to call this extension "Moderation Notes", because unlike "Whispers" or "Psst", it gives good insight into what it actually does without a more comprehensive description.

**Comment by askvortsov1** [comment]
Extension-wise, this functionality is pretty much implemented by https://discuss.flarum.org/d/22925-friendsofflarum-moderator-notes/45 and https://discuss.flarum.org/d/23228-moderator-warnings-extension/26. 

Related: flarum/issue-archive#273
