### ISSUE TITLE
Reply Dropdown menu changing with actions on page

### ISSUE THREAD

**Issue by Mecvak** [flarum/core#754]
Posting, liking / unliking, etc seem to cause the menu to develop a bunch of lines.
Refreshing the page fixes the issue.
This is on the current [dev commits](http://pastebin.com/raw/Y9EwmLiD)
![](http://i.imgur.com/ftzKyQx.gif)

**Comment by tobscure** [comment]
See 3cec7e8b46b76bc5f35824dc054832b101724369 and db06b8c71acaafac9736174e9f005f6da860b2e3. Track lhorie/mithril.js#934. Basically, as of the resolution of #727, you no longer need to compile JS yourself... but if you are, you'll need to manually apply this patch to your copy of mithril.js until that issue is fixed.
