### ISSUE TITLE
[Composer] Duplicate alert when trying to reply (composer has content already)

### ISSUE THREAD

**Issue by d3vr** [flarum/core#756]
If the composer already contains content (the start of a reply from another post or a new discussion) and you try to reply to another post by clicking on the "Write a reply" input at the bottom of the page, you get an alert warning you of losing that content. If you click on Cancel you get the same alert again. So that makes a duplicate unnecessary alert. 

This is not the case if you click on the reply button on the sidebar instead. A minor bug that needs to be fixed.

**Comment by franzliedke** [comment]
I cannot reproduce this, but it might be because I don't quite understand the steps you're describing.
When I have a composer open, the "Write a reply" input is not shown anymore... that's where the preview appears instead. Or am I missing something here?

Please explain in even more detail, sorry. ;)

**Comment by d3vr** [comment]
I just tried to reproduce the bug, it's no longer there. Must've been fixed by a recent update.
What I meant:
- Go to post 1, start typing a reply
- Go to post 2
- Scroll all the way down and click on the "Write reply" input
- You get a dialog: "You have not posted your reply. Do you wish to discard it?"
- You confirm or cancel the confirm box, either way you get asked a second time
This was the bug, but it's no longer happening.
