### ISSUE TITLE
Theme composer type

### ISSUE THREAD

**Issue by luceos** [flarum/core#766]
I recently see more activity on forums related to themes and #746 ; wouldn't it be wise to create a new composer type value that we will support: `flarum-theme`. Maybe we can even use a seperate directory themes for this type.

Would love to hear your opinions. I didn't notice themes on the roadmap.

**Comment by tobscure** [comment]
For us to consider this, there needs to be a solid advantage over just using the `flarum-extension` package type in combination with the "theme" tag. Keeping in mind that a new composer package type/directory = more API surface area and potentially repeated code. What is the advantage?

We can certainty still have the concept of themes from a UX point of view (as discussed in #746) without a new composer package type.

**Comment by Luceos** [comment]
From what I've seen on [flarum.work](http://flarum.work) tags aren't used consistently. Using type is also much clearer because we already use it for extensions. Using `flarum-extension` for listing in the extensions tab, unless it has a keyword theme doesn't make sense to me.

Speaking of API surface and repeated code, I don't know why that would be the case. We've been talking about moving the themes under the appearance tab, so based on that there shouldn't be more overhead in the admin. Adding one more type => destination to the composer installer isn't that complicated either.

**Comment by franzliedke** [comment]
Okay, we'll use `flarum-theme` as a type for themes.

Language packs and other types of extensions that will stay on the extensions page will be categorized using tags, which we can probably use for visual categorization on that page later on.

**Comment by franzliedke** [comment]
No. You would read about it here. :wink:

**Comment by luceos** [comment]
With the extenders there's no longer any reason to implement this. Closing.
