### ISSUE TITLE
contributing.md

### ISSUE THREAD

**Issue by luceos** [flarum/core#783]
The contributing markdown file needs updating explaining how to start contributing. I'm not sure, maybe we should choose the documentation for that instead of having two sources to point new devs at?

This related to the new documentation too.

**Comment by tobscure** [comment]
Yeah we can probably move it to the documentation (there's a place for that in the new structure, right?) and then link to it from CONTRIBUTING.md.

**Comment by Luceos** [comment]
I do think that's best, I'll assign this to 1.0.0 so we make sure the file in the repo reflects this decision/change.

**Comment by franzliedke** [comment]
Hmm, do we really want this in the docs? After all, the CONTRIBUTING.md works even if you're offline, and it's right where the sources are, so potentially more helpful.

**Comment by Luceos** [comment]
@franzliedke that makes sense. However it would be wise to keep that concise and minimalistic and reference to the official developer documentation from there too. 
As my OP says, it's more a question of where to point new devs to instead of where to put what. I opened this discussion mainly because @tobscure was referencing the contributing.md as being outdated after someone asked how to fix a dev environment he set up using the file.

**Comment by franzliedke** [comment]
Hmm, the guide actually looks okay right now, from a quick glance. That topic you mentioned was due to a bug in the core that surfaced after I added a new migration recently.

**Comment by franzliedke** [comment]
This can be considered done, I'd say.
