### ISSUE TITLE
total number in right-side slider incorrect

### ISSUE THREAD

**Issue by Luceos** [flarum/core#785]
The slider on the rights side gives a wrong x of N count, x should be N but holds the value of the posts in the dom, not the total.

For instance [this thread](https://discuss.flarum.org/d/1881-logo-extension-adds-a-logo-image-to-your-forum/15) at this time has 18 total posts, it now mentions to me 11 of 18 posts. When scrolling up (so the older posts are loaded) the count is re-loaded and correct showing 18 of 18 posts.

I've overheard someone mentioning this and noticed it today, didn't see an issue so this is to make sure it gets fixed.

**Comment by Luceos** [comment]
Pushing this to beta 5 because UX is important to us. :+1:

**Comment by tobscure** [comment]
Yep, can't believe I let this one slip through when I rewrote that code! :flushed:

**Comment by sijad** [comment]
also a problem which can be related to it, with each refreshing discuss page, the post number changes to previous post 

for example if you're at `localhost/flarum/d/{discuss-title}/20`
with each refreshing it goes to `localhost/flarum/d/{discuss-title}/19`, `localhost/flarum/d/{discuss-title}/18`, and so-on

I'm not sure if it's a problem or not, let me know if I need open another issue

**Comment by tobscure** [comment]
@sijad another issue for that would be good, thanks :)

**Comment by tobscure** [comment]
Crap, I think we might need to revert #687, which has caused this bug. /cc @ahsanity (absolutely not your fault, you were just following my instructions! :P)

Basically instead of `let commentsIndex = 0;` we need to set it to a value which reflects the number of comment posts that are previous to the current viewing position of the discussion. Problem is, we have no way to calculate this number without loading all of the posts (which we obviously can't do!) and working out which ones are comments and which are not...

Any suggestions, or are we forced to go back to displaying the numbers according to *all* posts, not just comments?

**Comment by franzliedke** [comment]
No way to do the calculation on the server? (That might be a dumb question, I don't have any experience with this part, yet.)

**Comment by tobscure** [comment]
Hmm, maybe... When we load a discussion, we include an relationship of the IDs of all of its posts in order. Potentially we could include the post type as meta information in this relationship data. It would be slightly less efficient in terms of the query and the data transmission though. Is it worth it?

**Comment by Luceos** [comment]
I wouldn't move this to the server. Mainly because it's only used on the client, if those calculations were used on the server as well, ok; but that's not the case. Also it would require sending that information on each mutation of those posts, I'm not sure it's worth that extra payload.

**Comment by Luceos** [comment]
:+1:

**Comment by tkduman** [comment]
I've something to say about this.

Right side slider thing is showing how many elements are on the screen instead of which post you're currently at.

For example this image: https://i.imgur.com/9Bz5gZJ.png

You can see that there are 4 very clear to see posts in the discussion and 1 system notice about a tag change which is apparently also counted as a post. 6th is if you look at 964th pixel of the total 974 vertical pixels you'll see there's another line separator. (The very bottom) That's the last one which makes the counter go 6 / 11.

---

About #945, if you try to click on **now** button, it'll grab the left value, afterwards it'll retrieve max value. Add both. Display. Realize that something went wrong and mathematically impossible. Fix it.

```
// This code is for clicking the "now" button.
current_value + max_value = display_value; Display(display_value);
if (display_value > max_value) // Do this **before** the 1 line above Display() function.
{
    display_value = max_value;
    Display(display_value);
    return;
}

```

Since I know C++, I wrote a basic code to demonstrate the problem and the formula of it.

---

Here's another screenshot of the issue: https://i.imgur.com/6hehupb.png
Here's the proof of it's displaying visible post element count: https://i.imgur.com/NbNqOTu.gifv
GIF of above code example: https://i.imgur.com/dgzqmFm.gif

current_value = 6, max_value = 11.
6 + 11 = 17, displays it. Then reverts back to 11.

On mobile going to bottom sometimes breaks the counter. (For a split second of time it displays an impossible value. (10 / 9 in this instance.) If you keep going down at the very bottom counter reset to 1 / max_value.

---

Another GIF about the max value exceeding problem: https://i.imgur.com/dDVWRQK.gif

2 of 2. current_value = 2. max_value = 2. 2+2 = 4. Display 4.
Whops. Display 2.

---

I'm using Google Chrome Version 63.0.3239.108 (Official Build) (64-bit) on PC and latest Android Google Chrome on phone as well.

PC OS: Windows 10 Pro 1703 (OS Build 15063.768)
Phone OS: Android 7.0.0

Also @sijad 's [785#issuecomment-182250958](https://github.com/flarum/core/issues/785#issuecomment-182250958) still persists.
