### ISSUE TITLE
Add per-user, per-interface language preference settings?

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#812]
Inspired by [this thread](https://discuss.flarum.org/d/2095-does-anyone-have-the-english-language-files).

Occasionally a user may want to use a different language in the admin UI ... it happens to me all the time. Rolling your own hybrid language pack is a solution, but seems like more trouble than it should be. We could support such users better by allowing them to install two complete language packs and allowing them to select between them.
1. Add two language preference settings two the user Settings panel:
   - **Forum UI language** (displayed for all registered users)
   - **Admin UI language** (displayed only users with admin access)
   
   Each of these would be a dropdown listing currently installed language packs.
   
   The former setting would replace the current language selector, so ...
2. Change the current language selector so it displays only for unauthenticated users.

The two labels (in boldface above) could be grouped in the Settings page under a heading that reads **Language Preferences** or something like that.

Would it be very difficult to get the translator to use a different language pack depending on which UI is being accessed?

**Comment by maelsoucaze** [comment]
I don't see the point to include something like that. Only few users will benefit of that feature (I don't know another BBS or CMS using this method, and almost nobody asked for it.

If this feature is really needed, the easiest method would be to separate admin parts in a different YAML file (ex: core.yml and core.admin.yml, flarum-likes.admin.yml, etc.), so it will be super easy to change these files with others of another language pack.

**Comment by maelsoucaze** [comment]
On another point, I like [Grav](https://getgrav.org/), and they released the administration panel as an [extension](https://getgrav.org/blog/beta-admin-plugin-available). It's was a brillant idea, it's easier to update and administration panel is sometimes unecessary.

If this method was applied to Flarum, admin variables will be separated into a flarum-admin.yml file, and the issue is solved.

**Comment by dcsjapan** [comment]
> I don't see the point to include something like that. Only few users will benefit of that feature (I don't know another BBS or CMS using this method, and almost nobody asked for it.

Joomla does it, for one. WordPress doesn't do it natively, but there's a WP Native Dashboard plugin that's been used by lots of people. I could probably name a few others, if I wanted to take the time.

> If this feature is really needed, the easiest method would be to separate admin parts in a different YAML file (ex: core.admin.yml, flarum-likes.admin.yml, etc.), so it will be super easy to change these files with others of another language pack.

Slightly less work than rolling your own YML files, but it still means you're stuck with a single admin language. The ability to switch languages becomes rather important whenever you have a multilingual team administering the site.

**Comment by wion** [comment]
> **Occasionally** a user **may** want to use a different language in the admin UI ... it happens to me **all the time**. 

Is that an oxymoron? Because "occasionally... may" and "all the time" are not equivalent. ;)

Seriously, though, I've been working in online communities in various ways with people all around the world for nearly 20 years, and I've never been in a situation where the *admin-side* of any core tool had to be in multiple languages for collaboration reasons. (The user's front-side, sure, but that's a different situation.) 

Having such a feature would assume that you wouldn't be able to communicate with your collaborators at any time outside of the forum (e.g., via phone, email, etc), and if that was true, then you probably have an undesirable collaboration arrangement. If you can't rely on your human abilities, you better not rely on technology.

There's a simple rule for admin or leadership collaboration: there must be a **common** language that all collaborators can work with. Otherwise you probably shouldn't be collaborating with each other. 

I'd say this is a low-demand/low-needed feature that should either be an extension for the rare times anyone needs it, or it should be put off until several versions of stable release have been made. This is not a vital feature, IMO, that should increase the core code footprint, and it certainly isn't a first-release priority, and probably not even worth being in this branch.

2 cents.

**Comment by dcsjapan** [comment]
> Is that an oxymoron? Because "occasionally... may" and "all the time" are not equivalent. ;)

The first half is talking about users in general, the second half is talking about me as a case in point.

> Having such a feature would assume that you wouldn't be able to communicate with your collaborators at any time outside of the forum (e.g., via phone, email, etc)

I don't follow you. This is simply about what language the UI displays in. Basically, it would allow each member of a multilingual team to display and navigate the admin UI in their preferred language, for time saving and convenience. It has nothing to do with the language used for communication between staff members, which is content, not UI.

**Comment by franzliedke** [comment]
I don't think there are any plans to move forward with this at this point. Of course, this decision may be revisited later.
