### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#822]

**Comment by Luceos** [comment]
Does this include supporting other cdn's for including the files now in core? See https://github.com/flarum/core/issues/822

**Comment by tobscure** [comment]
No that's kind of a separate issue (I assume it's referring to the use of a Google web font?). I think there's another (much older) issue for that. This issue is about supporting use of a CDN to host Flarum's assets and avatar uploads.

**Comment by imcaffrey** [comment]
@tobscure Yes, i am referring to the use of the Google web font.
I wonder how do I customize the core so that I can use a mirror of Google font for this. (I mean changing all links of `fonts.googleapis.com` to another site.)
You know, in my district it's quite hard to access Google web font stably.
Thanks!

**Comment by indiecore-fm** [comment]
Looking at support for KeyCDN. It's a great cheap option for many people.

**Comment by xuelangZF** [comment]
Which version will add cdn support? it seems not have a Milestone

**Comment by askvortsov1** [comment]
Split into public/assets, and storage/caching as separate

**Comment by matteocontrini** [comment]
@askvortsov1 do you mean this issue has been split? I'm not seeing new issues on this topic

**Comment by davwheat** [comment]
We've got #1783.

**Comment by askvortsov1** [comment]
Correct. We'll be adding an issue for the storage / cache stuff in a bit.
