### ISSUE TITLE
[Tags] Requiring no primary tags still forbids using nested secondary tags alone

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#829]
When no primary tags are required in order to post a discussion, Flarum will still restrict any nested secondary tags from being accessible to the discussion. This enforces the categorization hierarchy, but may be unintended behavior for some admins (who would like discussions categorized under a nested tag but without its primary, for better sorting).

**Comment by tobscure** [comment]
Can you explain the use-case ("for better sorting") a bit more? This currently works as intended if I'm understanding correctly.

**Comment by jordanjay29** [comment]
I think @Luceos can explain it better than I can.

**Comment by Luceos** [comment]
- You have your Flarum set up to NOT require any primary tags, but you DO have subtags within primaries.
- You create a new discussion but can't select any of the subtags because you have to select a primary first.

**Comment by dcsjapan** [comment]
I think this can be read two ways:

1. Users should be able to apply a nested tag to a discussion *without* applying it's primary ... basically, it should be possible to use subcategories without parent categories.

 I wouldn't say this is a bad suggestion, but it *would* be a major re-imagining of how tags work.This may well be worth discussing, if it is what you mean.

2. Users may have a hard time finding and/or choosing an appropriate tag because dialog doesn't show nested primaries until the appropriate primary is selected.

 Let's say a user wants to ask a question about installation. He doesn't see any "Installation" in the tag selection dialog, so he has to hunt around a bit before realizing it's filed under "Support". There may be a bit of a UI/usability issue here, which could be solved without reimagining how tags work. Maybe it would be enough to show nested tags in the dialog, and fix it so clicking one of them automatically selects the appropriate primary as well.

Which did you have in mind? I have some ideas for the former too, though (like I said) it would involve a much larger change to how tags work.

**Comment by tobyzerner** [comment]
I don't see the actual use-case for interpretation 1. What is a real-world scenario where you'd want to apply a sub-tag without applying its parent, and where that sub-tag wouldn't be better suited to a "floating" secondary tag, or being a parent primary tag itself?

The whole paradigm of nested categories/tags is based on the assumption that the sub-tags add extra information to a primary classification in the parent tag. To take a few examples from discuss.flarum.org:
- You can't talk about **Installation** without implicitly asking for **Support**.
- You can't talk about **Extensibility** without implicitly talking about **Development**.
- You can't talk about **Design** without implicitly giving **Feedback** about Flarum.
- You can't submit a **Language** without also submitting an **Extension**.
- You can't **Showcase** your forum without it also being **Off-topic**.
- etc.

If we're talking about interpretation 2, then yes, that's a UI/usability issue that we can discuss further. However, again, under the paradigm I've outlined above, I don't see how it's really necessary – if a user wants to get support with installation, presumably they _will_ be thinking about **Support**.

**Comment by dcsjapan** [comment]
> 1. What is a real-world scenario where you'd want to apply a sub-tag without applying its parent, and where that sub-tag wouldn't be better suited to a "floating" secondary tag, or being a parent primary tag itself?

I tend to agree ... the idea of subcategories without parent categories doesn't make much sense to me either, so I've been trying to imagine a situation where such a setup would be useful.

So ... this is just speculation, but ... let's imagine an admin wants to set up a site with a couple dozen or so tags that we would consider primary categories. That's a lot of tags to have running down the side of the site, so the admin wants to organize them somehow.

Now, the way sub-tags are hidden and revealed offers a great way to do this ... but in order to take advantage of that, he'd have to make them all sub-tags. That means coming up with some primary tags to group and hold them, which he may be willing to do ... but only as a convenient way of organizing things. He doesn't want the more semantic implications of primary tags, e.g.:
1. He doesn't want user to be able to search the primary tags.
2. He doesn't want the primaries to show up next to the discussion title in the index.

... and so on. Yeah, it sounds like an edge case to me, too. But there may be some value in looking at the tags this way. To put it in more abstract terms, we're talking about looking at tags purely in terms of how they function, without making any assumptions about how they'll be applied.

> However, again, under the paradigm I've outlined above, I don't see how it's really necessary – if a user wants to get support with installation, presumably they will be thinking about Support.

Here again you're assuming that every admin will be able to come up with an taxonomy that works as well for him as ours does for us. The problem with working from such concrete examples is that you can lock yourself into one way of thinking, and end up with a system that seems perfectly rational from one perspective, but unwieldy from another.

Mind you, I'm not saying that there's something wrong with the way Tags works now ... I rather like this extension and will enjoy using it, even if it means I'll have to do some mental calisthenics to adapt my esoTalk site (which is nested to three or four layers in some places) to a two-tier system. But ... it might be worthwhile, if you're going to be reworking it someday anyway, to think about ways it can offer admins greater flexibility of function without imposing an idea of how that functionality should be used.

**Comment by jordanjay29** [comment]
Honestly, there's two reasons I can think of where someone would want Use Case 1. 

1. Organizational display. There are traditional forums I've seen set up with boards that have sub-boards, and the only purpose for those top-tier boards is to act as category. No posts are allowed in those particular boards, only in the sub-boards, which would be similar to having an empty primary tag with its nested secondaries populated. 

2. Better sorting. Not seeing the entirety of secondary tags when viewing the primary tag would be a valuable option. This may be more useful as a change to the view instead, but for the moment I'm going to assume someone wants to accomplish this by way of tagging alone. This means you could see all general Support topics without seeing Installation topics, and then click into the Installation topics when you wanted to see those. Or not have Support cluttered with the Solved topics, for instance.

**Comment by dcsjapan** [comment]
@jordanjay29 Thanks for the clarification ...

> There are traditional forums I've seen set up with boards that have sub-boards, and the only purpose for those top-tier boards is to act as category..

Many scripts even provide categories which are nothing more than a heading (and maybe a box around the forum) for just this purpose.

**Comment by tobyzerner** [comment]
> @dcsjapan Many scripts even provide categories which are nothing more than a heading (and maybe a box around the forum) for just this purpose.

Yes, I think we've talked about adding this functionality in the past (https://github.com/flarum/core/issues/395 mentions it briefly, and I recall a discussion on the forums, but I can't seem to find it right now).

So it seems to me that adding the ability to have tag "groups", where you can divide primary tags under different semantic headings, would solve @jordanjay29's first use-case.

As for the second one, that's an issue that can be solved by search gambits / a UI change. i.e. this issue: https://github.com/flarum/core/issues/394

So I still really can't see a valid use-case for this. Remembering that we will never be able to cater for all minor edge cases – our priority with core extensions is to cater to the majority in the most simple way.

**Comment by jordanjay29** [comment]
flarum/issue-archive#393 and flarum/framework#394 seem like reasonable solutions to me. I don't have so much of a problem with this as I do the flarum/issue-archive#358 I reported just before.

**Comment by dcsjapan** [comment]
> So it seems to me that adding the ability to have tag "groups", where you can divide primary tags under different semantic headings, would solve @jordanjay29's first use-case.

Yes. It would allow admins to apply some sort of structure to the list of primary tags, which ... it must be said ... isn't a particularly structured way of organizing information.

Of course Flarum's approach is to break from the traditional forum way of organizing things, but I am concerned that be removing too much structure could really limit the applications in which admins will find Flarum useful. The lack of structure isn't a big deal if you only have a few forums (primary tags) ... say up to ten or a dozen ... but for larger sites with a great many forums, the lack of structure in the tags list could make it quite difficult for users to navigate the site.

> So I still really can't see a valid use-case for this. Remembering that we will never be able to cater for all minor edge cases – our priority with core extensions is to cater to the majority in the most simple way.

I agree, there has to be a point at which we can say: this is what the Tags extension does. It may not do everything that everyone wants, but it should be perfectly useful for many Flarum sites, and ... perhaps most importantly ... it serves as an example of what you can do with Flarum extensions.

... Which implies that sites with more extravagant needs ... such as the possibility of applying sub-tags without primaries, or the possibility of making a single sub-tag available to more than one primary, as described in https://github.com/flarum/core/issues/421... may be better served by a third-party replacement extension.

> flarum/issue-archive#393 and flarum/framework#394 seem like reasonable solutions to me. I don't have so much of a problem with this as I do the flarum/issue-archive#358 I reported just before.

I agree, that does need to be fixed.
