### ISSUE TITLE
External links: new window, noreferrer, noopener?

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#859]
This article has been making the rounds, pointing out an issue with links that use `target=_blank` to open links in new windows:
https://mathiasbynens.github.io/rel-noopener/

It suggests adding the new "noopener" (and maybe "noreferrer") rels to these links as well, to prevent any issues.

We add `target=_blank` to all external links in posts here:
https://github.com/flarum/core/blob/a6cf10f8546c3b2b2d0e0e338800ee57b5b66adc/src/Formatter/Formatter.php#L135

In addition, there are [good arguments to be made against opening links in new windows by default](https://css-tricks.com/use-target_blank/). However, we also employ infinite scrolling and may have some ongoing interactivity on the page, so removing the attribute may indeed be a bad idea.

So, we need to decide:
- whether to use `target=_blank`
- if yes, whether we should secure those links with "noopener" rels
- whether to use "noreferrer" also
- for the latter, whether there are any downsides to supressing referrers

**Comment by franzliedke** [comment]
I currently lean toward adding "noopener and noreferrer" in the one place mentioned above.

Regarding `target=_blank`, I'm torn: I like the arguments put forward in the article I linked to (mainly, users should decide how they want their links opened - using already existing browser features), but I worry about things like back buttons in combination with infinite scrolling due to our single-page app architecture.

**Comment by JoshyPHP** [comment]
You don't need both, [noreferrer alone should be enough](https://www.w3.org/TR/html5/links.html#link-type-noreferrer).

> This keyword also causes the opener attribute to remain null if the hyperlink creates a new browsing context.

**Comment by JoshyPHP** [comment]
I've thought about it and while it doesn't seem that the exploit can be used for anything too serious, the potential downsides of systematically adding `rel="noreferrer"` to links seem trivial. That's why I decided to update the library to systematically set `rel="noreferrer"` on any link that has a `target` attribute and doesn't already have `rel="noreferrer"` or `rel="noopener"`. I intend to publish the next release (0.4.12) at the end of the week/early next week.

If you come to the conclusion that you want `noreferrer`, you won't have anything to do. If you *don't* want `noreferrer` or you want to have your own implementations, you'll be able to disable it with the following:
```php
$configurator->templateNormalizer->remove('SetRelNoreferrerOnTargetedLinks');
```

**Comment by tobscure** [comment]
I am in favour of getting rid of `target=_blank`. The back button will still work fine since we update the URL during infinite scrolling. The post composer prompts before letting you leave the page if you have unsaved content, and one day we will have drafts + autosaving. We have no other good reason to use it.

**Comment by buiductuan182** [comment]
whether to use target=_blank : i thing we need use
ex: <a href="https://www.quangminhhanoi.com" > nha phan phoi dieu hoa  </a>
if yes, whether we should secure those links with "noopener" rels: no
whether to use "noreferrer" also: yes

**Comment by clarkwinkelmann** [comment]
The current implementation is fine from a security standpoint. `rel=noreferer` prevents the `opener` from being sent to the new tab. So I suggest we drop the security tag or close the issue.

Other relevant reading: https://developers.google.com/web/tools/lighthouse/audits/noopener

Regarding the discussion points, I'd be in favour of changing the following things:

- Drop `target="_blank"` as suggested by multiple articles. We don't have any *good* reason to keep it. This also means we won't need to worry about the `opener` in the future anymore
- Keep `nofollow` but drop `noreferrer` from parsed links, instead control that behaviour with the [`meta name="referrer"` or header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
- I think the default should be to keep the referrer as it's a useful metric in analytics. It does not even really need a setting inside Flarum as this can be configured via headers at the webserver level

**Comment by franzliedke** [comment]
I agree about removing `target="_blank"`. We might want to add a discussion topic about this and ask for input from the community, and then schedule it for the next beta.

With that out of the way, I think the `Referrer-Policy` header should be configured by the server admin, if necessary. (Extensions can easily add it as well.)

---

@clarkwinkelmann Can I ask you to take care of 1. gathering community input, 2. closing this issue, and 3. opening a new one for removal of `target="_blank"`?

**Comment by clarkwinkelmann** [comment]
@franzliedke sure, I'll take care if it :+1:

**Comment by clarkwinkelmann** [comment]
Discussion: https://discuss.flarum.org/d/20937-rfc-stop-forcing-user-links-to-open-in-new-tab

Feedback so far suggests removing `target=_blank` is not a desired change.

Do we want to make this an option in core ? And if so would it be an admin setting and/or a user setting ?

Regarding the part about the `Referrer-Policy`, it seems we can't remove `rel=noreferer` as it serves as a fallback for browsers that don't support `rel=noopener` and would leave them vulnerable to the opener vulnerability.

I have an additional suggestion that might solve both issues: open the link in a new tab via javascript. That way it can easily be customized via a user preference without altering the textformatter output per-user, and it also allows us to control the opening of internal links inside the single page app, which is a different, yet related issue (I'll also open an issue for that if there isn't one already).

I'll open the next issues when I close this. I'll leave the feedback discussion open a bit longer.

**Comment by datitisev** [comment]
@clarkwinkelmann The issue with opening new tabs via JavaScript is that the browser detects them as popups, whether they are in a new window or a new tab. Some browsers prevent opening pop-up windows by default, so that would not be a good user experience.

![image](https://user-images.githubusercontent.com/6401250/62468455-1c3ec880-b764-11e9-9d85-64da58a2c6a5.png)

**Comment by matteocontrini** [comment]
> we can't remove `rel=noreferer` as it serves as a fallback for browsers that don't support `rel=noopener` and would leave them vulnerable to the opener vulnerability

I think this should be put in perspective.

According to caniuse.com `noopener` can be "used" by 90% of the global users, while `noreferrer` is supported by 95% of them (+ partial support for IE11 - since 2017 - depending on which version you have, so it's difficult to estimate. If you install Windows 10 LTSB now you aren't getting `noreferrer` support in IE, and this is what businesses and schools often use, so `noreferrer` doesn't really solve the issue on IE11).

What I want to say is that this is an issue only if you are using an old version of a browser. If you pick a modern browser now, the `noopener` support is there (except for Edge which accounts for <1%). And if you use an old version you will be exposed to many other security vulnerabilities too...

Moreover, didn't we live for 20 years without worrying about the `window.opener` thing? Was this vulnerability really exploited in the real world? What's the chance that it's exploited now that a solution has been already deployed in all browsers?

**Comment by clarkwinkelmann** [comment]
> Moreover, didn't we live for 20 years without worrying about the window.opener thing?

Well I think it's worrying we didn't worry about it :scream: no idea about exploitation in the wild but it could be really nasty.

> now that a solution has been already deployed in all browsers

The solution requires websites to use the `noopener` `rel` attribute, so probably not all of them are safe. See below other forum software still vulnerable, including vbulletin :scream: :scream: 

I have visited the following forums (as guest) and checked how they handle external links:

- phpbb (tested at https://www.phpbb.com/community/): same tab, no `rel`
- Discourse (tested at https://meta.discourse.org/): opens links in same windows, but sets `rel="nofollow noopener"`. Their GitHub plugin seems to use external links with `target="_blank` and `rel="nofollow noopener"`
- Asgaros (tested at https://www.asgaros.de/support/), same tab, nofollow
- wpForo (tested at https://wpforo.com/community/), same tab, nofollow
- bbPress (tested at https://bbpress.org/forums/), same tab, nofollow
- Vanilla (tested at https://open.vanillaforums.com/), same tab, nofollow
- NodeBB (tested at https://community.nodebb.org/), same tab, nofollow. Some links seem to be rendered by plugins (links to php docs for example) and do have `target="_blank"` and as many as all the possible rel: `nofollow noreferrer noopener`
- MyBB (tested at https://community.mybb.com/), `target="_blank` and `rel="noopener"`
- Vbulletin (tested at https://forum.vbulletin.com/), `target="_blank"`, no `rel`. **is vulnerable to the opener issue**
- SMF (tested at https://www.simplemachines.org/community/), `target="_blank"`, no `rel`. **is vulnerable to the opener issue**
- (not a forum, but interesting) DuckDuckGo: user setting, always `rel=noopener`. when enabled, adds `target="_blank"`

I have not checked which of them have settings to let webmasters toggle the behaviour.

This investigation so far suggests:

- Some forums are vulnerable to the opener issue, but this isn't really our concern here. It does show it's something to keep in mind
- I have seen no significant usage of `rel=norefferer`, so I think it's safe to drop it and use `noopener` alone instead as you suggest @matteocontrini 
- Forcing links opening in new tab doesn't appear as widespread as the comments on Discuss suggest
- None of the websites I visited used javascript to open new tabs, so this might not be a standard thing to do indeed

I'll make a follow-up post on Discuss about this, I'm curious to know which other softwares I missed and might enforce new tabs by default.

Maybe I'm just unlucky and all of these platforms decided to disable new tabs on their support forums :man_shrugging:

**Comment by franzliedke** [comment]
Thanks for the thorough research, @clarkwinkelmann. That's awesome!

I am currently leaning towards removing `target="_blank"` in core. It can easily be replaced by an extension, which could take care of the security aspects and even make certain parts of that configurable, if desired.

The idea would be to make *no assumptions* in core. The feature is easy enough to *add* using an extension, so I would prefer that over an extension that removes core features.

Any input?

**Comment by clarkwinkelmann** [comment]
@franzliedke agreed. But should this be a **core** extension though ?

My research on other software indicates that it's not *that* common to open links in new tabs.

However the community feedback seems to indicate this might be (become) a very requested features.

If we don't offer this in the default installation, I am wondering if this will become another regular question, like "where's image upload" and "where's private messages".

**Comment by franzliedke** [comment]
Feels like making assumptions again. I see no problem with making it a non-official extension. If it becomes super popular, it's easy enough to pull it into the official bundle / under the official umbrella.

**Comment by clarkwinkelmann** [comment]
@franzliedke agreed. No objection to your suggestion :+1:

**Comment by franzliedke** [comment]
Done. I also [created an extension](https://github.com/franzliedke/flarum-open-links-in-new-tab) that people can use starting with the next beta release.

**Comment by matteocontrini** [comment]
Personally I don't think that moving the external links behaviour in a 3rd party extension is a good solution.

External links have opened in a new tab since always in Flarum. Everyone was happy about that and now the behaviour suddenly changes. I know, there's the extension, but 3rd party extensions are hard to discover. People upgrading from the previous beta might read the upgrade instructions, but new Flarum administrators will not.

It would be much easier if the extension was bundled with Flarum, even if disabled. Forcing administrators to find and install an extension for a behaviour that has been the default for years feels very unnatural to me.

**Comment by luceos** [comment]
I'm starting to have mixed feelings too.. Can't we offer two checkboxes in core for now, one for internal links and one for external ones?

**Comment by clarkwinkelmann** [comment]
> Forcing administrators to find and install an extension for a behaviour that has been the default for years feels very unnatural to me

We should list the explanations and how to install the third-party extension in the update steps if we do this. This should be enough to let people retain the current behavior.

This is beta after all, they should expect things to change.

> Can't we offer two checkboxes in core for now

If we start offering new settings in the default install, I'd say a core extension would be best. There's also settings for `nofollow` and `noreferer` that could be added to it.

**Comment by franzliedke** [comment]
I am very open (and actually plan) to add more configuration options to my extension, both for configuring the `rel` values and how to treat internal vs. external links.

> External links have opened in a new tab since always in Flarum. Everyone was happy about that and now the behaviour suddenly changes. I know, there's the extension, but 3rd party extensions are hard to discover. People upgrading from the previous beta might read the upgrade instructions, but new Flarum administrators will not.

Clark explained this pretty well: existing people will be notified in the upgrade guide; new installations will not experience any change to what they're used to and will search for extensions anyway.

---

With all of that said, I am very convinced that this is the right way forward: keep the core lean (especially with regards to more admin options), go with browser defaults and make no assumptions - but offer flexibility through focused extensions.
