### ISSUE TITLE
Update FontAwesome to version 4.5

### ISSUE THREAD

**Issue by tobscure** [flarum/core#891]
- assets/fonts
- less/lib/font-awesome

Actually, we should try loading it via Composer (https://github.com/components/font-awesome) so we don't have to include it in our repo.

**Comment by Scarwolf** [comment]
What is composer doing with those files? As flarums current structure for the FA-files is different. Is it possible to tell composer to move the file afterwards?

Flarums Structure::
* assets/fonts/
* less/lib/font-awesome

FAs Structure:
* fonts/
* less/

**Comment by Luceos** [comment]
We could re-introduce the composer-installer and have it check on type component and perhaps name components/font-awesome. If so we can move it into an resources folder of some sort.

**Comment by InconclusiveImpurity** [comment]
Worth mentioning the official repo [1] contains a composer.json, so it should be preferred if possible, removing any costs for maintaining additional repositories. 

Since composer is used to install flarum it can easily be utilized. A clean Solution would be to add an Composer Asset Manager to flarum itself, not the core, running as a plugin / installer. This is easy to accomplish by using component installer [2]. An example can be found in my fork. I haven't gotten the time to fix it at all, since from a user perspective it will not work, since configuration has to happen in the main composer.json and can not be loaded within other dependencies. Thus invoking default behavior. 

Worth mentioning is, that by excluding font awesome from the core and refactoring it into flarum itself assets get decoupled from core functionality. (Assets dependency resolution can be implemented by the Composer Asset Manager) - Making dependency resolution for extensions even less redundant and plain simple (e.g. two extensions using another icon font). I have to admit i have not yet looked at the given Asset Compilers i briefly saw. 

[1] https://github.com/FortAwesome/Font-Awesome
[2] https://github.com/RobLoach/component-installer

**Comment by franzliedke** [comment]
This is done now.

I am not particularly happy with how the paths [are hard-coded](https://github.com/flarum/core/commit/619561cf56a5a1c965949744c884cccca369aafe#diff-975b8c896ebfb85bdd2532db8c9038d6) at the moment, we'll have to tackle that problem in the future.

This probably means we'll have to provide a way for packages (a.k.a. extensions and core) to register paths to be a) published and b) loaded by the LESS compiler.

@tobscure Will that already be part of the asset management refactoring you were working on? Or should it be part of publishing assets (I remember there being a ticket, but I can't find it...)?

**Comment by nielstholenaar** [comment]
It seems that your commit, has broken the parsing of the Less. At least at my installation.

The CSS files won't be created, and the Less_Parser throws an error.

```
File `font-awesome.less` not found. in app.less
```

**Comment by franzliedke** [comment]
@nielstholenaar Have you run `composer update`?

**Comment by nielstholenaar** [comment]
@franzliedke Ofcourse.

It seems to be fixed by prefixing the path with the `base_path`

So:

```
'import_dirs' => [
   'vendor/fortawesome/font-awesome/less' => '',
],
```

Becomes:
```
'import_dirs' => [
    base_path() . '/vendor/fortawesome/font-awesome/less' => '',
],
```

**Comment by franzliedke** [comment]
Ah, yeah, that makes sense.

It's interesting, though, that it works for me. Are you running Flarum in a slightly different setup (e.g. having a special `public` folder)?

**Comment by franzliedke** [comment]
I just pushed a fix, thank you!

**Comment by nielstholenaar** [comment]
@franzliedke Yes I modified Flarum to have the assets folder and index files in an public directory.

Nice to hear :+1:
