### ISSUE TITLE
Mobile issue post controls

### ISSUE THREAD

**Issue by Luceos** [flarum/core#908]
I'm on mobile and can't hit like, reply or triple dot if the number of likers or replied people is multi lined. After some testing I am able to click the buttons but only on the top half. My guess is that the second line is full width and goes through the buttons.

Android 6, chrome.

I have this on Ron Jeremie's post 
https://discuss.flarum.org/d/1030-classifieds-extension/9

**Comment by Luceos** [comment]
I noticed the exact same behavior of not being able to click "reply" on my desktop now [here](https://discuss.flarum.org/d/2455-sucuri-showing-my-forum-infected). From what I see .Post-footer is above .Post-actions because the latter is floating right.

**Comment by Luceos** [comment]
Funny detail, select the text "modedeep and datitisev replied to this." and then click reply :grin:

**Comment by UaMV** [comment]
Could be related: I'm unable to login on mobile (tried multiple devices, accounts, browsers, & both my personal flarum install & that at discuss.flarum.org). When I click the debug link, it return the following report:

```
0
POST https://fe…er.net/login
null
```

**Comment by UaMV** [comment]
FYI, it's been very touch & go with me, so I can't speak definitely. I think some of my issues might be server related (at least for my site). I was finally able to get a log in via Safari on iOS.

**Comment by UaMV** [comment]
I think [this](https://discuss.flarum.org/d/2141-problems-with-post-requests-when-using-cname-records/4) was my issue. Disregard my previous comments.

**Comment by franzliedke** [comment]
This is easy to fix by applying a `z-index` to the `.Post-actions` container. However, that's just a workaround, so I'd like to avoid that, if possible.

I've done some digging to find out why this only happens when the post has replies (only), but not with likes. The problem seems to be the `position: relative` which is applied to the `.Post-mentionedBy` container (which it needs to absolutely position the popup with the reply preview), but not the `.Post-liked` box.

Commencing research...

**Comment by Luceos** [comment]
Great job @franzliedke :+1:
