### ISSUE TITLE
Permissions - Reply to discussion negates Start discussions

### ISSUE THREAD

**Issue by kulga** [flarum/core#917]
using dev-master but also showed up on beta.5

If a user has permissions:

* Allowed to Start Discussions
* Not allowed Reply to Discussions

The user is unable to create a new discussion and when the user attempts to:

```
      "status": "401",
      "code": "permission_denied"
```
___
If the user has their permissions changed:

* Allowed to Start Discussions
* Allowed Reply to Discussions

They can create a new discussion

**Comment by poush** [comment]
Can anyone tell me understanding the method https://github.com/flarum/core/blob/master/src/Core/Access/Gate.php#L183

and 

https://github.com/flarum/core/blob/master/src/Core/Access/Gate.php#L183

**Comment by franzliedke** [comment]
Hmm, I'm torn on this one. After all, the "reply to discussion" permission basically means the user is allowed to make posts. The "start discussion" permission is a special case of that - it's for new topics only.

So, technically, one should need the permission 

Isn't this a usability problem really? So that the "start discussion" permission should automatically activate the "reply to discussion" permission? Is there any valid use case where users would only be allowed to start discussions, but not to reply to them?

**Comment by tobscure** [comment]
> Is there any valid use case where users would only be allowed to start discussions, but not to reply to them?

I think we can't rule that out. We should try and support this behaviour, it shouldn't be too hard.
