### ISSUE TITLE
[Emoji] Duplicate emojis on dropdown list

### ISSUE THREAD

**Issue by datitisev** [flarum/core#968]
Whenever I type `:tong`, the first 3 results are exactly the same.
I don't know if this is also a bug for other entries, I just know about the tongue emoji (:tongue:)

Screenshot:
![captura de pantalla 2016-05-25 a las 5 04 15 pm](https://cloud.githubusercontent.com/assets/6401250/15556260/0c39f178-229b-11e6-9821-421d8cd18fc1.png)

**Comment by dcsjapan** [comment]
Confirmed ... while responding to Franz's [long emoji thread](https://discuss.flarum.org/d/2957-favorite-long-emojis/3) I got more oden than I bargained for.

![screenshot](https://cloud.githubusercontent.com/assets/13129997/15561040/dfc65662-232c-11e6-84c1-60c7333fda0a.png)

It looks as though it might be offering recently selected items as suggestions ...

**Comment by franzliedke** [comment]
Darn, I wanted to fix this before any of you noticed. ;)

It's a small regresssion, part of my recent fix. Because we first search for exact matches from the beginning, and only switch to fuzzy matches if we haven't found enough (7) exact matches, it can sometimes happen that a fuzzy match duplicates an exact match.

Although, to be honest, that does not explain how "tongue" can appear three times.

**Comment by JoshyPHP** [comment]
@franzliedke I don't know how the dropdown works but if you deduplicate entries I recommend you do it by codepoint (e.g. `26f5`) rather than shortname. For instance, both `:book:` and `:open_book:` point to the same emoji: U+26F5. Typing this I found that's what GitHub does too, if you type `:open_` it will suggest `:book:`.

**Comment by franzliedke** [comment]
Cheers, fixed.
