### ISSUE TITLE
[Mentions] Change `reply` button to `quote` when post text selected

### ISSUE THREAD

**Issue by sijad** [flarum/core#972]
it should be easy to implement

**Comment by tobscure** [comment]
I think we should in fact do the opposite, and change the behaviour so that the Reply button acts as it does when no text is selected (i.e. it just opens a blank reply without any quoted text). Reason being, the quote functionality is already front-and-centre when you have selected text, so we should prefer consistency in the behaviour of the Reply button.

**Comment by datitisev** [comment]
@tobscure What about just changing it to "Quote" on mobile, because I know the "Quote" button doesn't appear in iOS because of the implemented text selected _thing_.

We could probably just change the button to "Quote" on mobile.

**Comment by tobscure** [comment]
Quote selection button not being available on mobile was a bug.
