### ISSUE TITLE
Wrong username and avatar in session menu/post composer

### ISSUE THREAD

**Issue by glombers** [flarum/core#985]
https://discuss.flarum.org/d/3196-wtf-why-is-no-my-account/2

**Comment by webeindustry** [comment]
glombers, you have at least 3 accts on the site. It's difficult to take this issue seriously without repro from other members.

**Comment by dcsjapan** [comment]
@glombers Posting under multiple accounts not only makes it difficult to take this issue seriously, it also makes things confusing when we do try to deal with an issue you posted. For this reason, we generally do not approve of the use of multiple accounts on the Flarum community website.

You've already had one account banned because your habit of creating extra accounts. Please stick with [the account you originally created](https://discuss.flarum.org/u/Weeboo) for all future posts.

As for your issue, we'd like to have independent confirmation from another user.

**Comment by glombers** [comment]
so but I can not do anything on the account so I put glombersik. strange that blew my sets. even the mail was not mine could change it. The same was [Bek](https://discuss.flarum.org/d/3196-shows-wrong-avatar-and-account)

**Comment by dcsjapan** [comment]
> so but I can not do anything on the account

Please explain that in detail.

**Comment by glombers** [comment]
I do not know what happened I went to the site I saw that I had 51 notyfications. then I saw that I was not on my account but when I commented post was normally

**Comment by glombers** [comment]
Or are you kidding us to deal with, or is a kind of magic

**Comment by dcsjapan** [comment]
I'm not understanding your problem. Are you sure you were actually logged in as Weeboo?

Please try logging out of Glombersik and logging in as Weeboo, and let us know what happens.

**Comment by glombers** [comment]
I logged on glombersika and had it:
http://prntscr.com/bgsb2f
normally should show glombersik

colleague **BEK**  interceded picture of my avatar in his account:
http://i.imgur.com/KZZBTAf.png

It's all as if for a moment there was a shift register or displayed a bad user sessions

**Comment by glombers** [comment]
but after reloading back it was normally

**Comment by dcsjapan** [comment]
Yes, I understood that part. I was asking for details about your problem using your Weeboo account. That's something we need to fix, if there's an issue there.

Please do as I asked and try logging in with that account.

**Comment by dcsjapan** [comment]
@tobscure Regarding the issue, Bek [has posted](https://discuss.flarum.org/d/3196-shows-wrong-avatar-and-account/22) with a link to information that seems related:

https://discuss.flarum.org/d/2352-flarum-v0-1-0-beta-5-released/121

Going by the response from @dav-is it seems the phenomenon experienced by @glombers could be the result of a caching issue. This needs to be looked at, especially if caching issues can expose information (such as email addresses) from another user's account, as @glombers has mentioned.

**Comment by webeindustry** [comment]
The issue was addressed weeks prior. @Luceos caught it within two minutes of implementing the nginx cache. I changed the cache key, and no issues were reported for the last few weeks until this morning. I moved discuss from the cloud instance to beta server, went about my daily tasks, and was alerted to what could be an issue here. This will need to be figured out, as it's a serious security issue. I'm trying to wrap my head around how it could appear solid for several weeks, and glitch out after swapping from the cloud back to beta.

**Comment by glombers** [comment]
This was so that the logging on your forum 2x once with github and once with Facebok still set up my two accounts with the same email

**Comment by jordanjay29** [comment]
@glombers Remind me which accounts are yours?

**Comment by glombers** [comment]
I do not remember the names
Glombersik - new account
Weeboo - account create witch FB
Weboss - account create witch FB

**Comment by jordanjay29** [comment]
Well, if you have two accounts created with the same FB account, Flarum would have just logged you into the same account rather than letting you sign up for another. 

Glombersik and Weeboo have different emails, so I don't think that's the cause. I can't find Weboss, it must be spelled differently or doesn't exist.

**Comment by glombers** [comment]
I assume a new account at github maybe this is the reason that again logged the same email but another username

**Comment by Luceos** [comment]
@webeindustry this freaks me out:

> I changed the cache key, and no issues were reported for the last few weeks until this morning.

😟 

Hope you find the cause or fix it differently.

**Comment by webeindustry** [comment]
It's permanently disabled.

See #980

**Comment by franzliedke** [comment]
As this issue is interspersed with so much off-topic communication, I'll close it. It's hard to see what's going on.

If the actual underlying issue is still a problem (and not reported elsewhere), you'd do me a big favor by opening a new issue that summarizes the problem and all the details related (and screenshots provided). If anybody would be willing to contribute the time to do that, that would be great. Thanks in advance!
